var annotated_dup =
[
    [ "DBus", "namespaceDBus.html", [
      [ "GLib", "namespaceDBus_1_1GLib.html", [
        [ "GLibDispatcher", "classDBus_1_1GLib_1_1GLibDispatcher.html", "classDBus_1_1GLib_1_1GLibDispatcher" ]
      ] ],
      [ "priv", "namespaceDBus_1_1priv.html", [
        [ "dbus_function_traits", "structDBus_1_1priv_1_1dbus__function__traits.html", null ],
        [ "dbus_function_traits< std::function< DBus::MultipleReturn< T_ret... >(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01DBus_1_1MultipleReturn_3_01ccdd8f64e56aceee42604171dfe33538.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01DBus_1_1MultipleReturn_3_01ccdd8f64e56aceee42604171dfe33538" ],
        [ "dbus_function_traits< std::function< T_ret(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01T__ret_07Args_8_8_8_08_4_01_4.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01T__ret_07Args_8_8_8_08_4_01_4" ],
        [ "dbus_function_traits< std::function< void(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01void_07Args_8_8_8_08_4_01_4.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01void_07Args_8_8_8_08_4_01_4" ],
        [ "dbus_signature", "classDBus_1_1priv_1_1dbus__signature.html", null ],
        [ "dbus_signature< arg1, argn... >", "classDBus_1_1priv_1_1dbus__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1dbus__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "dbus_signature<>", "classDBus_1_1priv_1_1dbus__signature_3_4.html", "classDBus_1_1priv_1_1dbus__signature_3_4" ],
        [ "method_signature", "classDBus_1_1priv_1_1method__signature.html", null ],
        [ "method_signature< arg1, argn... >", "classDBus_1_1priv_1_1method__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1method__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "method_signature<>", "classDBus_1_1priv_1_1method__signature_3_4.html", "classDBus_1_1priv_1_1method__signature_3_4" ],
        [ "multireturn_signature", "classDBus_1_1priv_1_1multireturn__signature.html", null ],
        [ "multireturn_signature< arg1, argn... >", "classDBus_1_1priv_1_1multireturn__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1multireturn__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "multireturn_signature<>", "classDBus_1_1priv_1_1multireturn__signature_3_4.html", "classDBus_1_1priv_1_1multireturn__signature_3_4" ],
        [ "SASL", "classDBus_1_1priv_1_1SASL.html", "classDBus_1_1priv_1_1SASL" ],
        [ "SendmsgTransport", "classDBus_1_1priv_1_1SendmsgTransport.html", "classDBus_1_1priv_1_1SendmsgTransport" ],
        [ "SignatureNode", "classDBus_1_1priv_1_1SignatureNode.html", "classDBus_1_1priv_1_1SignatureNode" ],
        [ "SimpleTransport", "classDBus_1_1priv_1_1SimpleTransport.html", "classDBus_1_1priv_1_1SimpleTransport" ],
        [ "Transport", "classDBus_1_1priv_1_1Transport.html", "classDBus_1_1priv_1_1Transport" ],
        [ "VariantAppendIterator", "classDBus_1_1priv_1_1VariantAppendIterator.html", "classDBus_1_1priv_1_1VariantAppendIterator" ],
        [ "VariantIterator", "classDBus_1_1priv_1_1VariantIterator.html", "classDBus_1_1priv_1_1VariantIterator" ]
      ] ],
      [ "Qt", "namespaceDBus_1_1Qt.html", [
        [ "QtDispatcher", "classDBus_1_1Qt_1_1QtDispatcher.html", "classDBus_1_1Qt_1_1QtDispatcher" ],
        [ "QtThreadDispatcher", "classDBus_1_1Qt_1_1QtThreadDispatcher.html", "classDBus_1_1Qt_1_1QtThreadDispatcher" ]
      ] ],
      [ "Uv", "namespaceDBus_1_1Uv.html", [
        [ "UvDispatcher", "classDBus_1_1Uv_1_1UvDispatcher.html", "classDBus_1_1Uv_1_1UvDispatcher" ]
      ] ],
      [ "CallMessage", "classDBus_1_1CallMessage.html", "classDBus_1_1CallMessage" ],
      [ "Connection", "classDBus_1_1Connection.html", "classDBus_1_1Connection" ],
      [ "DBusDaemonProxy", "classDBus_1_1DBusDaemonProxy.html", "classDBus_1_1DBusDaemonProxy" ],
      [ "Demarshaling", "classDBus_1_1Demarshaling.html", "classDBus_1_1Demarshaling" ],
      [ "Dispatcher", "classDBus_1_1Dispatcher.html", "classDBus_1_1Dispatcher" ],
      [ "Error", "classDBus_1_1Error.html", "classDBus_1_1Error" ],
      [ "ErrorAccessDenied", "classDBus_1_1ErrorAccessDenied.html", "classDBus_1_1ErrorAccessDenied" ],
      [ "ErrorAddressInUse", "classDBus_1_1ErrorAddressInUse.html", "classDBus_1_1ErrorAddressInUse" ],
      [ "ErrorAuthFailed", "classDBus_1_1ErrorAuthFailed.html", "classDBus_1_1ErrorAuthFailed" ],
      [ "ErrorBadAddress", "classDBus_1_1ErrorBadAddress.html", "classDBus_1_1ErrorBadAddress" ],
      [ "ErrorBadVariantCast", "classDBus_1_1ErrorBadVariantCast.html", "classDBus_1_1ErrorBadVariantCast" ],
      [ "ErrorDeadlock", "classDBus_1_1ErrorDeadlock.html", "classDBus_1_1ErrorDeadlock" ],
      [ "ErrorDisconnected", "classDBus_1_1ErrorDisconnected.html", "classDBus_1_1ErrorDisconnected" ],
      [ "ErrorDispatcherInitFailed", "classDBus_1_1ErrorDispatcherInitFailed.html", "classDBus_1_1ErrorDispatcherInitFailed" ],
      [ "ErrorFailed", "classDBus_1_1ErrorFailed.html", "classDBus_1_1ErrorFailed" ],
      [ "ErrorFileExists", "classDBus_1_1ErrorFileExists.html", "classDBus_1_1ErrorFileExists" ],
      [ "ErrorFileNotFound", "classDBus_1_1ErrorFileNotFound.html", "classDBus_1_1ErrorFileNotFound" ],
      [ "ErrorIncorrectDispatchThread", "classDBus_1_1ErrorIncorrectDispatchThread.html", "classDBus_1_1ErrorIncorrectDispatchThread" ],
      [ "ErrorInteractiveAuthorizationRequired", "classDBus_1_1ErrorInteractiveAuthorizationRequired.html", "classDBus_1_1ErrorInteractiveAuthorizationRequired" ],
      [ "ErrorInvalidAdaptee", "classDBus_1_1ErrorInvalidAdaptee.html", "classDBus_1_1ErrorInvalidAdaptee" ],
      [ "ErrorInvalidArgs", "classDBus_1_1ErrorInvalidArgs.html", "classDBus_1_1ErrorInvalidArgs" ],
      [ "ErrorInvalidCObject", "classDBus_1_1ErrorInvalidCObject.html", "classDBus_1_1ErrorInvalidCObject" ],
      [ "ErrorInvalidConnection", "classDBus_1_1ErrorInvalidConnection.html", "classDBus_1_1ErrorInvalidConnection" ],
      [ "ErrorInvalidFileContent", "classDBus_1_1ErrorInvalidFileContent.html", "classDBus_1_1ErrorInvalidFileContent" ],
      [ "ErrorInvalidMessage", "classDBus_1_1ErrorInvalidMessage.html", "classDBus_1_1ErrorInvalidMessage" ],
      [ "ErrorInvalidMessageType", "classDBus_1_1ErrorInvalidMessageType.html", "classDBus_1_1ErrorInvalidMessageType" ],
      [ "ErrorInvalidReturn", "classDBus_1_1ErrorInvalidReturn.html", "classDBus_1_1ErrorInvalidReturn" ],
      [ "ErrorInvalidSharedPtr", "classDBus_1_1ErrorInvalidSharedPtr.html", "classDBus_1_1ErrorInvalidSharedPtr" ],
      [ "ErrorInvalidSignature", "classDBus_1_1ErrorInvalidSignature.html", "classDBus_1_1ErrorInvalidSignature" ],
      [ "ErrorInvalidTypecast", "classDBus_1_1ErrorInvalidTypecast.html", "classDBus_1_1ErrorInvalidTypecast" ],
      [ "ErrorIOError", "classDBus_1_1ErrorIOError.html", "classDBus_1_1ErrorIOError" ],
      [ "ErrorLimitsExceeded", "classDBus_1_1ErrorLimitsExceeded.html", "classDBus_1_1ErrorLimitsExceeded" ],
      [ "ErrorMatchRule", "classDBus_1_1ErrorMatchRule.html", "classDBus_1_1ErrorMatchRule" ],
      [ "ErrorMatchRuleInvalid", "classDBus_1_1ErrorMatchRuleInvalid.html", "classDBus_1_1ErrorMatchRuleInvalid" ],
      [ "ErrorMatchRuleNotFound", "classDBus_1_1ErrorMatchRuleNotFound.html", "classDBus_1_1ErrorMatchRuleNotFound" ],
      [ "ErrorMessage", "classDBus_1_1ErrorMessage.html", "classDBus_1_1ErrorMessage" ],
      [ "ErrorMessageNestedTooDeep", "classDBus_1_1ErrorMessageNestedTooDeep.html", "classDBus_1_1ErrorMessageNestedTooDeep" ],
      [ "ErrorNameHasNoOwner", "classDBus_1_1ErrorNameHasNoOwner.html", "classDBus_1_1ErrorNameHasNoOwner" ],
      [ "ErrorNoConnection", "classDBus_1_1ErrorNoConnection.html", "classDBus_1_1ErrorNoConnection" ],
      [ "ErrorNoMemory", "classDBus_1_1ErrorNoMemory.html", "classDBus_1_1ErrorNoMemory" ],
      [ "ErrorNoNetwork", "classDBus_1_1ErrorNoNetwork.html", "classDBus_1_1ErrorNoNetwork" ],
      [ "ErrorNoReply", "classDBus_1_1ErrorNoReply.html", "classDBus_1_1ErrorNoReply" ],
      [ "ErrorNoServer", "classDBus_1_1ErrorNoServer.html", "classDBus_1_1ErrorNoServer" ],
      [ "ErrorNotInitialized", "classDBus_1_1ErrorNotInitialized.html", "classDBus_1_1ErrorNotInitialized" ],
      [ "ErrorNotOwner", "classDBus_1_1ErrorNotOwner.html", "classDBus_1_1ErrorNotOwner" ],
      [ "ErrorNotSupported", "classDBus_1_1ErrorNotSupported.html", "classDBus_1_1ErrorNotSupported" ],
      [ "ErrorPollFailed", "classDBus_1_1ErrorPollFailed.html", "classDBus_1_1ErrorPollFailed" ],
      [ "ErrorPropertyReadOnly", "classDBus_1_1ErrorPropertyReadOnly.html", "classDBus_1_1ErrorPropertyReadOnly" ],
      [ "ErrorRemoteException", "classDBus_1_1ErrorRemoteException.html", "classDBus_1_1ErrorRemoteException" ],
      [ "ErrorSELinuxSecurityContextUnknown", "classDBus_1_1ErrorSELinuxSecurityContextUnknown.html", "classDBus_1_1ErrorSELinuxSecurityContextUnknown" ],
      [ "ErrorServiceUnknown", "classDBus_1_1ErrorServiceUnknown.html", "classDBus_1_1ErrorServiceUnknown" ],
      [ "ErrorSpawnChildExited", "classDBus_1_1ErrorSpawnChildExited.html", "classDBus_1_1ErrorSpawnChildExited" ],
      [ "ErrorSpawnChildSignaled", "classDBus_1_1ErrorSpawnChildSignaled.html", "classDBus_1_1ErrorSpawnChildSignaled" ],
      [ "ErrorSpawnExecFailed", "classDBus_1_1ErrorSpawnExecFailed.html", "classDBus_1_1ErrorSpawnExecFailed" ],
      [ "ErrorSpawnFailed", "classDBus_1_1ErrorSpawnFailed.html", "classDBus_1_1ErrorSpawnFailed" ],
      [ "ErrorSpawnForkFailed", "classDBus_1_1ErrorSpawnForkFailed.html", "classDBus_1_1ErrorSpawnForkFailed" ],
      [ "ErrorTimedOut", "classDBus_1_1ErrorTimedOut.html", "classDBus_1_1ErrorTimedOut" ],
      [ "ErrorTimeout", "classDBus_1_1ErrorTimeout.html", "classDBus_1_1ErrorTimeout" ],
      [ "ErrorUnableToParse", "classDBus_1_1ErrorUnableToParse.html", "classDBus_1_1ErrorUnableToParse" ],
      [ "ErrorUnexpectedResponse", "classDBus_1_1ErrorUnexpectedResponse.html", "classDBus_1_1ErrorUnexpectedResponse" ],
      [ "ErrorUnixProcessIdUnknown", "classDBus_1_1ErrorUnixProcessIdUnknown.html", "classDBus_1_1ErrorUnixProcessIdUnknown" ],
      [ "ErrorUnknown", "classDBus_1_1ErrorUnknown.html", "classDBus_1_1ErrorUnknown" ],
      [ "ErrorUnknownInterface", "classDBus_1_1ErrorUnknownInterface.html", "classDBus_1_1ErrorUnknownInterface" ],
      [ "ErrorUnknownMethod", "classDBus_1_1ErrorUnknownMethod.html", "classDBus_1_1ErrorUnknownMethod" ],
      [ "ErrorUnknownObject", "classDBus_1_1ErrorUnknownObject.html", "classDBus_1_1ErrorUnknownObject" ],
      [ "ErrorUnknownProperty", "classDBus_1_1ErrorUnknownProperty.html", "classDBus_1_1ErrorUnknownProperty" ],
      [ "FileDescriptor", "classDBus_1_1FileDescriptor.html", "classDBus_1_1FileDescriptor" ],
      [ "Interface", "classDBus_1_1Interface.html", "classDBus_1_1Interface" ],
      [ "InterfaceProxy", "classDBus_1_1InterfaceProxy.html", "classDBus_1_1InterfaceProxy" ],
      [ "IntrospectableInterfaceProxy", "classDBus_1_1IntrospectableInterfaceProxy.html", "classDBus_1_1IntrospectableInterfaceProxy" ],
      [ "Marshaling", "classDBus_1_1Marshaling.html", "classDBus_1_1Marshaling" ],
      [ "MatchRule", "classDBus_1_1MatchRule.html", "classDBus_1_1MatchRule" ],
      [ "MatchRuleBuilder", "classDBus_1_1MatchRuleBuilder.html", "classDBus_1_1MatchRuleBuilder" ],
      [ "Message", "classDBus_1_1Message.html", "classDBus_1_1Message" ],
      [ "MessageAppendIterator", "classDBus_1_1MessageAppendIterator.html", "classDBus_1_1MessageAppendIterator" ],
      [ "MessageIterator", "classDBus_1_1MessageIterator.html", "classDBus_1_1MessageIterator" ],
      [ "Method", "classDBus_1_1Method.html", "classDBus_1_1Method" ],
      [ "MethodBase", "classDBus_1_1MethodBase.html", "classDBus_1_1MethodBase" ],
      [ "MethodCallMatchRule", "classDBus_1_1MethodCallMatchRule.html", "classDBus_1_1MethodCallMatchRule" ],
      [ "MethodProxy", "classDBus_1_1MethodProxy.html", null ],
      [ "MethodProxy< T_return(T_arg...)>", "classDBus_1_1MethodProxy_3_01T__return_07T__arg_8_8_8_08_4.html", "classDBus_1_1MethodProxy_3_01T__return_07T__arg_8_8_8_08_4" ],
      [ "MethodProxy< void(T_arg...)>", "classDBus_1_1MethodProxy_3_01void_07T__arg_8_8_8_08_4.html", "classDBus_1_1MethodProxy_3_01void_07T__arg_8_8_8_08_4" ],
      [ "MethodProxyBase", "classDBus_1_1MethodProxyBase.html", "classDBus_1_1MethodProxyBase" ],
      [ "MethodReturnMatchRule", "classDBus_1_1MethodReturnMatchRule.html", "classDBus_1_1MethodReturnMatchRule" ],
      [ "MultipleReturn", "classDBus_1_1MultipleReturn.html", "classDBus_1_1MultipleReturn" ],
      [ "Object", "classDBus_1_1Object.html", "classDBus_1_1Object" ],
      [ "ObjectManagerProxy", "classDBus_1_1ObjectManagerProxy.html", "classDBus_1_1ObjectManagerProxy" ],
      [ "ObjectProxy", "classDBus_1_1ObjectProxy.html", "classDBus_1_1ObjectProxy" ],
      [ "Path", "classDBus_1_1Path.html", "classDBus_1_1Path" ],
      [ "PeerInterfaceProxy", "classDBus_1_1PeerInterfaceProxy.html", "classDBus_1_1PeerInterfaceProxy" ],
      [ "PropertiesInterfaceProxy", "classDBus_1_1PropertiesInterfaceProxy.html", "classDBus_1_1PropertiesInterfaceProxy" ],
      [ "Property", "classDBus_1_1Property.html", "classDBus_1_1Property" ],
      [ "PropertyBase", "classDBus_1_1PropertyBase.html", "classDBus_1_1PropertyBase" ],
      [ "PropertyProxy", "classDBus_1_1PropertyProxy.html", "classDBus_1_1PropertyProxy" ],
      [ "PropertyProxyBase", "classDBus_1_1PropertyProxyBase.html", "classDBus_1_1PropertyProxyBase" ],
      [ "ReturnMessage", "classDBus_1_1ReturnMessage.html", "classDBus_1_1ReturnMessage" ],
      [ "Signal", "classDBus_1_1Signal.html", null ],
      [ "Signal< T_ret(T_args...)>", "classDBus_1_1Signal_3_01T__ret_07T__args_8_8_8_08_4.html", null ],
      [ "Signal< void(T_type...)>", "classDBus_1_1Signal_3_01void_07T__type_8_8_8_08_4.html", "classDBus_1_1Signal_3_01void_07T__type_8_8_8_08_4" ],
      [ "SignalBase", "classDBus_1_1SignalBase.html", "classDBus_1_1SignalBase" ],
      [ "SignalMatchRule", "classDBus_1_1SignalMatchRule.html", "classDBus_1_1SignalMatchRule" ],
      [ "SignalMessage", "classDBus_1_1SignalMessage.html", "classDBus_1_1SignalMessage" ],
      [ "SignalProxy", "classDBus_1_1SignalProxy.html", null ],
      [ "SignalProxy< void(T_arg...)>", "classDBus_1_1SignalProxy_3_01void_07T__arg_8_8_8_08_4.html", "classDBus_1_1SignalProxy_3_01void_07T__arg_8_8_8_08_4" ],
      [ "SignalProxyBase", "classDBus_1_1SignalProxyBase.html", "classDBus_1_1SignalProxyBase" ],
      [ "Signature", "classDBus_1_1Signature.html", "classDBus_1_1Signature" ],
      [ "SignatureIterator", "classDBus_1_1SignatureIterator.html", "classDBus_1_1SignatureIterator" ],
      [ "StandaloneDispatcher", "classDBus_1_1StandaloneDispatcher.html", "classDBus_1_1StandaloneDispatcher" ],
      [ "ThreadDispatcher", "classDBus_1_1ThreadDispatcher.html", "classDBus_1_1ThreadDispatcher" ],
      [ "TypeInfo", "classDBus_1_1TypeInfo.html", "classDBus_1_1TypeInfo" ],
      [ "Validator", "classDBus_1_1Validator.html", "classDBus_1_1Validator" ],
      [ "Variant", "classDBus_1_1Variant.html", "classDBus_1_1Variant" ]
    ] ],
    [ "CalleeClass", "classCalleeClass.html", "classCalleeClass" ],
    [ "SL_LogLocation", "structSL__LogLocation.html", "structSL__LogLocation" ]
];