var annotated_dup =
[
    [ "DBus", "namespaceDBus.html", [
      [ "priv", "namespaceDBus_1_1priv.html", [
        [ "SASL", "classDBus_1_1priv_1_1SASL.html", "classDBus_1_1priv_1_1SASL" ],
        [ "SendmsgTransport", "classDBus_1_1priv_1_1SendmsgTransport.html", "classDBus_1_1priv_1_1SendmsgTransport" ],
        [ "SignatureNode", "classDBus_1_1priv_1_1SignatureNode.html", "classDBus_1_1priv_1_1SignatureNode" ],
        [ "dbus_signature", "classDBus_1_1priv_1_1dbus__signature.html", null ],
        [ "dbus_signature<>", "classDBus_1_1priv_1_1dbus__signature_3_4.html", "classDBus_1_1priv_1_1dbus__signature_3_4" ],
        [ "dbus_signature< arg1, argn... >", "classDBus_1_1priv_1_1dbus__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1dbus__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "SimpleTransport", "classDBus_1_1priv_1_1SimpleTransport.html", "classDBus_1_1priv_1_1SimpleTransport" ],
        [ "Transport", "classDBus_1_1priv_1_1Transport.html", "classDBus_1_1priv_1_1Transport" ],
        [ "method_signature", "classDBus_1_1priv_1_1method__signature.html", null ],
        [ "method_signature<>", "classDBus_1_1priv_1_1method__signature_3_4.html", "classDBus_1_1priv_1_1method__signature_3_4" ],
        [ "method_signature< arg1, argn... >", "classDBus_1_1priv_1_1method__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1method__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "multireturn_signature", "classDBus_1_1priv_1_1multireturn__signature.html", null ],
        [ "multireturn_signature<>", "classDBus_1_1priv_1_1multireturn__signature_3_4.html", "classDBus_1_1priv_1_1multireturn__signature_3_4" ],
        [ "multireturn_signature< arg1, argn... >", "classDBus_1_1priv_1_1multireturn__signature_3_01arg1_00_01argn_8_8_8_01_4.html", "classDBus_1_1priv_1_1multireturn__signature_3_01arg1_00_01argn_8_8_8_01_4" ],
        [ "dbus_function_traits", "structDBus_1_1priv_1_1dbus__function__traits.html", null ],
        [ "dbus_function_traits< std::function< void(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01void_07Args_8_8_8_08_4_01_4.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01void_07Args_8_8_8_08_4_01_4" ],
        [ "dbus_function_traits< std::function< T_ret(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01T__ret_07Args_8_8_8_08_4_01_4.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01T__ret_07Args_8_8_8_08_4_01_4" ],
        [ "dbus_function_traits< std::function< DBus::MultipleReturn< T_ret... >(Args...)> >", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01DBus_1_1MultipleReturn_3_01ccdd8f64e56aceee42604171dfe33538.html", "structDBus_1_1priv_1_1dbus__function__traits_3_01std_1_1function_3_01DBus_1_1MultipleReturn_3_01ccdd8f64e56aceee42604171dfe33538" ],
        [ "VariantAppendIterator", "classDBus_1_1priv_1_1VariantAppendIterator.html", "classDBus_1_1priv_1_1VariantAppendIterator" ],
        [ "VariantIterator", "classDBus_1_1priv_1_1VariantIterator.html", "classDBus_1_1priv_1_1VariantIterator" ]
      ] ],
      [ "CallMessage", "classDBus_1_1CallMessage.html", "classDBus_1_1CallMessage" ],
      [ "Connection", "classDBus_1_1Connection.html", "classDBus_1_1Connection" ],
      [ "DBusDaemonProxy", "classDBus_1_1DBusDaemonProxy.html", "classDBus_1_1DBusDaemonProxy" ],
      [ "Demarshaling", "classDBus_1_1Demarshaling.html", "classDBus_1_1Demarshaling" ],
      [ "Dispatcher", "classDBus_1_1Dispatcher.html", "classDBus_1_1Dispatcher" ],
      [ "Error", "classDBus_1_1Error.html", "classDBus_1_1Error" ],
      [ "ErrorIncorrectDispatchThread", "classDBus_1_1ErrorIncorrectDispatchThread.html", "classDBus_1_1ErrorIncorrectDispatchThread" ],
      [ "ErrorRemoteException", "classDBus_1_1ErrorRemoteException.html", "classDBus_1_1ErrorRemoteException" ],
      [ "ErrorUnknown", "classDBus_1_1ErrorUnknown.html", "classDBus_1_1ErrorUnknown" ],
      [ "ErrorBadVariantCast", "classDBus_1_1ErrorBadVariantCast.html", "classDBus_1_1ErrorBadVariantCast" ],
      [ "ErrorUnableToParse", "classDBus_1_1ErrorUnableToParse.html", "classDBus_1_1ErrorUnableToParse" ],
      [ "ErrorInvalidMessage", "classDBus_1_1ErrorInvalidMessage.html", "classDBus_1_1ErrorInvalidMessage" ],
      [ "ErrorMessageNestedTooDeep", "classDBus_1_1ErrorMessageNestedTooDeep.html", "classDBus_1_1ErrorMessageNestedTooDeep" ],
      [ "ErrorMessage", "classDBus_1_1ErrorMessage.html", "classDBus_1_1ErrorMessage" ],
      [ "FileDescriptor", "classDBus_1_1FileDescriptor.html", "classDBus_1_1FileDescriptor" ],
      [ "Interface", "classDBus_1_1Interface.html", "classDBus_1_1Interface" ],
      [ "MethodProxy", "classDBus_1_1MethodProxy.html", null ],
      [ "InterfaceProxy", "classDBus_1_1InterfaceProxy.html", "classDBus_1_1InterfaceProxy" ],
      [ "Marshaling", "classDBus_1_1Marshaling.html", "classDBus_1_1Marshaling" ],
      [ "MatchRule", "classDBus_1_1MatchRule.html", "classDBus_1_1MatchRule" ],
      [ "SignalMatchRule", "classDBus_1_1SignalMatchRule.html", "classDBus_1_1SignalMatchRule" ],
      [ "MethodCallMatchRule", "classDBus_1_1MethodCallMatchRule.html", "classDBus_1_1MethodCallMatchRule" ],
      [ "MethodReturnMatchRule", "classDBus_1_1MethodReturnMatchRule.html", "classDBus_1_1MethodReturnMatchRule" ],
      [ "ErrorMatchRule", "classDBus_1_1ErrorMatchRule.html", "classDBus_1_1ErrorMatchRule" ],
      [ "MatchRuleBuilder", "classDBus_1_1MatchRuleBuilder.html", "classDBus_1_1MatchRuleBuilder" ],
      [ "Message", "classDBus_1_1Message.html", "classDBus_1_1Message" ],
      [ "MessageAppendIterator", "classDBus_1_1MessageAppendIterator.html", "classDBus_1_1MessageAppendIterator" ],
      [ "MultipleReturn", "classDBus_1_1MultipleReturn.html", "classDBus_1_1MultipleReturn" ],
      [ "MessageIterator", "classDBus_1_1MessageIterator.html", "classDBus_1_1MessageIterator" ],
      [ "MethodBase", "classDBus_1_1MethodBase.html", "classDBus_1_1MethodBase" ],
      [ "Method", "classDBus_1_1Method.html", "classDBus_1_1Method" ],
      [ "MethodProxyBase", "classDBus_1_1MethodProxyBase.html", "classDBus_1_1MethodProxyBase" ],
      [ "MethodProxy< void(T_arg...)>", "classDBus_1_1MethodProxy_3_01void_07T__arg_8_8_8_08_4.html", "classDBus_1_1MethodProxy_3_01void_07T__arg_8_8_8_08_4" ],
      [ "MethodProxy< T_return(T_arg...)>", "classDBus_1_1MethodProxy_3_01T__return_07T__arg_8_8_8_08_4.html", "classDBus_1_1MethodProxy_3_01T__return_07T__arg_8_8_8_08_4" ],
      [ "Object", "classDBus_1_1Object.html", "classDBus_1_1Object" ],
      [ "ObjectProxy", "classDBus_1_1ObjectProxy.html", "classDBus_1_1ObjectProxy" ],
      [ "Path", "classDBus_1_1Path.html", "classDBus_1_1Path" ],
      [ "PropertyBase", "classDBus_1_1PropertyBase.html", "classDBus_1_1PropertyBase" ],
      [ "Property", "classDBus_1_1Property.html", "classDBus_1_1Property" ],
      [ "PropertyProxyBase", "classDBus_1_1PropertyProxyBase.html", "classDBus_1_1PropertyProxyBase" ],
      [ "PropertyProxy", "classDBus_1_1PropertyProxy.html", "classDBus_1_1PropertyProxy" ],
      [ "ReturnMessage", "classDBus_1_1ReturnMessage.html", "classDBus_1_1ReturnMessage" ],
      [ "Signal", "classDBus_1_1Signal.html", null ],
      [ "Signal< T_ret(T_args...)>", "classDBus_1_1Signal_3_01T__ret_07T__args_8_8_8_08_4.html", null ],
      [ "Signal< void(T_type...)>", "classDBus_1_1Signal_3_01void_07T__type_8_8_8_08_4.html", "classDBus_1_1Signal_3_01void_07T__type_8_8_8_08_4" ],
      [ "SignalBase", "classDBus_1_1SignalBase.html", "classDBus_1_1SignalBase" ],
      [ "SignalMessage", "classDBus_1_1SignalMessage.html", "classDBus_1_1SignalMessage" ],
      [ "SignalProxy", "classDBus_1_1SignalProxy.html", null ],
      [ "SignalProxyBase", "classDBus_1_1SignalProxyBase.html", "classDBus_1_1SignalProxyBase" ],
      [ "SignalProxy< void(T_arg...)>", "classDBus_1_1SignalProxy_3_01void_07T__arg_8_8_8_08_4.html", "classDBus_1_1SignalProxy_3_01void_07T__arg_8_8_8_08_4" ],
      [ "Signature", "classDBus_1_1Signature.html", "classDBus_1_1Signature" ],
      [ "SignatureIterator", "classDBus_1_1SignatureIterator.html", "classDBus_1_1SignatureIterator" ],
      [ "StandaloneDispatcher", "classDBus_1_1StandaloneDispatcher.html", "classDBus_1_1StandaloneDispatcher" ],
      [ "IntrospectableInterfaceProxy", "classDBus_1_1IntrospectableInterfaceProxy.html", "classDBus_1_1IntrospectableInterfaceProxy" ],
      [ "PeerInterfaceProxy", "classDBus_1_1PeerInterfaceProxy.html", "classDBus_1_1PeerInterfaceProxy" ],
      [ "PropertiesInterfaceProxy", "classDBus_1_1PropertiesInterfaceProxy.html", "classDBus_1_1PropertiesInterfaceProxy" ],
      [ "ThreadDispatcher", "classDBus_1_1ThreadDispatcher.html", "classDBus_1_1ThreadDispatcher" ],
      [ "TypeInfo", "classDBus_1_1TypeInfo.html", "classDBus_1_1TypeInfo" ],
      [ "Validator", "classDBus_1_1Validator.html", "classDBus_1_1Validator" ],
      [ "Variant", "classDBus_1_1Variant.html", "classDBus_1_1Variant" ]
    ] ],
    [ "ErrorAccessDenied", "classErrorAccessDenied.html", null ],
    [ "ErrorAddressInUse", "classErrorAddressInUse.html", null ],
    [ "ErrorAuthFailed", "classErrorAuthFailed.html", null ],
    [ "ErrorBadAddress", "classErrorBadAddress.html", null ],
    [ "ErrorDeadlock", "classErrorDeadlock.html", null ],
    [ "ErrorDisconnected", "classErrorDisconnected.html", null ],
    [ "ErrorDispatcherInitFailed", "classErrorDispatcherInitFailed.html", null ],
    [ "ErrorFailed", "classErrorFailed.html", null ],
    [ "ErrorFileExists", "classErrorFileExists.html", null ],
    [ "ErrorFileNotFound", "classErrorFileNotFound.html", null ],
    [ "ErrorInvalidAdaptee", "classErrorInvalidAdaptee.html", null ],
    [ "ErrorInvalidArgs", "classErrorInvalidArgs.html", null ],
    [ "ErrorInvalidCObject", "classErrorInvalidCObject.html", null ],
    [ "ErrorInvalidConnection", "classErrorInvalidConnection.html", null ],
    [ "ErrorInvalidFileContent", "classErrorInvalidFileContent.html", null ],
    [ "ErrorInvalidMessageType", "classErrorInvalidMessageType.html", null ],
    [ "ErrorInvalidSharedPtr", "classErrorInvalidSharedPtr.html", null ],
    [ "ErrorInvalidSignature", "classErrorInvalidSignature.html", null ],
    [ "ErrorInvalidTypecast", "classErrorInvalidTypecast.html", null ],
    [ "ErrorIOError", "classErrorIOError.html", null ],
    [ "ErrorLimitsExceeded", "classErrorLimitsExceeded.html", null ],
    [ "ErrorMatchRuleInvalid", "classErrorMatchRuleInvalid.html", null ],
    [ "ErrorMatchRuleNotFound", "classErrorMatchRuleNotFound.html", null ],
    [ "ErrorNameHasNoOwner", "classErrorNameHasNoOwner.html", null ],
    [ "ErrorNoConnection", "classErrorNoConnection.html", null ],
    [ "ErrorNoMemory", "classErrorNoMemory.html", null ],
    [ "ErrorNoNetwork", "classErrorNoNetwork.html", null ],
    [ "ErrorNoReply", "classErrorNoReply.html", null ],
    [ "ErrorNoServer", "classErrorNoServer.html", null ],
    [ "ErrorNotInitialized", "classErrorNotInitialized.html", null ],
    [ "ErrorNotOwner", "classErrorNotOwner.html", null ],
    [ "ErrorNotSupported", "classErrorNotSupported.html", null ],
    [ "ErrorPollFailed", "classErrorPollFailed.html", null ],
    [ "ErrorPropertyReadOnly", "classErrorPropertyReadOnly.html", null ],
    [ "ErrorSELinuxSecurityContextUnknown", "classErrorSELinuxSecurityContextUnknown.html", null ],
    [ "ErrorServiceUnknown", "classErrorServiceUnknown.html", null ],
    [ "ErrorSpawnChildExited", "classErrorSpawnChildExited.html", null ],
    [ "ErrorSpawnChildSignaled", "classErrorSpawnChildSignaled.html", null ],
    [ "ErrorSpawnExecFailed", "classErrorSpawnExecFailed.html", null ],
    [ "ErrorSpawnFailed", "classErrorSpawnFailed.html", null ],
    [ "ErrorSpawnForkFailed", "classErrorSpawnForkFailed.html", null ],
    [ "ErrorTimedOut", "classErrorTimedOut.html", null ],
    [ "ErrorTimeout", "classErrorTimeout.html", null ],
    [ "ErrorUnixProcessIdUnknown", "classErrorUnixProcessIdUnknown.html", null ],
    [ "ErrorUnknownInterface", "classErrorUnknownInterface.html", null ],
    [ "ErrorUnknownMethod", "classErrorUnknownMethod.html", null ],
    [ "ErrorUnknownObject", "classErrorUnknownObject.html", null ],
    [ "ErrorUnknownProperty", "classErrorUnknownProperty.html", null ],
    [ "SL_LogLocation", "structSL__LogLocation.html", "structSL__LogLocation" ]
];