DBus::MessageHandler Class Reference
DBus::MessageHandler Class Reference
Objects | Local Objects
This class provides a common base class for all message handlers.
#include <messagehandler.h>
Public Types
typedef DBusCxxPointer< MessageHandler > pointer
typedef DBusCxxWeakPointer< MessageHandler > weak_pointer
typedef sigc::signal< HandlerResult, DBusCxxPointer< Connection >, Message::const_pointer >::accumulated< MessageHandlerAccumulator > MessageSignal
Public Member Functions
virtual ~MessageHandler ()
virtual HandlerResult handle_message (DBusCxxPointer< Connection >, Message::const_pointer)
The default implementation simply emits the message signal and returns the result.
MessageSignal & signal_message ()
Protected Member Functions
MessageHandler ()
Static Protected Member Functions
static DBusHandlerResult message_handler_callback (DBusConnection *connection, DBusMessage *message, void *user_data)
When used as a callback, this method expects.
Protected Attributes
MessageSignal m_signal_message
Detailed Description
This class provides a common base class for all message handlers.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
MessageSignal
typedef sigc::signal<HandlerResult,DBusCxxPointer<Connection>, Message::const_pointer>::accumulated<MessageHandlerAccumulator> DBus::MessageHandler::MessageSignal
pointer
typedef DBusCxxPointer<MessageHandler> DBus::MessageHandler::pointer
weak_pointer
typedef DBusCxxWeakPointer<MessageHandler> DBus::MessageHandler::weak_pointer
Constructor & Destructor Documentation
MessageHandler()
DBus::MessageHandler::MessageHandler () protected
~MessageHandler()
DBus::MessageHandler::~MessageHandler () virtual
Member Function Documentation
handle_message()
HandlerResult DBus::MessageHandler::handle_message (DBusCxxPointer< Connection > conn, Message::const_pointer msg) virtual
The default implementation simply emits the message signal and returns the result.
Reimplemented in DBus::Object, and DBus::SignalReceiver.
References m_signal_message.
Referenced by message_handler_callback().
message_handler_callback()
DBusHandlerResult DBus::MessageHandler::message_handler_callback (DBusConnection * connection, DBusMessage * message, void * user_data) static protected
When used as a callback, this method expects.
Parameters
user_data to contain a pointer to the MessageHandler instance.
References DBus::Message::create(), handle_message(), and DBus::Connection::self().
signal_message()
MessageHandler::MessageSignal & DBus::MessageHandler::signal_message ()
References m_signal_message.
Member Data Documentation
m_signal_message
MessageSignal DBus::MessageHandler::m_signal_message protected
Referenced by handle_message(), DBus::SignalReceiver::handle_message(), and signal_message().
The documentation for this class was generated from the following files:
messagehandler.h
messagehandler.cpp