dbus-cxx: DBus::MessageAppendIterator Class Reference
DBus::MessageAppendIterator Class Reference
DBus Messages
Insertion iterator allow values to be appended to a message.
#include <messageappenditerator.h>
Public Member Functions
MessageAppendIterator ()
MessageAppendIterator (Message &message)
MessageAppendIterator (DBusCxxPointer< Message > message)
~MessageAppendIterator ()
const Message * message () const
Returns a pointer to the message associated with this iterator or NULL if no message is associated.
DBusMessageIter * cobj ()
Returns a pointer to the underlying DBusMessageIter object.
bool init (Message &message)
Initializes the iterator for the specified message.
void invalidate ()
Invalidates the iterator.
bool is_valid () const
True if this is a valid iterator.
operator bool () const
True if the iterator is valid and initialized, false otherwise.
bool append (bool v)
bool append (uint8_t v)
bool append (int16_t v)
bool append (uint16_t v)
bool append (int32_t v)
bool append (uint32_t v)
bool append (int64_t v)
bool append (uint64_t v)
bool append (double v)
bool append (const char *v)
bool append (const std::string &v)
bool append (const Signature &v)
bool append (const Path &v)
bool append (const FileDescriptor::pointer &fd)
bool append (char v)
bool append (int8_t v)
bool append (float v)
template<typename T >
bool append (const std::vector< T > &v)
template<typename Key , typename Data >
bool append (const std::map< Key, Data > &dictionary)
template<typename T >
bool append (const Variant< T > &var)
template<typename T >
MessageAppendIterator & operator<< (const T &v)
bool open_container (ContainerType t, const std::string &contained_signature)
bool close_container ()
MessageAppendIterator * sub_iterator ()
Protected Member Functions
template<typename T >
bool protected_append (const T &v)
bool protected_append (const bool &v)
bool protected_append (const std::string &v)
bool protected_append (const Signature &v)
bool protected_append (const Path &v)
bool protected_append (const FileDescriptor::pointer &fd)
Protected Attributes
Message * m_message
DBusMessageIter m_cobj
MessageAppendIterator * m_subiter
Detailed Description
Insertion iterator allow values to be appended to a message.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
MessageAppendIterator() [1/3]
DBus::MessageAppendIterator::MessageAppendIterator ()
References m_cobj.
Referenced by open_container().
MessageAppendIterator() [2/3]
DBus::MessageAppendIterator::MessageAppendIterator (Message & message)
References init(), and m_cobj.
MessageAppendIterator() [3/3]
DBus::MessageAppendIterator::MessageAppendIterator (DBusCxxPointer< Message > message)
References init(), and m_cobj.
~MessageAppendIterator()
DBus::MessageAppendIterator::~MessageAppendIterator ()
Member Function Documentation
append() [1/20]
bool DBus::MessageAppendIterator::append (bool v)
References protected_append().
Referenced by append(), and operator<<().
append() [2/20]
bool DBus::MessageAppendIterator::append (uint8_t v)
References protected_append().
append() [3/20]
bool DBus::MessageAppendIterator::append (int16_t v)
References protected_append().
append() [4/20]
bool DBus::MessageAppendIterator::append (uint16_t v)
References protected_append().
append() [5/20]
bool DBus::MessageAppendIterator::append (int32_t v)
References protected_append().
append() [6/20]
bool DBus::MessageAppendIterator::append (uint32_t v)
References protected_append().
append() [7/20]
bool DBus::MessageAppendIterator::append (int64_t v)
References protected_append().
append() [8/20]
bool DBus::MessageAppendIterator::append (uint64_t v)
References protected_append().
append() [9/20]
bool DBus::MessageAppendIterator::append (double v)
References protected_append().
append() [10/20]
bool DBus::MessageAppendIterator::append (const char * v)
References protected_append().
append() [11/20]
bool DBus::MessageAppendIterator::append (const std::string & v)
References protected_append().
append() [12/20]
bool DBus::MessageAppendIterator::append (const Signature & v)
References protected_append().
append() [13/20]
bool DBus::MessageAppendIterator::append (const Path & v)
References protected_append().
append() [14/20]
bool DBus::MessageAppendIterator::append (const FileDescriptor::pointer & fd)
References append(), and protected_append().
append() [15/20]
bool DBus::MessageAppendIterator::append (char v)
References protected_append().
append() [16/20]
bool DBus::MessageAppendIterator::append (int8_t v)
References protected_append().
append() [17/20]
bool DBus::MessageAppendIterator::append (float v)
References protected_append().
append() [18/20]
template<typename T > bool DBus::MessageAppendIterator::append (const std::vector< T > & v) inline
References close_container(), DBus::CONTAINER_ARRAY, m_subiter, open_container(), DBus::signature(), and DBus::type().
append() [19/20]
template<typename Key , typename Data > bool DBus::MessageAppendIterator::append (const std::map< Key, Data > & dictionary) inline
References append(), close_container(), DBus::CONTAINER_ARRAY, DBus::CONTAINER_DICT_ENTRY, m_subiter, open_container(), and DBus::signature_dict_data().
append() [20/20]
template<typename T > bool DBus::MessageAppendIterator::append (const Variant< T > & var) inline
References append(), close_container(), DBus::CONTAINER_VARIANT, DBus::Variant< T >::data, m_subiter, open_container(), and DBus::signature().
close_container()
bool DBus::MessageAppendIterator::close_container ()
References cobj(), m_cobj, and m_subiter.
Referenced by append(), open_container(), and operator<<().
cobj()
DBusMessageIter * DBus::MessageAppendIterator::cobj ()
Returns a pointer to the underlying DBusMessageIter object.
References m_cobj.
Referenced by close_container(), and open_container().
init()
bool DBus::MessageAppendIterator::init (Message & message)
Initializes the iterator for the specified message.
References DBus::Message::cobj(), m_cobj, m_message, m_subiter, and message().
Referenced by MessageAppendIterator().
invalidate()
void DBus::MessageAppendIterator::invalidate ()
Invalidates the iterator.
References m_cobj, m_message, and m_subiter.
is_valid()
bool DBus::MessageAppendIterator::is_valid () const
True if this is a valid iterator.
References DBus::Message::is_valid(), and m_message.
Referenced by operator bool(), and protected_append().
message()
const Message* DBus::MessageAppendIterator::message () const
Returns a pointer to the message associated with this iterator or NULL if no message is associated.
Referenced by init().
open_container()
bool DBus::MessageAppendIterator::open_container (ContainerType t, const std::string & contained_signature)
References close_container(), cobj(), DBus::CONTAINER_DICT_ENTRY, DBus::CONTAINER_STRUCT, m_cobj, m_message, m_subiter, and MessageAppendIterator().
Referenced by append(), and operator<<().
operator bool()
DBus::MessageAppendIterator::operator bool () const
True if the iterator is valid and initialized, false otherwise.
References is_valid().
operator<<()
template<typename T > MessageAppendIterator& DBus::MessageAppendIterator::operator<< (const T & v) inline
References append(), close_container(), open_container(), and sub_iterator().
protected_append() [1/6]
template<typename T > bool DBus::MessageAppendIterator::protected_append (const T & v) inline protected
References DBus::Message::invalidate(), is_valid(), m_cobj, m_message, and DBus::type().
Referenced by append(), and protected_append().
protected_append() [2/6]
bool DBus::MessageAppendIterator::protected_append (const bool & v) protected
References DBus::Message::invalidate(), is_valid(), m_cobj, m_message, and DBus::TYPE_BOOLEAN.
protected_append() [3/6]
bool DBus::MessageAppendIterator::protected_append (const std::string & v) protected
References protected_append().
protected_append() [4/6]
bool DBus::MessageAppendIterator::protected_append (const Signature & v) protected
References DBus::Message::invalidate(), is_valid(), m_cobj, m_message, and DBus::TYPE_SIGNATURE.
protected_append() [5/6]
bool DBus::MessageAppendIterator::protected_append (const Path & v) protected
References DBus::Message::invalidate(), is_valid(), m_cobj, m_message, and DBus::TYPE_OBJECT_PATH.
protected_append() [6/6]
bool DBus::MessageAppendIterator::protected_append (const FileDescriptor::pointer & fd) protected
References DBus::Message::invalidate(), is_valid(), m_cobj, m_message, and DBus::type().
sub_iterator()
MessageAppendIterator * DBus::MessageAppendIterator::sub_iterator ()
References m_subiter.
Referenced by operator<<().
Member Data Documentation
m_cobj
DBusMessageIter DBus::MessageAppendIterator::m_cobj protected
Referenced by close_container(), cobj(), init(), invalidate(), MessageAppendIterator(), open_container(), and protected_append().
m_message
Message* DBus::MessageAppendIterator::m_message protected
Referenced by init(), invalidate(), is_valid(), open_container(), and protected_append().
m_subiter
MessageAppendIterator* DBus::MessageAppendIterator::m_subiter protected
Referenced by append(), close_container(), init(), invalidate(), open_container(), and sub_iterator().
The documentation for this class was generated from the following files:
messageappenditerator.h
messageappenditerator.cpp