dbus-cxx: DBus::CallMessage Class Reference
DBus::CallMessage Class Reference
DBus Messages
Represents a DBus call message.
#include <callmessage.h>
Public Types
typedef DBusCxxPointer< CallMessage > pointer
typedef DBusCxxPointer< const CallMessage > const_pointer
typedef DBusCxxWeakPointer< CallMessage > weak_pointer
Public Types inherited from DBus::Message
typedef DBusCxxPointer< Message > pointer
typedef DBusCxxPointer< const Message > const_pointer
typedef DBusCxxWeakPointer< Message > weak_pointer
typedef MessageIterator iterator
typedef MessageAppendIterator append_iterator
Public Member Functions
bool set_path (const std::string &p)
Path path () const
bool has_path (const std::string &p) const
std::vector< std::string > path_decomposed () const
bool set_interface (const std::string &i)
const char * interface () const
bool has_interface (const std::string &i) const
bool set_member (const std::string &m)
const char * member () const
bool has_member (const std::string &m) const
const char * signature () const
bool has_signature (const std::string &signature) const
bool operator== (const CallMessage &) const
void set_no_reply (bool no_reply=true)
bool expects_reply () const
Public Member Functions inherited from DBus::Message
DBusCxxPointer< ReturnMessage > create_reply () const
virtual ~Message ()
Message & operator= (const Message &m)
bool operator== (const Message &other)
bool is_valid () const
void invalidate ()
operator bool () const
uint32_t serial () const
int type () const
void set_auto_start (bool auto_start)
bool auto_start ()
bool set_destination (const std::string &s)
const char * destination () const
bool set_sender (const std::string &s)
const char * sender () const
bool is_call (const std::string &interface, const std::string &method) const
bool is_signal (const std::string &interface, const std::string &signal_name) const
bool is_error (const std::string &error_name) const
bool has_destination (const std::string &name) const
bool has_sender (const std::string &name) const
template<typename T >
iterator operator>> (T &value) const
template<typename T >
append_iterator operator<< (const T &value)
iterator begin () const
iterator end () const
append_iterator append ()
DBusMessage * cobj () const
Static Public Member Functions
static pointer create ()
static pointer create (DBusMessage *cobj)
static pointer create (Message::pointer msg)
static const_pointer create (Message::const_pointer msg)
static pointer create (const std::string &dest, const std::string &path, const std::string &iface, const std::string &method)
static pointer create (const std::string &path, const std::string &iface, const std::string &method)
static pointer create (const std::string &path, const std::string &method)
Static Public Member Functions inherited from DBus::Message
static pointer create (MessageType type)
static pointer create (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::pointer other, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Protected Member Functions
CallMessage ()
CallMessage (DBusMessage *cobj)
CallMessage (Message::pointer msg)
CallMessage (Message::const_pointer msg)
CallMessage (const std::string &dest, const std::string &path, const std::string &iface, const std::string &method)
CallMessage (const std::string &path, const std::string &iface, const std::string &method)
CallMessage (const std::string &path, const std::string &method)
Protected Member Functions inherited from DBus::Message
Message (MessageType type)
Message (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
Message (Message::pointer other, CreateMethod m=CREATE_ALIAS)
Message (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Additional Inherited Members
Protected Attributes inherited from DBus::Message
DBusMessage * m_cobj
bool m_valid
Detailed Description
Represents a DBus call message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for a call message.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
const_pointer
typedef DBusCxxPointer<const CallMessage> DBus::CallMessage::const_pointer
pointer
typedef DBusCxxPointer<CallMessage> DBus::CallMessage::pointer
weak_pointer
typedef DBusCxxWeakPointer<CallMessage> DBus::CallMessage::weak_pointer
Constructor & Destructor Documentation
CallMessage() [1/7]
DBus::CallMessage::CallMessage () protected
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
Referenced by create().
CallMessage() [2/7]
DBus::CallMessage::CallMessage (DBusMessage * cobj) protected
References DBus::Message::cobj(), and DBus::Message::m_cobj.
CallMessage() [3/7]
DBus::CallMessage::CallMessage (Message::pointer msg) protected
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
CallMessage() [4/7]
DBus::CallMessage::CallMessage (Message::const_pointer msg) protected
References DBus::CALL_MESSAGE, and DBus::Message::m_cobj.
CallMessage() [5/7]
DBus::CallMessage::CallMessage (const std::string & dest, const std::string & path, const std::string & iface, const std::string & method) protected
References DBus::Message::m_cobj, and DBus::Message::m_valid.
CallMessage() [6/7]
DBus::CallMessage::CallMessage (const std::string & path, const std::string & iface, const std::string & method) protected
References DBus::Message::m_cobj, and DBus::Message::m_valid.
CallMessage() [7/7]
DBus::CallMessage::CallMessage (const std::string & path, const std::string & method) protected
References DBus::Message::m_cobj, and DBus::Message::m_valid.
Member Function Documentation
create() [1/7]
CallMessage::pointer DBus::CallMessage::create () static
Examples:
callee_raw.cpp, and caller_raw.cpp.
References CallMessage().
Referenced by DBus::ObjectProxy::create_call_message(), DBus::Object::handle_message(), and DBus::Connection::introspect().
create() [2/7]
CallMessage::pointer DBus::CallMessage::create (DBusMessage * cobj) static
References CallMessage().
create() [3/7]
CallMessage::pointer DBus::CallMessage::create (Message::pointer msg) static
References CallMessage().
create() [4/7]
CallMessage::const_pointer DBus::CallMessage::create (Message::const_pointer msg) static
References CallMessage().
create() [5/7]
CallMessage::pointer DBus::CallMessage::create (const std::string & dest, const std::string & path, const std::string & iface, const std::string & method) static
References CallMessage().
create() [6/7]
CallMessage::pointer DBus::CallMessage::create (const std::string & path, const std::string & iface, const std::string & method) static
References CallMessage().
create() [7/7]
CallMessage::pointer DBus::CallMessage::create (const std::string & path, const std::string & method) static
References CallMessage().
expects_reply()
bool DBus::CallMessage::expects_reply () const
References DBus::Message::m_cobj.
has_interface()
bool DBus::CallMessage::has_interface (const std::string & i) const
References DBus::Message::m_cobj.
has_member()
bool DBus::CallMessage::has_member (const std::string & m) const
References DBus::Message::m_cobj.
has_path()
bool DBus::CallMessage::has_path (const std::string & p) const
References DBus::Message::m_cobj.
has_signature()
bool DBus::CallMessage::has_signature (const std::string & signature) const
References DBus::Message::m_cobj.
interface()
const char * DBus::CallMessage::interface () const
References DBus::Message::m_cobj.
Referenced by operator==().
member()
const char * DBus::CallMessage::member () const
References DBus::Message::m_cobj.
Referenced by operator==().
operator==()
bool DBus::CallMessage::operator== (const CallMessage & m) const
References interface(), DBus::Message::m_cobj, and member().
path()
Path DBus::CallMessage::path () const
References DBus::Message::m_cobj.
path_decomposed()
std::vector< std::string > DBus::CallMessage::path_decomposed () const
References DBus::Message::m_cobj.
set_interface()
bool DBus::CallMessage::set_interface (const std::string & i)
References DBus::Message::m_cobj.
set_member()
bool DBus::CallMessage::set_member (const std::string & m)
References DBus::Message::m_cobj.
set_no_reply()
void DBus::CallMessage::set_no_reply (bool no_reply = true)
References DBus::Message::m_cobj.
set_path()
bool DBus::CallMessage::set_path (const std::string & p)
References DBus::Message::m_cobj.
signature()
const char * DBus::CallMessage::signature () const
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
callmessage.h
callmessage.cpp