DBus::ObjectProxy Class Reference
DBus::ObjectProxy Class Reference
Proxy | Objects
Object proxies are local proxies that provide local methods and signals for remote objects with dbus interfaces.
#include <objectproxy.h>
Public Types
typedef DBusCxxPointer< ObjectProxy > pointer
Typedef to smart pointers to ObjectProxy.
typedef std::multimap< std::string, InterfaceProxy::pointer > Interfaces
Public Member Functions
virtual ~ObjectProxy ()
DBusCxxPointer< Connection > connection () const
void set_connection (DBusCxxPointer< Connection > conn)
const std::string & destination () const
void set_destination (const std::string &destination)
const Path & path () const
void set_path (const std::string &path)
const Interfaces & interfaces () const
InterfaceProxy::pointer interface (const std::string &name) const
Returns the first interface with the given name.
InterfaceProxy::pointer operator[] (const std::string &name) const
Alias for interface(name)
bool add_interface (InterfaceProxy::pointer interface)
Adds the interface to this object.
InterfaceProxy::pointer create_interface (const std::string &name)
Creates and adds the named interface to this object.
void remove_interface (const std::string &name)
Removes the first interface with the given name.
void remove_interface (InterfaceProxy::pointer interface)
Removes the given interface.
bool has_interface (const std::string &name) const
bool has_interface (InterfaceProxy::pointer interface) const
InterfaceProxy::pointer default_interface () const
bool set_default_interface (const std::string &new_default_name)
bool set_default_interface (InterfaceProxy::pointer new_default)
void remove_default_interface ()
bool add_method (const std::string &interface, MethodProxyBase::pointer method)
Adds the method to the named interface.
bool add_method (MethodProxyBase::pointer method)
Adds the method to the default interface.
CallMessage::pointer create_call_message (const std::string &interface_name, const std::string &method_name) const
CallMessage::pointer create_call_message (const std::string &method_name) const
ReturnMessage::const_pointer call (CallMessage::const_pointer, int timeout_milliseconds=-1) const
PendingCall::pointer call_async (CallMessage::const_pointer, int timeout_milliseconds=-1) const
template<class T_return >
DBusCxxPointer< MethodProxy< T_return > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 >
DBusCxxPointer< MethodProxy< T_return, T_arg1 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_return >
DBusCxxPointer< signal_proxy< T_return > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 >
DBusCxxPointer< signal_proxy< T_return, T_arg1 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
sigc::signal< void, InterfaceProxy::pointer > signal_interface_added ()
sigc::signal< void, InterfaceProxy::pointer > signal_interface_removed ()
sigc::signal< void, InterfaceProxy::pointer, InterfaceProxy::pointer > signal_default_interface_changed ()
Static Public Member Functions
static pointer create (const std::string &path)
Creates an ObjectProxy with a specific path.
static pointer create (const std::string &destination, const std::string &path)
Creates an ObjectProxy with a specific path.
static pointer create (DBusCxxPointer< Connection > conn, const std::string &path)
static pointer create (DBusCxxPointer< Connection > conn, const std::string &destination, const std::string &path)
Protected Types
typedef std::map< InterfaceProxy::pointer, sigc::connection > InterfaceSignalNameConnections
Protected Member Functions
ObjectProxy (DBusCxxPointer< Connection > conn, const std::string &destination, const std::string &path)
This class has a protected constructor.
void on_interface_name_changed (const std::string &oldname, const std::string &newname, InterfaceProxy::pointer interface)
Protected Attributes
DBusCxxPointer< Connection > m_connection
std::string m_destination
Path m_path
pthread_rwlock_t m_interfaces_rwlock
pthread_mutex_t m_name_mutex
Interfaces m_interfaces
InterfaceProxy::pointer m_default_interface
sigc::signal< void, InterfaceProxy::pointer, InterfaceProxy::pointer > m_signal_default_interface_changed
sigc::signal< void, InterfaceProxy::pointer > m_signal_interface_added
sigc::signal< void, InterfaceProxy::pointer > m_signal_interface_removed
InterfaceSignalNameConnections m_interface_signal_name_connections
Detailed Description
Object proxies are local proxies that provide local methods and signals for remote objects with dbus interfaces.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Examples:
caller_object.cpp, and signal_receiver_object.cpp.
Member Typedef Documentation
Interfaces
typedef std::multimap<std::string, InterfaceProxy::pointer> DBus::ObjectProxy::Interfaces
InterfaceSignalNameConnections
typedef std::map<InterfaceProxy::pointer,sigc::connection> DBus::ObjectProxy::InterfaceSignalNameConnections protected
pointer
typedef DBusCxxPointer<ObjectProxy> DBus::ObjectProxy::pointer
Typedef to smart pointers to ObjectProxy.
Can access type as ObjectProxy::pointer
Examples:
caller_object.cpp, and signal_receiver_object.cpp.
Constructor & Destructor Documentation
ObjectProxy()
DBus::ObjectProxy::ObjectProxy (DBusCxxPointer< Connection > conn, const std::string & destination, const std::string & path) protected
This class has a protected constructor.
Use the create() methods to obtain a smart pointer to a new instance.
References m_interfaces_rwlock, and m_name_mutex.
Referenced by create().
~ObjectProxy()
DBus::ObjectProxy::~ObjectProxy () virtual
References m_interfaces_rwlock, and m_name_mutex.
Member Function Documentation
add_interface()
bool DBus::ObjectProxy::add_interface (InterfaceProxy::pointer interface)
Adds the interface to this object.
References interface(), m_default_interface, m_interface_signal_name_connections, m_interfaces, m_interfaces_rwlock, m_signal_interface_added, on_interface_name_changed(), and set_default_interface().
Referenced by create_interface(), and set_default_interface().
add_method() [1/2]
bool DBus::ObjectProxy::add_method (const std::string & interface, MethodProxyBase::pointer method)
Adds the method to the named interface.
References create_interface(), and interface().
add_method() [2/2]
bool DBus::ObjectProxy::add_method (MethodProxyBase::pointer method)
Adds the method to the default interface.
References create_interface(), interface(), m_default_interface, and set_default_interface().
call()
ReturnMessage::const_pointer DBus::ObjectProxy::call (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_connection.
call_async()
PendingCall::pointer DBus::ObjectProxy::call_async (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_connection.
connection()
Connection::pointer DBus::ObjectProxy::connection () const
References m_connection.
Referenced by DBus::InterfaceProxy::connection().
create() [1/4]
ObjectProxy::pointer DBus::ObjectProxy::create (const std::string & path) static
Creates an ObjectProxy with a specific path.
Parameters
path The path of the object that this will be a proxy for
Examples:
caller_object.cpp, and signal_receiver_object.cpp.
References ObjectProxy().
Referenced by DBus::Connection::create_object_proxy().
create() [2/4]
ObjectProxy::pointer DBus::ObjectProxy::create (const std::string & destination, const std::string & path) static
Creates an ObjectProxy with a specific path.
Parameters
destination The destination address that this will be a proxy for
path The path of the object that this will be a proxy for
References ObjectProxy().
create() [3/4]
ObjectProxy::pointer DBus::ObjectProxy::create (DBusCxxPointer< Connection > conn, const std::string & path) static
References ObjectProxy().
create() [4/4]
ObjectProxy::pointer DBus::ObjectProxy::create (DBusCxxPointer< Connection > conn, const std::string & destination, const std::string & path) static
References ObjectProxy().
create_call_message() [1/2]
CallMessage::pointer DBus::ObjectProxy::create_call_message (const std::string & interface_name, const std::string & method_name) const
References DBus::CallMessage::create(), m_destination, and m_path.
create_call_message() [2/2]
CallMessage::pointer DBus::ObjectProxy::create_call_message (const std::string & method_name) const
References DBus::CallMessage::create(), m_destination, and m_path.
create_interface()
InterfaceProxy::pointer DBus::ObjectProxy::create_interface (const std::string & name)
Creates and adds the named interface to this object.
Returns
the newly created interface
References add_interface(), DBus::InterfaceProxy::create(), and interface().
Referenced by add_method().
create_method() [1/8]
template<class T_return > DBusCxxPointer<MethodProxy<T_return> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [2/8]
template<class T_return , class T_arg1 > DBusCxxPointer<MethodProxy<T_return, T_arg1> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [3/8]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [4/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [5/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [6/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [7/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_method() [8/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::ObjectProxy::create_method (const std::string & interface_name, const std::string & method_name) inline
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created method proxy
Parameters
interface_name The name of the interface to add this proxy method to
method_name The name to assign to the newly create method proxy. This name will be used to perform the dbus-call.
create_signal() [1/8]
template<class T_return > DBusCxxPointer<signal_proxy<T_return> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [2/8]
template<class T_return , class T_arg1 > DBusCxxPointer<signal_proxy<T_return, T_arg1> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [3/8]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [4/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [5/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [6/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [7/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
create_signal() [8/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::ObjectProxy::create_signal (const std::string & interface_name, const std::string & sig_name) inline
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
Returns
A smart pointer to the newly created signal proxy
Parameters
interface_name The name of the interface to add this proxy signal to
sig_name The name to assign to the newly created signal proxy.
References signal_default_interface_changed(), signal_interface_added(), and signal_interface_removed().
default_interface()
InterfaceProxy::pointer DBus::ObjectProxy::default_interface () const
References m_default_interface.
destination()
const std::string & DBus::ObjectProxy::destination () const
References m_destination.
Referenced by set_destination().
has_interface() [1/2]
bool DBus::ObjectProxy::has_interface (const std::string & name) const
References m_interfaces, and m_interfaces_rwlock.
Referenced by set_default_interface().
has_interface() [2/2]
bool DBus::ObjectProxy::has_interface (InterfaceProxy::pointer interface) const
References m_interfaces, and m_interfaces_rwlock.
interface()
InterfaceProxy::pointer DBus::ObjectProxy::interface (const std::string & name) const
Returns the first interface with the given name.
References m_interfaces, and m_interfaces_rwlock.
Referenced by add_interface(), add_method(), create_interface(), on_interface_name_changed(), operator[](), remove_interface(), and set_default_interface().
interfaces()
const ObjectProxy::Interfaces & DBus::ObjectProxy::interfaces () const
References m_interfaces.
on_interface_name_changed()
void DBus::ObjectProxy::on_interface_name_changed (const std::string & oldname, const std::string & newname, InterfaceProxy::pointer interface) protected
References interface(), m_interface_signal_name_connections, m_interfaces, and m_interfaces_rwlock.
Referenced by add_interface().
operator[]()
InterfaceProxy::pointer DBus::ObjectProxy::operator[] (const std::string & name) const
Alias for interface(name)
References interface().
path()
const Path & DBus::ObjectProxy::path () const
References m_path.
Referenced by DBus::InterfaceProxy::path(), and set_path().
remove_default_interface()
void DBus::ObjectProxy::remove_default_interface ()
References m_default_interface, and m_signal_default_interface_changed.
remove_interface() [1/2]
void DBus::ObjectProxy::remove_interface (const std::string & name)
Removes the first interface with the given name.
References interface(), m_default_interface, m_interface_signal_name_connections, m_interfaces, m_interfaces_rwlock, m_signal_default_interface_changed, and m_signal_interface_removed.
remove_interface() [2/2]
void DBus::ObjectProxy::remove_interface (InterfaceProxy::pointer interface)
Removes the given interface.
References m_default_interface, m_interface_signal_name_connections, m_interfaces, m_interfaces_rwlock, m_signal_default_interface_changed, and m_signal_interface_removed.
set_connection()
void DBus::ObjectProxy::set_connection (DBusCxxPointer< Connection > conn)
References m_connection, and m_interfaces.
set_default_interface() [1/2]
bool DBus::ObjectProxy::set_default_interface (const std::string & new_default_name)
References m_default_interface, m_interfaces, m_interfaces_rwlock, and m_signal_default_interface_changed.
Referenced by add_interface(), and add_method().
set_default_interface() [2/2]
bool DBus::ObjectProxy::set_default_interface (InterfaceProxy::pointer new_default)
References add_interface(), has_interface(), interface(), m_default_interface, and m_signal_default_interface_changed.
set_destination()
void DBus::ObjectProxy::set_destination (const std::string & destination)
References destination(), and m_destination.
set_path()
void DBus::ObjectProxy::set_path (const std::string & path)
References m_interfaces, m_path, and path().
signal_default_interface_changed()
sigc::signal< void, InterfaceProxy::pointer, InterfaceProxy::pointer > DBus::ObjectProxy::signal_default_interface_changed ()
References m_signal_default_interface_changed.
Referenced by create_signal().
signal_interface_added()
sigc::signal< void, InterfaceProxy::pointer > DBus::ObjectProxy::signal_interface_added ()
References m_signal_interface_added.
Referenced by create_signal().
signal_interface_removed()
sigc::signal< void, InterfaceProxy::pointer > DBus::ObjectProxy::signal_interface_removed ()
References m_signal_interface_removed.
Referenced by create_signal().
Member Data Documentation
m_connection
DBusCxxPointer<Connection> DBus::ObjectProxy::m_connection protected
Referenced by call(), call_async(), connection(), and set_connection().
m_default_interface
InterfaceProxy::pointer DBus::ObjectProxy::m_default_interface protected
Referenced by add_interface(), add_method(), default_interface(), remove_default_interface(), remove_interface(), and set_default_interface().
m_destination
std::string DBus::ObjectProxy::m_destination protected
Referenced by create_call_message(), destination(), and set_destination().
m_interface_signal_name_connections
InterfaceSignalNameConnections DBus::ObjectProxy::m_interface_signal_name_connections protected
Referenced by add_interface(), on_interface_name_changed(), and remove_interface().
m_interfaces
Interfaces DBus::ObjectProxy::m_interfaces protected
Referenced by add_interface(), has_interface(), interface(), interfaces(), on_interface_name_changed(), remove_interface(), set_connection(), set_default_interface(), and set_path().
m_interfaces_rwlock
pthread_rwlock_t DBus::ObjectProxy::m_interfaces_rwlock mutable protected
Referenced by add_interface(), has_interface(), interface(), ObjectProxy(), on_interface_name_changed(), remove_interface(), set_default_interface(), and ~ObjectProxy().
m_name_mutex
pthread_mutex_t DBus::ObjectProxy::m_name_mutex protected
Referenced by ObjectProxy(), and ~ObjectProxy().
m_path
Path DBus::ObjectProxy::m_path protected
Referenced by create_call_message(), path(), and set_path().
m_signal_default_interface_changed
sigc::signal<void,InterfaceProxy::pointer,InterfaceProxy::pointer> DBus::ObjectProxy::m_signal_default_interface_changed protected
Referenced by remove_default_interface(), remove_interface(), set_default_interface(), and signal_default_interface_changed().
m_signal_interface_added
sigc::signal<void,InterfaceProxy::pointer> DBus::ObjectProxy::m_signal_interface_added protected
Referenced by add_interface(), and signal_interface_added().
m_signal_interface_removed
sigc::signal<void,InterfaceProxy::pointer> DBus::ObjectProxy::m_signal_interface_removed protected
Referenced by remove_interface(), and signal_interface_removed().
The documentation for this class was generated from the following files:
objectproxy.h
objectproxy.cpp