dbus-cxx: DBus::Error Class Reference
DBus::Error Class Reference
Errors
Base class of a hierarchy of error objects thrown when exceptional conditions occur.
#include <error.h>
Inherits std::exception.
Inherited by DBus::ErrorAccessDenied, DBus::ErrorAddressInUse, DBus::ErrorAuthFailed, DBus::ErrorBadAddress, DBus::ErrorBadVariantCast, DBus::ErrorDeadlock, DBus::ErrorDisconnected, DBus::ErrorDispatcherInitFailed, DBus::ErrorFailed, DBus::ErrorFileExists, DBus::ErrorFileNotFound, DBus::ErrorIOError, DBus::ErrorIncorrectDispatchThread, DBus::ErrorInteractiveAuthorizationRequired, DBus::ErrorInvalidAdaptee, DBus::ErrorInvalidArgs, DBus::ErrorInvalidCObject, DBus::ErrorInvalidConnection, DBus::ErrorInvalidFileContent, DBus::ErrorInvalidMessage, DBus::ErrorInvalidMessageType, DBus::ErrorInvalidReturn, DBus::ErrorInvalidSharedPtr, DBus::ErrorInvalidSignature, DBus::ErrorInvalidTypecast, DBus::ErrorLimitsExceeded, DBus::ErrorMatchRuleInvalid, DBus::ErrorMatchRuleNotFound, DBus::ErrorMessageNestedTooDeep, DBus::ErrorNameHasNoOwner, DBus::ErrorNoConnection, DBus::ErrorNoMemory, DBus::ErrorNoNetwork, DBus::ErrorNoReply, DBus::ErrorNoServer, DBus::ErrorNotInitialized, DBus::ErrorNotOwner, DBus::ErrorNotSupported, DBus::ErrorPollFailed, DBus::ErrorPropertyReadOnly, DBus::ErrorRemoteException, DBus::ErrorSELinuxSecurityContextUnknown, DBus::ErrorServiceUnknown, DBus::ErrorSpawnChildExited, DBus::ErrorSpawnChildSignaled, DBus::ErrorSpawnExecFailed, DBus::ErrorSpawnFailed, DBus::ErrorSpawnForkFailed, DBus::ErrorTimedOut, DBus::ErrorTimeout, DBus::ErrorUnableToParse, DBus::ErrorUnexpectedResponse, DBus::ErrorUnixProcessIdUnknown, DBus::ErrorUnknown, DBus::ErrorUnknownInterface, DBus::ErrorUnknownMethod, DBus::ErrorUnknownObject, and DBus::ErrorUnknownProperty.
Public Member Functions
Error ()
Error (const char *name, const char *message=nullptr)
Error (const char *name, std::string message)
Error (std::string name, std::string message)
~Error () noexcept
const char * what () const noexcept
std::string name () const
std::string message () const
Protected Attributes
std::string m_name
std::string m_message
Detailed Description
Base class of a hierarchy of error objects thrown when exceptional conditions occur.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
Error() [1/4]
DBus::Error::Error ()
Error() [2/4]
DBus::Error::Error (const char * name, const char * message = nullptr)
References m_message, m_name, message(), and name().
Error() [3/4]
DBus::Error::Error (const char * name, std::string message)
References m_message, m_name, message(), and name().
Error() [4/4]
DBus::Error::Error (std::string name, std::string message)
References m_message, m_name, message(), and name().
~Error()
DBus::Error::~Error () noexcept
Member Function Documentation
message()
std::string DBus::Error::message () const
References m_message.
Referenced by Error().
name()
std::string DBus::Error::name () const
References m_name.
Referenced by Error().
what()
const char * DBus::Error::what () const noexcept
References m_message.
Referenced by DBus::Method< T_type >::handle_call_message().
Member Data Documentation
m_message
std::string DBus::Error::m_message protected
Referenced by Error(), message(), and what().
m_name
std::string DBus::Error::m_name protected
Referenced by Error(), and name().
The documentation for this class was generated from the following files:
error.h
error.cpp