DBus::SignalMessage Class Reference
DBus::SignalMessage Class Reference
DBus Messages
Represents a DBus signal message.
#include <signalmessage.h>
Public Types
typedef DBusCxxPointer< SignalMessage > pointer
typedef DBusCxxPointer< const SignalMessage > const_pointer
typedef DBusCxxWeakPointer< SignalMessage > weak_pointer
Public Types inherited from DBus::Message
typedef DBusCxxPointer< Message > pointer
typedef DBusCxxPointer< const Message > const_pointer
typedef DBusCxxWeakPointer< Message > weak_pointer
typedef MessageIterator iterator
typedef MessageAppendIterator append_iterator
Public Member Functions
bool set_path (const std::string &p)
Path path () const
bool has_path (const std::string &p) const
std::vector< std::string > path_decomposed () const
bool set_interface (const std::string &i)
const char * interface () const
bool has_interface (const std::string &i) const
bool set_member (const std::string &m)
const char * member () const
bool has_member (const std::string &m) const
bool operator== (const SignalMessage &) const
Public Member Functions inherited from DBus::Message
DBusCxxPointer< ReturnMessage > create_reply () const
virtual ~Message ()
Message & operator= (const Message &m)
bool operator== (const Message &other)
bool is_valid () const
void invalidate ()
operator bool () const
uint32_t serial () const
int type () const
void set_auto_start (bool auto_start)
bool auto_start ()
bool set_destination (const std::string &s)
const char * destination () const
bool set_sender (const std::string &s)
const char * sender () const
bool is_call (const std::string &interface, const std::string &method) const
bool is_signal (const std::string &interface, const std::string &signal_name) const
bool is_error (const std::string &error_name) const
bool has_destination (const std::string &name) const
bool has_sender (const std::string &name) const
template<typename T >
iterator operator>> (T &value) const
template<typename T >
append_iterator operator<< (const T &value)
iterator begin () const
iterator end () const
append_iterator append ()
DBusMessage * cobj () const
Static Public Member Functions
static pointer create (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::pointer msg)
static const_pointer create (Message::const_pointer msg)
static pointer create (const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
Static Public Member Functions inherited from DBus::Message
static pointer create (MessageType type)
static pointer create (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::pointer other, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Protected Member Functions
SignalMessage (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
SignalMessage (Message::pointer msg)
SignalMessage (Message::const_pointer msg)
SignalMessage (const std::string &name)
SignalMessage (const std::string &path, const std::string &interface, const std::string &name)
Protected Member Functions inherited from DBus::Message
Message (MessageType type)
Message (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
Message (Message::pointer other, CreateMethod m=CREATE_ALIAS)
Message (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Additional Inherited Members
Protected Attributes inherited from DBus::Message
DBusMessage * m_cobj
bool m_valid
Detailed Description
Represents a DBus signal message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for a signal message that is received from a signal or transmitted on signal emission.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
const_pointer
typedef DBusCxxPointer<const SignalMessage> DBus::SignalMessage::const_pointer
pointer
typedef DBusCxxPointer<SignalMessage> DBus::SignalMessage::pointer
weak_pointer
typedef DBusCxxWeakPointer<SignalMessage> DBus::SignalMessage::weak_pointer
Constructor & Destructor Documentation
SignalMessage() [1/5]
DBus::SignalMessage::SignalMessage (DBusMessage * cobj = NULL, CreateMethod m = CREATE_ALIAS) protected
Referenced by create().
SignalMessage() [2/5]
DBus::SignalMessage::SignalMessage (Message::pointer msg) protected
References DBus::SIGNAL_MESSAGE.
SignalMessage() [3/5]
DBus::SignalMessage::SignalMessage (Message::const_pointer msg) protected
References DBus::SIGNAL_MESSAGE.
SignalMessage() [4/5]
DBus::SignalMessage::SignalMessage (const std::string & name) protected
References set_member().
SignalMessage() [5/5]
DBus::SignalMessage::SignalMessage (const std::string & path, const std::string & interface, const std::string & name) protected
References DBus::Message::m_cobj.
Member Function Documentation
create() [1/5]
SignalMessage::pointer DBus::SignalMessage::create (DBusMessage * cobj = NULL, CreateMethod m = CREATE_ALIAS) static
Examples:
signal_emitter_raw.cpp.
References SignalMessage().
Referenced by DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::internal_callback(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::internal_callback(), DBus::signal_proxy_base::matches(), DBus::SignalReceiver::matches(), and DBus::Connection::on_filter_callback().
create() [2/5]
SignalMessage::pointer DBus::SignalMessage::create (Message::pointer msg) static
References SignalMessage().
create() [3/5]
SignalMessage::const_pointer DBus::SignalMessage::create (Message::const_pointer msg) static
References SignalMessage().
create() [4/5]
SignalMessage::pointer DBus::SignalMessage::create (const std::string & name) static
References SignalMessage().
create() [5/5]
SignalMessage::pointer DBus::SignalMessage::create (const std::string & path, const std::string & interface, const std::string & name) static
References SignalMessage().
has_interface()
bool DBus::SignalMessage::has_interface (const std::string & i) const
References DBus::Message::m_cobj.
has_member()
bool DBus::SignalMessage::has_member (const std::string & m) const
References DBus::Message::m_cobj.
has_path()
bool DBus::SignalMessage::has_path (const std::string & p) const
References DBus::Message::m_cobj.
interface()
const char * DBus::SignalMessage::interface () const
References DBus::Message::m_cobj.
Referenced by operator==().
member()
const char * DBus::SignalMessage::member () const
References DBus::Message::m_cobj.
Referenced by operator==().
operator==()
bool DBus::SignalMessage::operator== (const SignalMessage & m) const
References interface(), DBus::Message::m_cobj, and member().
path()
Path DBus::SignalMessage::path () const
References DBus::Message::m_cobj.
path_decomposed()
std::vector< std::string > DBus::SignalMessage::path_decomposed () const
References DBus::Message::m_cobj.
set_interface()
bool DBus::SignalMessage::set_interface (const std::string & i)
References DBus::Message::m_cobj.
set_member()
bool DBus::SignalMessage::set_member (const std::string & m)
References DBus::Message::m_cobj.
Referenced by SignalMessage().
set_path()
bool DBus::SignalMessage::set_path (const std::string & p)
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
signalmessage.h
signalmessage.cpp