dbus-cxx: DBus::SignalProxyBase Class Reference
DBus::SignalProxyBase Class Reference abstract
Proxy | Signals
Base class for a signal proxy that allows you to listen for signals.
#include <signalproxy.h>
Public Member Functions
virtual HandlerResult handle_signal (std::shared_ptr< const SignalMessage >)
const std::string & match_rule () const
Public Member Functions inherited from DBus::SignalBase
virtual ~SignalBase ()
std::shared_ptr< Connection > connection ()
void set_connection (std::weak_ptr< Connection > connection)
const std::string & sender () const
void set_sender (const std::string &s)
const std::string & interface_name () const
void set_interface (const std::string &i)
const std::string & name () const
void set_name (const std::string &n)
const Path & path () const
void set_path (const std::string &s)
const std::string & destination () const
void set_destination (const std::string &s)
virtual std::string introspect (int space_depth=0) const
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Protected Member Functions
SignalProxyBase (const SignalMatchRule &matchRule)
virtual ~SignalProxyBase ()
bool matches (std::shared_ptr< const SignalMessage > msg)
virtual HandlerResult on_dbus_incoming (std::shared_ptr< const SignalMessage > msg)=0
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Protected Member Functions inherited from DBus::SignalBase
SignalBase (const std::string &path, const std::string &interface_name, const std::string &name)
SignalBase (const std::string &interface_name, const std::string &name)
SignalBase (std::weak_ptr< Connection > connection, const std::string &path, const std::string &interface_name, const std::string &name)
SignalBase (std::weak_ptr< Connection > connection, const std::string &interface_name, const std::string &name)
bool handle_dbus_outgoing (std::shared_ptr< const Message >)
Private Member Functions
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Detailed Description
Base class for a signal proxy that allows you to listen for signals.
This is required to use signals in a generic manner, as the subclasses are all templated.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
SignalProxyBase()
DBus::SignalProxyBase::SignalProxyBase (const SignalMatchRule & matchRule) protected
References DBus::MatchRule::match_rule().
~SignalProxyBase()
DBus::SignalProxyBase::~SignalProxyBase () protected virtual
Member Function Documentation
DBUS_CXX_PROPAGATE_CONST()
DBus::SignalProxyBase::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
handle_signal()
HandlerResult DBus::SignalProxyBase::handle_signal (std::shared_ptr< const SignalMessage > msg) virtual
References matches(), DBus::Not_Handled, and on_dbus_incoming().
match_rule()
const std::string & DBus::SignalProxyBase::match_rule () const
matches()
bool DBus::SignalProxyBase::matches (std::shared_ptr< const SignalMessage > msg) protected
References DBus::SignalBase::destination(), DBus::SignalBase::interface_name(), DBus::SignalBase::name(), DBus::SignalBase::path(), and DBus::SignalBase::sender().
Referenced by handle_signal().
on_dbus_incoming()
virtual HandlerResult DBus::SignalProxyBase::on_dbus_incoming (std::shared_ptr< const SignalMessage > msg) protected pure virtual
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Implemented in DBus::SignalProxy< void(T_arg...)>.
Referenced by handle_signal().
The documentation for this class was generated from the following files:
signalproxy.h
signalproxy.cpp