DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
Signals | Local Objects
Subclass of the numbered sigc::signal templates.
#include <dbus_signal.h>
Public Types
typedef DBusCxxPointer< signal > pointer
Public Types inherited from DBus::signal_base
typedef DBusCxxPointer< signal_base > pointer
Public Member Functions
signal (const std::string &interface, const std::string &name)
signal (const std::string &path, const std::string &interface, const std::string &name)
signal (const std::string &interface, const std::string &name, const signal &src)
signal (const std::string &path, const std::string &interface, const std::string &name, const signal &src)
virtual signal_base::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Public Member Functions inherited from DBus::signal_base
virtual ~signal_base ()
DBusCxxPointer< Connection > connection ()
void set_connection (DBusCxxPointer< Connection > connection)
const std::string & sender () const
void set_sender (const std::string &s)
const std::string & interface () const
void set_interface (const std::string &i)
const std::string & name () const
void set_name (const std::string &n)
const Path & path () const
void set_path (const std::string &s)
const std::string & destination () const
void set_destination (const std::string &s)
Static Public Member Functions
static pointer create (const std::string &interface, const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
static pointer create (const std::string &interface, const std::string &name, const signal &src)
static pointer create (const std::string &path, const std::string &interface, const std::string &name, const signal &src)
Protected Member Functions
T_return internal_callback (T_arg1 arg1, T_arg2 arg2, T_arg3 arg3, T_arg4 arg4, T_arg5 arg5, T_arg6 arg6, T_arg7 arg7)
Protected Member Functions inherited from DBus::signal_base
signal_base (const std::string &path, const std::string &interface, const std::string &name)
signal_base (const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_base (const signal_base &other)
bool handle_dbus_outgoing (Message::const_pointer)
Protected Attributes
std::string m_arg_names [7]
sigc::connection m_internal_callback_connection
Protected Attributes inherited from DBus::signal_base
DBusCxxWeakPointer< Connection > m_connection
std::string m_sender
Path m_path
std::string m_interface
std::string m_name
std::string m_destination
std::string m_match_rule
Friends
class Interface
Detailed Description
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil>
class DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >
Subclass of the numbered sigc::signal templates.
This class defines a subclass of the sigc::signal types and can be used as its parent. The key difference is that when the signal is emitted a DBus signal message is created using the parameters of the signal emission and transmitted via the dbus in addition to any local signal propagation that may take place.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Examples:
signal_emitter_object.cpp.
Member Typedef Documentation
pointer
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> typedef DBusCxxPointer<signal> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::pointer
Constructor & Destructor Documentation
signal() [1/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_internal_callback_connection.
Referenced by DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::create(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create().
signal() [2/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_internal_callback_connection.
signal() [3/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal (const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > & src) inline
signal() [4/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal (const std::string & path, const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > & src) inline
Member Function Documentation
arg_name()
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> virtual std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name (size_t i) inline virtual
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
clone()
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> virtual signal_base::pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone () inline virtual
Implements DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
create() [1/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & interface, const std::string & name) inline static
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
Referenced by DBus::Interface::create_signal(), and DBus::Connection::create_signal().
create() [2/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & path, const std::string & interface, const std::string & name) inline static
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
create() [3/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > & src) inline static
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
create() [4/4]
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> static pointer DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & path, const std::string & interface, const std::string & name, const signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > & src) inline static
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal().
internal_callback()
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> T_return DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::internal_callback (T_arg1 arg1, T_arg2 arg2, T_arg3 arg3, T_arg4 arg4, T_arg5 arg5, T_arg6 arg6, T_arg7 arg7) inline protected
References DBus::SignalMessage::create(), DBUSCXX_DEBUG_STDSTR, DBus::signal_base::handle_dbus_outgoing(), DBus::signal_base::m_destination, DBus::signal_base::m_interface, DBus::signal_base::m_name, and DBus::signal_base::m_path.
Referenced by DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::signal(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal().
introspect()
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> virtual std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect (int space_depth = 0) const inline virtual
Returns a DBus XML description of this interface.
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, DBus::signal_base::name(), and DBus::signature().
set_arg_name()
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> virtual void DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name (size_t i, const std::string & name) inline virtual
Reimplemented from DBus::signal_base.
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::signal_base::name().
Friends And Related Function Documentation
Interface
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> friend class Interface friend
Member Data Documentation
m_arg_names
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> std::string DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names[7] protected
Referenced by DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name().
m_internal_callback_connection
template<class T_return, class T_arg1 = nil, class T_arg2 = nil, class T_arg3 = nil, class T_arg4 = nil, class T_arg5 = nil, class T_arg6 = nil, class T_arg7 = nil> sigc::connection DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_internal_callback_connection protected
Referenced by DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal(), DBus::signal< T_return, nil, nil, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::signal(), and DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal().
The documentation for this class was generated from the following file:
dbus_signal.h