dbus-cxx: DBus::InterfaceProxy Class Reference
DBus::InterfaceProxy Class Reference
Objects | Proxy
#include <interfaceproxy.h>
Public Types
typedef DBusCxxPointer< InterfaceProxy > pointer
typedef DBusCxxWeakPointer< InterfaceProxy > weak_pointer
typedef std::multimap< std::string, MethodProxyBase::pointer > Methods
typedef std::set< signal_proxy_base::pointer > Signals
Public Member Functions
virtual ~InterfaceProxy ()
ObjectProxy * object () const
Path path () const
DBusCxxPointer< Connection > connection () const
const std::string & name () const
void set_name (const std::string &new_name)
const Methods & methods () const
MethodProxyBase::pointer method (const std::string &name) const
Returns the first method with the given name.
template<class T_return >
DBusCxxPointer< MethodProxy< T_return > > create_method (const std::string &name)
template<class T_return , class T_arg1 >
DBusCxxPointer< MethodProxy< T_return, T_arg1 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_method (const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_method (const std::string &name)
bool add_method (MethodProxyBase::pointer method)
Adds the named method.
void remove_method (const std::string &name)
Removes the first method with the given name.
void remove_method (MethodProxyBase::pointer method)
Removed the specific method.
bool has_method (const std::string &name) const
True if the interface has a method with the given name.
bool has_method (MethodProxyBase::pointer method) const
True if the interface has the specified method.
CallMessage::pointer create_call_message (const std::string &method_name) const
ReturnMessage::const_pointer call (CallMessage::const_pointer, int timeout_milliseconds=-1) const
PendingCall::pointer call_async (CallMessage::const_pointer, int timeout_milliseconds=-1) const
template<class T_return >
DBusCxxPointer< signal_proxy< T_return > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 >
DBusCxxPointer< signal_proxy< T_return, T_arg1 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal (const std::string &sig_name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal (const std::string &sig_name)
const Signals & signals () const
signal_proxy_base::pointer signal (const std::string &signame)
bool add_signal (signal_proxy_base::pointer sig)
bool remove_signal (const std::string &signame)
bool remove_signal (signal_proxy_base::pointer sig)
bool has_signal (const std::string &signame) const
bool has_signal (signal_proxy_base::pointer sig) const
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Signal emitted when the name is changed.
sigc::signal< void, MethodProxyBase::pointer > signal_method_added ()
Signal emitted when a method of the given name is added.
sigc::signal< void, MethodProxyBase::pointer > signal_method_removed ()
Signal emitted when a method of the given name is removed.
Static Public Member Functions
static pointer create (const std::string &name=std::string())
Protected Types
typedef std::map< MethodProxyBase::pointer, sigc::connection > MethodSignalNameConnections
Protected Member Functions
InterfaceProxy (const std::string &name)
void on_method_name_changed (const std::string &oldname, const std::string &newname, MethodProxyBase::pointer method)
void on_object_set_connection (DBusCxxPointer< Connection > conn)
void on_object_set_path (const std::string &path)
Protected Attributes
ObjectProxy * m_object
std::string m_name
Methods m_methods
Signals m_signals
pthread_rwlock_t m_methods_rwlock
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
sigc::signal< void, MethodProxyBase::pointer > m_signal_method_added
sigc::signal< void, MethodProxyBase::pointer > m_signal_method_removed
MethodSignalNameConnections m_method_signal_name_connections
Friends
class ObjectProxy
Detailed Description
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
Methods
typedef std::multimap<std::string, MethodProxyBase::pointer> DBus::InterfaceProxy::Methods
MethodSignalNameConnections
typedef std::map<MethodProxyBase::pointer,sigc::connection> DBus::InterfaceProxy::MethodSignalNameConnections protected
pointer
typedef DBusCxxPointer<InterfaceProxy> DBus::InterfaceProxy::pointer
Signals
typedef std::set<signal_proxy_base::pointer> DBus::InterfaceProxy::Signals
weak_pointer
typedef DBusCxxWeakPointer<InterfaceProxy> DBus::InterfaceProxy::weak_pointer
Constructor & Destructor Documentation
InterfaceProxy()
DBus::InterfaceProxy::InterfaceProxy (const std::string & name) protected
References m_methods_rwlock, and m_name_mutex.
Referenced by create().
~InterfaceProxy()
DBus::InterfaceProxy::~InterfaceProxy () virtual
References m_methods_rwlock, and m_name_mutex.
Member Function Documentation
add_method()
bool DBus::InterfaceProxy::add_method (MethodProxyBase::pointer method)
Adds the named method.
References has_method(), m_method_signal_name_connections, m_methods, m_methods_rwlock, m_signal_method_added, method(), and on_method_name_changed().
Referenced by create_method().
add_signal()
bool DBus::InterfaceProxy::add_signal (signal_proxy_base::pointer sig)
References connection(), m_signals, name(), and path().
Referenced by create_signal().
call()
ReturnMessage::const_pointer DBus::InterfaceProxy::call (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_object.
Referenced by create_method().
call_async()
PendingCall::pointer DBus::InterfaceProxy::call_async (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_object.
Referenced by create_method().
connection()
Connection::pointer DBus::InterfaceProxy::connection () const
References DBus::ObjectProxy::connection(), and m_object.
Referenced by add_signal(), and remove_signal().
create()
InterfaceProxy::pointer DBus::InterfaceProxy::create (const std::string & name = std::string()) static
References InterfaceProxy().
Referenced by DBus::ObjectProxy::create_interface().
create_call_message()
CallMessage::pointer DBus::InterfaceProxy::create_call_message (const std::string & method_name) const
References m_name, and m_object.
Referenced by create_method().
create_method() [1/8]
template<class T_return > DBusCxxPointer<MethodProxy<T_return> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [2/8]
template<class T_return , class T_arg1 > DBusCxxPointer<MethodProxy<T_return, T_arg1> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [3/8]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [4/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [5/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [6/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [7/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [8/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<MethodProxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::InterfaceProxy::create_method (const std::string & name) inline
References add_method(), call(), call_async(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), create_call_message(), has_method(), method(), and remove_method().
create_signal() [1/8]
template<class T_return > DBusCxxPointer<signal_proxy<T_return> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [2/8]
template<class T_return , class T_arg1 > DBusCxxPointer<signal_proxy<T_return, T_arg1> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [3/8]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [4/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [5/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [6/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [7/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), m_name, and path().
create_signal() [8/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::InterfaceProxy::create_signal (const std::string & sig_name) inline
References add_signal(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), has_signal(), m_name, path(), remove_signal(), signal(), signal_method_added(), signal_method_removed(), signal_name_changed(), and signals().
has_method() [1/2]
bool DBus::InterfaceProxy::has_method (const std::string & name) const
True if the interface has a method with the given name.
References m_methods, and m_methods_rwlock.
Referenced by add_method(), and create_method().
has_method() [2/2]
bool DBus::InterfaceProxy::has_method (MethodProxyBase::pointer method) const
True if the interface has the specified method.
References m_methods, and m_methods_rwlock.
has_signal() [1/2]
bool DBus::InterfaceProxy::has_signal (const std::string & signame) const
References m_signals.
Referenced by create_signal(), and remove_signal().
has_signal() [2/2]
bool DBus::InterfaceProxy::has_signal (signal_proxy_base::pointer sig) const
References m_signals.
method()
MethodProxyBase::pointer DBus::InterfaceProxy::method (const std::string & name) const
Returns the first method with the given name.
References m_methods, and m_methods_rwlock.
Referenced by add_method(), create_method(), on_method_name_changed(), and remove_method().
methods()
const InterfaceProxy::Methods & DBus::InterfaceProxy::methods () const
References m_methods.
name()
const std::string & DBus::InterfaceProxy::name () const
References m_name.
Referenced by add_signal().
object()
ObjectProxy * DBus::InterfaceProxy::object () const
References m_object.
on_method_name_changed()
void DBus::InterfaceProxy::on_method_name_changed (const std::string & oldname, const std::string & newname, MethodProxyBase::pointer method) protected
References m_method_signal_name_connections, m_methods, m_methods_rwlock, and method().
Referenced by add_method().
on_object_set_connection()
void DBus::InterfaceProxy::on_object_set_connection (DBusCxxPointer< Connection > conn) protected
References m_signals.
on_object_set_path()
void DBus::InterfaceProxy::on_object_set_path (const std::string & path) protected
References m_signals.
path()
Path DBus::InterfaceProxy::path () const
References m_object, and DBus::ObjectProxy::path().
Referenced by add_signal(), and create_signal().
remove_method() [1/2]
void DBus::InterfaceProxy::remove_method (const std::string & name)
Removes the first method with the given name.
References m_method_signal_name_connections, m_methods, m_methods_rwlock, m_signal_method_removed, and method().
Referenced by create_method().
remove_method() [2/2]
void DBus::InterfaceProxy::remove_method (MethodProxyBase::pointer method)
Removed the specific method.
References m_method_signal_name_connections, m_methods, m_methods_rwlock, and m_signal_method_removed.
remove_signal() [1/2]
bool DBus::InterfaceProxy::remove_signal (const std::string & signame)
References signal().
Referenced by create_signal().
remove_signal() [2/2]
bool DBus::InterfaceProxy::remove_signal (signal_proxy_base::pointer sig)
References connection(), has_signal(), and m_signals.
set_name()
void DBus::InterfaceProxy::set_name (const std::string & new_name)
References m_name, m_name_mutex, and m_signal_name_changed.
signal()
signal_proxy_base::pointer DBus::InterfaceProxy::signal (const std::string & signame)
References m_signals.
Referenced by create_signal(), and remove_signal().
signal_method_added()
sigc::signal< void, MethodProxyBase::pointer > DBus::InterfaceProxy::signal_method_added ()
Signal emitted when a method of the given name is added.
References m_signal_method_added.
Referenced by create_signal().
signal_method_removed()
sigc::signal< void, MethodProxyBase::pointer > DBus::InterfaceProxy::signal_method_removed ()
Signal emitted when a method of the given name is removed.
References m_signal_method_removed.
Referenced by create_signal().
signal_name_changed()
sigc::signal< void, const std::string &, const std::string &> DBus::InterfaceProxy::signal_name_changed ()
Signal emitted when the name is changed.
References m_signal_name_changed.
Referenced by create_signal().
signals()
const InterfaceProxy::Signals & DBus::InterfaceProxy::signals () const
References m_signals.
Referenced by create_signal().
Friends And Related Function Documentation
ObjectProxy
friend class ObjectProxy friend
Member Data Documentation
m_method_signal_name_connections
MethodSignalNameConnections DBus::InterfaceProxy::m_method_signal_name_connections protected
Referenced by add_method(), on_method_name_changed(), and remove_method().
m_methods
Methods DBus::InterfaceProxy::m_methods protected
Referenced by add_method(), has_method(), method(), methods(), on_method_name_changed(), and remove_method().
m_methods_rwlock
pthread_rwlock_t DBus::InterfaceProxy::m_methods_rwlock mutable protected
Referenced by add_method(), has_method(), InterfaceProxy(), method(), on_method_name_changed(), remove_method(), and ~InterfaceProxy().
m_name
std::string DBus::InterfaceProxy::m_name protected
Referenced by create_call_message(), create_signal(), name(), and set_name().
m_name_mutex
pthread_mutex_t DBus::InterfaceProxy::m_name_mutex protected
Ensures that the name doesn't change while the name changed signal is emitting.
Referenced by InterfaceProxy(), set_name(), and ~InterfaceProxy().
m_object
ObjectProxy* DBus::InterfaceProxy::m_object protected
Referenced by call(), call_async(), connection(), create_call_message(), object(), and path().
m_signal_method_added
sigc::signal<void,MethodProxyBase::pointer> DBus::InterfaceProxy::m_signal_method_added protected
Referenced by add_method(), and signal_method_added().
m_signal_method_removed
sigc::signal<void,MethodProxyBase::pointer> DBus::InterfaceProxy::m_signal_method_removed protected
Referenced by remove_method(), and signal_method_removed().
m_signal_name_changed
sigc::signal<void,const std::string&,const std::string&> DBus::InterfaceProxy::m_signal_name_changed protected
Referenced by set_name(), and signal_name_changed().
m_signals
Signals DBus::InterfaceProxy::m_signals protected
Referenced by add_signal(), has_signal(), on_object_set_connection(), on_object_set_path(), remove_signal(), signal(), and signals().
The documentation for this class was generated from the following files:
interfaceproxy.h
interfaceproxy.cpp