dbus-cxx: DBus::FileDescriptor Class Reference
DBus::FileDescriptor Class Reference
A FileDescriptor holds a UNIX file descriptor that can be passed between processes.
#include <filedescriptor.h>
Public Member Functions
~FileDescriptor ()
int descriptor () const
operator bool () const
Static Public Member Functions
static std::shared_ptr< FileDescriptor > create (int fd)
Protected Member Functions
FileDescriptor ()
FileDescriptor (int fd)
FileDescriptor (const FileDescriptor &other)
Private Attributes
bool m_valid
int m_fd
Detailed Description
A FileDescriptor holds a UNIX file descriptor that can be passed between processes.
Constructor & Destructor Documentation
FileDescriptor() [1/3]
DBus::FileDescriptor::FileDescriptor () inline protected
Referenced by create().
FileDescriptor() [2/3]
DBus::FileDescriptor::FileDescriptor (int fd) inline explicit protected
FileDescriptor() [3/3]
DBus::FileDescriptor::FileDescriptor (const FileDescriptor & other) inline explicit protected
~FileDescriptor()
DBus::FileDescriptor::~FileDescriptor () inline
Member Function Documentation
create()
static std::shared_ptr< FileDescriptor > DBus::FileDescriptor::create (int fd) inline static
References FileDescriptor().
Referenced by DBus::MessageIterator::get_filedescriptor().
descriptor()
int DBus::FileDescriptor::descriptor () const inline
References m_fd.
operator bool()
DBus::FileDescriptor::operator bool () const inline
References m_valid.
Member Data Documentation
m_fd
int DBus::FileDescriptor::m_fd private
Referenced by descriptor().
m_valid
bool DBus::FileDescriptor::m_valid private
Referenced by operator bool().
The documentation for this class was generated from the following file:
filedescriptor.h