dbus-cxx: DBus::MethodBase Class Reference
DBus::MethodBase Class Reference abstract
Local Objects | Objects
#include <methodbase.h>
Public Types
typedef DBusCxxPointer< MethodBase > pointer
Public Member Functions
virtual ~MethodBase ()
const std::string & name () const
void set_name (const std::string &name)
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)=0
virtual pointer clone ()=0
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Protected Member Functions
MethodBase (const std::string &name)
MethodBase (const MethodBase &other)
Protected Attributes
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
Detailed Description
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
typedef DBusCxxPointer<MethodBase> DBus::MethodBase::pointer
Constructor & Destructor Documentation
MethodBase() [1/2]
DBus::MethodBase::MethodBase (const std::string & name) protected
References m_name_mutex.
MethodBase() [2/2]
DBus::MethodBase::MethodBase (const MethodBase & other) protected
References m_name_mutex.
~MethodBase()
DBus::MethodBase::~MethodBase () virtual
References m_name_mutex.
Member Function Documentation
arg_name()
std::string DBus::MethodBase::arg_name (size_t i) virtual
Reimplemented in DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, and DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >.
clone()
virtual pointer DBus::MethodBase::clone () pure virtual
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Implemented in DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >.
handle_call_message()
virtual HandlerResult DBus::MethodBase::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) pure virtual
Implemented in DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, and DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >.
introspect()
std::string DBus::MethodBase::introspect (int space_depth = 0) const virtual
Returns a DBus XML description of this interface.
Reimplemented in DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >.
name()
const std::string & DBus::MethodBase::name () const
References m_name.
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name(), and set_name().
set_arg_name()
void DBus::MethodBase::set_arg_name (size_t i, const std::string & name) virtual
Reimplemented in DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >, and DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >.
set_name()
void DBus::MethodBase::set_name (const std::string & name)
References m_name, m_name_mutex, m_signal_name_changed, and name().
signal_name_changed()
sigc::signal< void, const std::string &, const std::string &> DBus::MethodBase::signal_name_changed ()
References m_signal_name_changed.
Member Data Documentation
m_name
std::string DBus::MethodBase::m_name protected
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::handle_call_message(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message(), name(), and set_name().
m_name_mutex
pthread_mutex_t DBus::MethodBase::m_name_mutex protected
Ensures that the name doesn't change while the name changed signal is emitting.
Referenced by MethodBase(), set_name(), and ~MethodBase().
m_signal_name_changed
sigc::signal<void,const std::string&, const std::string&> DBus::MethodBase::m_signal_name_changed protected
Referenced by set_name(), and signal_name_changed().
The documentation for this class was generated from the following files:
methodbase.h
methodbase.cpp