DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > Class Template Reference
Local Objects | Objects
#include <method.h>
Public Types
typedef DBusCxxPointer< Method > pointer
Public Types inherited from DBus::MethodBase
typedef DBusCxxPointer< MethodBase > pointer
Public Member Functions
Method (const std::string &name)
virtual ~Method ()
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
void set_method (sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot)
virtual MethodBase::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Public Member Functions inherited from DBus::MethodBase
virtual ~MethodBase ()
const std::string & name () const
void set_name (const std::string &name)
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Static Public Member Functions
static pointer create (const std::string &name)
Protected Attributes
std::string m_arg_names [7+1]
sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > m_slot
Protected Attributes inherited from DBus::MethodBase
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
Additional Inherited Members
Protected Member Functions inherited from DBus::MethodBase
MethodBase (const std::string &name)
MethodBase (const MethodBase &other)
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6, class T_arg7>
class DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > typedef DBusCxxPointer<Method> DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::pointer
Constructor & Destructor Documentation
Method()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method (const std::string & name) inline
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::create(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create(), and DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
~Method()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::~Method () inline virtual
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message().
Member Function Documentation
arg_name()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name (size_t i) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
clone()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual MethodBase::pointer DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::clone () inline virtual
Implements DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method(), and DBus::MethodBase::name().
create()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > static pointer DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create (const std::string & name) inline static
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method().
Referenced by DBus::Interface::create_method().
handle_call_message()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > HandlerResult DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) virtual
Implements DBus::MethodBase.
References DBus::ErrorMessage::create(), DBUS_CXX_PACKAGE_MAJOR_VERSION, DBUS_CXX_PACKAGE_MICRO_VERSION, DBUS_CXX_PACKAGE_MINOR_VERSION, DBUSCXX_DEBUG_STDSTR, DBus::HANDLED, DBus::MethodBase::m_name, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot, and DBus::NOT_HANDLED.
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::~Method(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::~Method(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::~Method(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::~Method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::~Method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::~Method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::~Method(), and DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::~Method().
introspect()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect (int space_depth = 0) const inline virtual
Returns a DBus XML description of this interface.
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, DBus::MethodBase::name(), DBus::signature(), and DBus::type().
set_arg_name()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > virtual void DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name (size_t i, const std::string & name) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::MethodBase::name().
set_method()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > void DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method (sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot) inline
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot.
Member Data Documentation
m_arg_names
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > std::string DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names[7+1] protected
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::introspect(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::introspect(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), and DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_arg_name().
m_slot
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > sigc::slot7<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot protected
Referenced by DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::handle_call_message(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::handle_call_message(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::handle_call_message(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::handle_call_message(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_arg_name(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_arg_name(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method(), DBus::Method< T_return, nil, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_method(), DBus::Method< void, nil, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, nil, nil, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::set_method(), DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::set_method(), and DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::set_method().
The documentation for this class was generated from the following file:
method.h