dbus-cxx: DBus::GLib::GLibDispatcher Class Reference
DBus::GLib::GLibDispatcher Class Reference
Does all dispatching in the main GLib context.
#include <glibdispatcher.h>
Public Member Functions
~GLibDispatcher ()
std::shared_ptr< Connection > create_connection (BusType type)
std::shared_ptr< Connection > create_connection (std::string address)
bool add_connection (std::shared_ptr< Connection > connection)
Public Member Functions inherited from DBus::Dispatcher
virtual ~Dispatcher ()
Static Public Member Functions
static std::shared_ptr< GLibDispatcher > create ()
Private Member Functions
GLibDispatcher ()
gboolean channel_has_data (GIOChannel *channel, GIOCondition condition)
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Static Private Member Functions
static gboolean channel_data_cb (GIOChannel *channel, GIOCondition condition, gpointer data)
Detailed Description
Does all dispatching in the main GLib context.
Constructor & Destructor Documentation
GLibDispatcher()
GLibDispatcher::GLibDispatcher () private
Referenced by create().
~GLibDispatcher()
GLibDispatcher::~GLibDispatcher ()
Member Function Documentation
add_connection()
bool GLibDispatcher::add_connection (std::shared_ptr< Connection > connection) virtual
Implements DBus::Dispatcher.
References channel_data_cb(), LOGGER_NAME, and SIMPLELOGGER_TRACE.
Referenced by create_connection().
channel_data_cb()
gboolean GLibDispatcher::channel_data_cb (GIOChannel * channel, GIOCondition condition, gpointer data) static private
References channel_has_data().
Referenced by add_connection().
channel_has_data()
gboolean GLibDispatcher::channel_has_data (GIOChannel * channel, GIOCondition condition) private
References DBus::COMPLETE, conn, LOGGER_NAME, and SIMPLELOGGER_TRACE.
Referenced by channel_data_cb().
create()
std::shared_ptr< GLibDispatcher > GLibDispatcher::create () static
References GLibDispatcher().
Referenced by main().
create_connection() [1/2]
std::shared_ptr< DBus::Connection > GLibDispatcher::create_connection (BusType type) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, DBus::Connection::create(), and DBus::type().
create_connection() [2/2]
std::shared_ptr< DBus::Connection > GLibDispatcher::create_connection (std::string address) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, and DBus::Connection::create().
DBUS_CXX_PROPAGATE_CONST()
DBus::GLib::GLibDispatcher::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
The documentation for this class was generated from the following files:
glibdispatcher.h
glibdispatcher.cpp