dbus-cxx: DBus::Dispatcher Class Reference
DBus::Dispatcher Class Reference
Handles multi-threaded dispatching of one or more connections.
#include <dispatcher.h>
Classes
class WatchPair
Public Types
typedef DBusCxxPointer< Dispatcher > pointer
typedef DBusCxxPointer< const Dispatcher > const_pointer
Public Member Functions
virtual ~Dispatcher ()
bool start ()
bool stop ()
bool is_running ()
Managing Connections
Connection::pointer create_connection (DBusConnection *cobj=NULL, bool is_private=false)
Connection::pointer create_connection (BusType type, bool is_private=false)
Connection::pointer create_connection (std::string address, bool is_private=false)
Connection::pointer create_connection (const Connection &other)
bool add_connection (Connection::pointer connection)
Static Public Member Functions
static pointer create (bool is_running=true)
Protected Types
typedef std::list< Connection::pointer > Connections
Protected Member Functions
Dispatcher (bool is_running=true)
virtual void dispatch_thread_main ()
bool on_add_watch (Watch::pointer)
bool on_remove_watch (Watch::pointer)
void on_watch_toggled (Watch::pointer)
bool on_add_timeout (Timeout::pointer)
bool on_remove_timeout (Timeout::pointer)
bool on_timeout_toggled (Timeout::pointer)
void on_wakeup_main (Connection::pointer)
void on_dispatch_status_changed (DispatchStatus, Connection::pointer)
void wakeup_thread ()
void add_read_and_write_watches (std::vector< struct pollfd > *fds)
Add all read and write watch FDs to the given vector to watch.
void handle_read_and_write_watches (std::vector< struct pollfd > *fds)
Handle all of the read and write watches if the given FD needs to be serviced.
void dispatch_connections ()
Dispatch all of our connections.
Protected Attributes
Connections m_connections
volatile bool m_running
std::thread * m_dispatch_thread
std::mutex m_mutex_watches
std::map< int, WatchPair > m_watches_map
std::mutex m_mutex_exception_fd_set
std::vector< int > m_exception_fd_set
int process_fd [2]
unsigned int m_dispatch_loop_limit
This is the maximum number of dispatches that will occur for a connection in one iteration of the dispatch thread.
Detailed Description
Handles multi-threaded dispatching of one or more connections.
This class provides a way to handle multiple connections with one set of dispatching threads.
This dispatcher creates two threads, one to watch I/O file descriptors for activity and the other to handle message dispatching.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
Connections
typedef std::list<Connection::pointer> DBus::Dispatcher::Connections protected
const_pointer
typedef DBusCxxPointer<const Dispatcher> DBus::Dispatcher::const_pointer
pointer
typedef DBusCxxPointer<Dispatcher> DBus::Dispatcher::pointer
Constructor & Destructor Documentation
Dispatcher()
DBus::Dispatcher::Dispatcher (bool is_running = true) protected
References process_fd, and start().
Referenced by create().
~Dispatcher()
DBus::Dispatcher::~Dispatcher () virtual
Reimplemented in DBus::Glib::Dispatcher.
References stop().
Member Function Documentation
add_connection()
bool DBus::Dispatcher::add_connection (Connection::pointer connection)
References m_connections, on_add_timeout(), on_add_watch(), on_dispatch_status_changed(), on_remove_timeout(), on_remove_watch(), on_timeout_toggled(), on_wakeup_main(), and on_watch_toggled().
Referenced by create_connection().
add_read_and_write_watches()
void DBus::Dispatcher::add_read_and_write_watches (std::vector< struct pollfd > * fds) protected
Add all read and write watch FDs to the given vector to watch.
References m_mutex_watches, and m_watches_map.
Referenced by dispatch_thread_main().
create()
Dispatcher::pointer DBus::Dispatcher::create (bool is_running = true) static
Examples:
calculator_client.cpp, calculator_server.cpp, calculator_watcher.cpp, callee.cpp, callee_2.cpp, callee_dispatched.cpp, callee_object.cpp, callee_object_inherited.cpp, caller_dispatched.cpp, caller_object.cpp, signal_emitter_3.cpp, signal_emitter_object.cpp, signal_receiver.cpp, signal_receiver_2.cpp, and signal_receiver_object.cpp.
References Dispatcher().
create_connection() [1/4]
Connection::pointer DBus::Dispatcher::create_connection (DBusConnection * cobj = NULL, bool is_private = false)
References add_connection(), and DBus::Connection::create().
create_connection() [2/4]
Connection::pointer DBus::Dispatcher::create_connection (BusType type, bool is_private = false)
References add_connection(), and DBus::Connection::create().
create_connection() [3/4]
Connection::pointer DBus::Dispatcher::create_connection (std::string address, bool is_private = false)
References add_connection(), and DBus::Connection::create().
create_connection() [4/4]
Connection::pointer DBus::Dispatcher::create_connection (const Connection & other)
References add_connection(), and DBus::Connection::create().
dispatch_connections()
void DBus::Dispatcher::dispatch_connections () protected
Dispatch all of our connections.
References DBus::DISPATCH_COMPLETE, DBus::DISPATCH_DATA_REMAINS, m_connections, m_dispatch_loop_limit, and wakeup_thread().
Referenced by dispatch_thread_main(), and DBus::Glib::Dispatcher::on_glibmm_dispatch().
dispatch_thread_main()
void DBus::Dispatcher::dispatch_thread_main () protected virtual
Reimplemented in DBus::Glib::Dispatcher.
References add_read_and_write_watches(), dispatch_connections(), handle_read_and_write_watches(), m_running, and process_fd.
Referenced by start().
handle_read_and_write_watches()
void DBus::Dispatcher::handle_read_and_write_watches (std::vector< struct pollfd > * fds) protected
Handle all of the read and write watches if the given FD needs to be serviced.
References m_mutex_watches, and m_watches_map.
Referenced by dispatch_thread_main().
is_running()
bool DBus::Dispatcher::is_running ()
References m_running.
Referenced by DBus::Glib::Dispatcher::~Dispatcher().
on_add_timeout()
bool DBus::Dispatcher::on_add_timeout (Timeout::pointer timeout) protected
Referenced by add_connection().
on_add_watch()
bool DBus::Dispatcher::on_add_watch (Watch::pointer watch) protected
References m_mutex_watches, m_watches_map, DBus::Dispatcher::WatchPair::read_watch, wakeup_thread(), and DBus::Dispatcher::WatchPair::write_watch.
Referenced by add_connection().
on_dispatch_status_changed()
void DBus::Dispatcher::on_dispatch_status_changed (DispatchStatus status, Connection::pointer conn) protected
References DBus::DISPATCH_DATA_REMAINS, and wakeup_thread().
Referenced by add_connection().
on_remove_timeout()
bool DBus::Dispatcher::on_remove_timeout (Timeout::pointer timeout) protected
Referenced by add_connection().
on_remove_watch()
bool DBus::Dispatcher::on_remove_watch (Watch::pointer watch) protected
References m_mutex_watches, m_watches_map, and wakeup_thread().
Referenced by add_connection().
on_timeout_toggled()
bool DBus::Dispatcher::on_timeout_toggled (Timeout::pointer timeout) protected
Referenced by add_connection().
on_wakeup_main()
void DBus::Dispatcher::on_wakeup_main (Connection::pointer conn) protected
References wakeup_thread().
Referenced by add_connection().
on_watch_toggled()
void DBus::Dispatcher::on_watch_toggled (Watch::pointer watch) protected
References wakeup_thread().
Referenced by add_connection().
start()
bool DBus::Dispatcher::start ()
References dispatch_thread_main(), m_dispatch_thread, and m_running.
Referenced by DBus::Glib::Dispatcher::Dispatcher(), and Dispatcher().
stop()
bool DBus::Dispatcher::stop ()
References m_dispatch_thread, m_running, and wakeup_thread().
Referenced by DBus::Glib::Dispatcher::~Dispatcher(), and ~Dispatcher().
wakeup_thread()
void DBus::Dispatcher::wakeup_thread () protected
References process_fd.
Referenced by dispatch_connections(), on_add_watch(), on_dispatch_status_changed(), on_remove_watch(), on_wakeup_main(), on_watch_toggled(), and stop().
Member Data Documentation
m_connections
Connections DBus::Dispatcher::m_connections protected
Referenced by add_connection(), and dispatch_connections().
m_dispatch_loop_limit
unsigned int DBus::Dispatcher::m_dispatch_loop_limit protected
This is the maximum number of dispatches that will occur for a connection in one iteration of the dispatch thread.
If set to 0, a particular connection will continue to dispatch as long as its status remains DISPATCH_DATA_REMAINS.
Referenced by dispatch_connections().
m_dispatch_thread
std::thread* DBus::Dispatcher::m_dispatch_thread protected
Referenced by start(), and stop().
m_exception_fd_set
std::vector<int> DBus::Dispatcher::m_exception_fd_set protected
m_mutex_exception_fd_set
std::mutex DBus::Dispatcher::m_mutex_exception_fd_set protected
m_mutex_watches
std::mutex DBus::Dispatcher::m_mutex_watches protected
Referenced by add_read_and_write_watches(), handle_read_and_write_watches(), on_add_watch(), and on_remove_watch().
m_running
volatile bool DBus::Dispatcher::m_running protected
Referenced by DBus::Glib::Dispatcher::dispatch_thread_main(), dispatch_thread_main(), is_running(), start(), and stop().
m_watches_map
std::map<int,WatchPair> DBus::Dispatcher::m_watches_map protected
Referenced by add_read_and_write_watches(), handle_read_and_write_watches(), on_add_watch(), and on_remove_watch().
process_fd
int DBus::Dispatcher::process_fd[2] protected
Referenced by DBus::Glib::Dispatcher::dispatch_thread_main(), dispatch_thread_main(), Dispatcher(), and wakeup_thread().
The documentation for this class was generated from the following files:
dispatcher.h
dispatcher.cpp