dbus-cxx: DBus::priv::SimpleTransport Class Reference
DBus::priv::SimpleTransport Class Reference
The SimpleTransport handles reading and writing over a Unix FD.
#include <simpletransport.h>
Public Member Functions
~SimpleTransport ()
ssize_t writeMessage (std::shared_ptr< const Message > message, uint32_t serial)
std::shared_ptr< Message > readMessage ()
bool is_valid () const
Check if this transport is OK.
int fd () const
Public Member Functions inherited from DBus::priv::Transport
virtual ~Transport ()
Static Public Member Functions
static std::shared_ptr< SimpleTransport > create (int fd, bool initialize)
Create a SimpleTransport.
Static Public Member Functions inherited from DBus::priv::Transport
static std::shared_ptr< Transport > open_transport (std::string address)
Open and return a transport based off of the given address.
Private Member Functions
SimpleTransport (int fd, bool initialize)
void purgeData ()
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Additional Inherited Members
Protected Attributes inherited from DBus::priv::Transport
std::vector< uint8_t > m_serverAddress
Detailed Description
The SimpleTransport handles reading and writing over a Unix FD.
Constructor & Destructor Documentation
SimpleTransport()
SimpleTransport::SimpleTransport (int fd, bool initialize) private
References LOGGER_NAME.
Referenced by create().
~SimpleTransport()
SimpleTransport::~SimpleTransport ()
Member Function Documentation
create()
std::shared_ptr< SimpleTransport > SimpleTransport::create (int fd, bool initialize) static
Create a SimpleTransport.
If the transport is unable to be created, returns an invalid shared_ptr.
Parameters
fd The already-open file descriptor
initialize True if this transport should initialize the connection by sending a single NULL byte
Returns
References SimpleTransport().
DBUS_CXX_PROPAGATE_CONST()
DBus::priv::SimpleTransport::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
fd()
int SimpleTransport::fd () const virtual
Implements DBus::priv::Transport.
is_valid()
bool SimpleTransport::is_valid () const virtual
Check if this transport is OK.
Returns
Implements DBus::priv::Transport.
purgeData()
void SimpleTransport::purgeData () private
References FirstHeaderPart.
Referenced by readMessage().
readMessage()
std::shared_ptr< DBus::Message > SimpleTransport::readMessage () virtual
Implements DBus::priv::Transport.
References DBus::Big, Body, DBus::Message::create_from_data(), DBus::Demarshaling::demarshal_uint32_t(), DBus::Demarshaling::demarshal_uint8_t(), FirstHeaderPart, DBus::hexdump(), DBus::Little, LOGGER_NAME, DBus::Validator::maximum_message_size(), purgeData(), SecondHeaderPart, DBus::Demarshaling::set_data_offset(), and DBus::Demarshaling::set_endianess().
writeMessage()
ssize_t SimpleTransport::writeMessage (std::shared_ptr< const Message > message, uint32_t serial) virtual
Implements DBus::priv::Transport.
References DBus::hexdump(), and LOGGER_NAME.
The documentation for this class was generated from the following files:
simpletransport.h
simpletransport.cpp