dbus-cxx: DBus::Property< T_type > Class Template Reference
DBus::Property< T_type > Class Template Reference
Represents a local DBus property.
#include <property.h>
Public Member Functions
void set_value (T_type t)
T_type value () const
virtual std::string introspect (int space_depth)
Public Member Functions inherited from DBus::PropertyBase
std::string name () const
Get the name of this propery.
Variant variant_value () const
Get the value of this property as a Variant.
PropertyUpdateType update_type () const
PropertyAccess access_type () const
void set_value (Variant value)
Set the value of this property.
virtual std::string introspect (int)
Static Public Member Functions
static std::shared_ptr< Property< T_type > > create (std::string name, PropertyAccess access, PropertyUpdateType update)
Private Member Functions
Property (std::string name, PropertyAccess access, PropertyUpdateType update)
Additional Inherited Members
Protected Member Functions inherited from DBus::PropertyBase
PropertyBase (std::string name, PropertyAccess access, PropertyUpdateType update)
~PropertyBase ()
Detailed Description
template<typename T_type>
class DBus::Property< T_type >
Represents a local DBus property.
Properties can be Read, Write, or Readonly. When they change, a signal may be emitted on the bus to listeners.
Constructor & Destructor Documentation
Property()
template<typename T_type > DBus::Property< T_type >::Property (std::string name, PropertyAccess access, PropertyUpdateType update) inline private
Member Function Documentation
create()
template<typename T_type > static std::shared_ptr< Property< T_type > > DBus::Property< T_type >::create (std::string name, PropertyAccess access, PropertyUpdateType update) inline static
References DBus::PropertyBase::name().
Referenced by DBus::Interface::create_property().
introspect()
template<typename T_type > virtual std::string DBus::Property< T_type >::introspect (int space_depth) inline virtual
Reimplemented from DBus::PropertyBase.
References DBus::PropertyBase::access_type(), DBus::Const, DBUS_CXX_PROPERTY_EMITS_CHANGE_SIGNAL_ANNOTATION, DBus::DoesNotUpdate, DBus::Invalidates, DBus::PropertyBase::name(), DBus::ReadOnly, DBus::ReadWrite, DBus::PropertyBase::update_type(), DBus::Updates, and DBus::WriteOnly.
set_value()
template<typename T_type > void DBus::Property< T_type >::set_value (T_type t) inline
References DBus::PropertyBase::set_value().
value()
template<typename T_type > T_type DBus::Property< T_type >::value () const inline
References DBus::PropertyBase::variant_value().
The documentation for this class was generated from the following file:
property.h