dbus-cxx: DBus::MatchRuleBuilder Class Reference
DBus::MatchRuleBuilder Class Reference
A builder to create match rules.
#include <matchrule.h>
Public Member Functions
MatchRuleBuilder & set_path (const std::string &path)
MatchRuleBuilder & set_interface (const std::string &interface_name)
MatchRuleBuilder & set_member (const std::string &member)
MatchRuleBuilder & set_sender (const std::string &sender)
MatchRuleBuilder & set_destination (const std::string &destination)
SignalMatchRule as_signal_match ()
MethodCallMatchRule as_method_call_match ()
MethodReturnMatchRule as_method_return_match ()
ErrorMatchRule as_error_match ()
Static Public Member Functions
static MatchRuleBuilder create ()
Protected Member Functions
MatchRuleBuilder ()
Private Attributes
std::shared_ptr< MatchRuleData > m_priv
Detailed Description
A builder to create match rules.
When you are done building the match rule, call the appropriate method(asSignalMatch, asMethodCallMatch, etc).
Constructor & Destructor Documentation
MatchRuleBuilder()
MatchRuleBuilder::MatchRuleBuilder () protected
Member Function Documentation
as_error_match()
ErrorMatchRule MatchRuleBuilder::as_error_match ()
References m_priv.
as_method_call_match()
MethodCallMatchRule MatchRuleBuilder::as_method_call_match ()
References m_priv.
as_method_return_match()
MethodReturnMatchRule MatchRuleBuilder::as_method_return_match ()
References m_priv.
as_signal_match()
SignalMatchRule MatchRuleBuilder::as_signal_match ()
References m_priv.
Referenced by DBus::InterfaceProxy::create_signal(), DBus::InterfaceProxy::set_object(), and DBus::SignalProxyBase::update_match_rule().
create()
MatchRuleBuilder MatchRuleBuilder::create () static
Referenced by DBus::InterfaceProxy::create_signal(), DBus::InterfaceProxy::set_object(), and DBus::SignalProxyBase::update_match_rule().
set_destination()
MatchRuleBuilder & MatchRuleBuilder::set_destination (const std::string & destination)
References m_priv.
set_interface()
MatchRuleBuilder & MatchRuleBuilder::set_interface (const std::string & interface_name)
References m_priv.
Referenced by DBus::InterfaceProxy::create_signal(), DBus::InterfaceProxy::set_object(), and DBus::SignalProxyBase::update_match_rule().
set_member()
MatchRuleBuilder & MatchRuleBuilder::set_member (const std::string & member)
References m_priv.
Referenced by DBus::InterfaceProxy::create_signal(), DBus::InterfaceProxy::set_object(), and DBus::SignalProxyBase::update_match_rule().
set_path()
MatchRuleBuilder & MatchRuleBuilder::set_path (const std::string & path)
References m_priv.
Referenced by DBus::InterfaceProxy::create_signal(), DBus::InterfaceProxy::set_object(), and DBus::SignalProxyBase::update_match_rule().
set_sender()
MatchRuleBuilder & MatchRuleBuilder::set_sender (const std::string & sender)
References m_priv.
Member Data Documentation
m_priv
std::shared_ptr<MatchRuleData> DBus::MatchRuleBuilder::m_priv private
Referenced by as_error_match(), as_method_call_match(), as_method_return_match(), as_signal_match(), set_destination(), set_interface(), set_member(), set_path(), and set_sender().
The documentation for this class was generated from the following files:
matchrule.h
matchrule.cpp