DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
Local Objects | Objects
#include <method.h>
Public Types
typedef DBusCxxPointer< Method > pointer
typedef DBusCxxPointer< Method > pointer
Public Types inherited from DBus::MethodBase
typedef DBusCxxPointer< MethodBase > pointer
Public Member Functions
Method (const std::string &name)
virtual ~Method ()
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
void set_method (sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > slot)
virtual MethodBase::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Method (const std::string &name)
virtual HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
void set_method (sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > slot)
virtual MethodBase::pointer clone ()
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Public Member Functions inherited from DBus::MethodBase
virtual ~MethodBase ()
const std::string & name () const
void set_name (const std::string &name)
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Static Public Member Functions
static pointer create (const std::string &name)
static pointer create (const std::string &name)
Protected Attributes
std::string m_arg_names [4+1]
sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > m_slot
Protected Attributes inherited from DBus::MethodBase
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
Additional Inherited Members
Protected Member Functions inherited from DBus::MethodBase
MethodBase (const std::string &name)
MethodBase (const MethodBase &other)
Detailed Description
template<class T_arg1, class T_arg2, class T_arg3, class T_arg4>
class DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > typedef DBusCxxPointer<Method> DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::pointer
pointer [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > typedef DBusCxxPointer<Method> DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::pointer
Constructor & Destructor Documentation
Method() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::Method (const std::string & name) inline
~Method()
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::~Method () inline virtual
Method() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::Method (const std::string & name) inline
Member Function Documentation
arg_name() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual std::string DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name (size_t i) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
arg_name() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual std::string DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::arg_name (size_t i) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names.
clone() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual MethodBase::pointer DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone () inline virtual
Implements DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method(), and DBus::MethodBase::name().
clone() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual MethodBase::pointer DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::clone () inline virtual
Implements DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method(), and DBus::MethodBase::name().
create() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > static pointer DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create (const std::string & name) inline static
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method().
create() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > static pointer DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create (const std::string & name) inline static
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::Method().
handle_call_message() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual HandlerResult DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) inline virtual
Implements DBus::MethodBase.
References DBUSCXX_DEBUG_STDSTR, DBus::HANDLED, DBus::MethodBase::m_name, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot, and DBus::NOT_HANDLED.
handle_call_message() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual HandlerResult DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message) inline virtual
Implements DBus::MethodBase.
References DBus::ErrorMessage::create(), DBUS_CXX_PACKAGE_MAJOR_VERSION, DBUS_CXX_PACKAGE_MICRO_VERSION, DBUS_CXX_PACKAGE_MINOR_VERSION, DBUSCXX_DEBUG_STDSTR, DBus::HANDLED, DBus::MethodBase::m_name, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot, and DBus::NOT_HANDLED.
introspect() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual std::string DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect (int space_depth = 0) const inline virtual
Returns a DBus XML description of this interface.
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::MethodBase::name().
introspect() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual std::string DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::introspect (int space_depth = 0) const inline virtual
Returns a DBus XML description of this interface.
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, DBus::MethodBase::name(), and DBus::signature().
set_arg_name() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual void DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name (size_t i, const std::string & name) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot, and DBus::MethodBase::name().
set_arg_name() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > virtual void DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_arg_name (size_t i, const std::string & name) inline virtual
Reimplemented from DBus::MethodBase.
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_arg_names, and DBus::MethodBase::name().
set_method() [1/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > void DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method (sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > slot) inline
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot.
set_method() [2/2]
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > void DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::set_method (sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > slot) inline
References DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::m_slot.
Member Data Documentation
m_arg_names
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > std::string DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::m_arg_names protected
m_slot
template<class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > sigc::slot4< void, T_arg1, T_arg2, T_arg3, T_arg4 > DBus::Method< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::m_slot protected
The documentation for this class was generated from the following files:
method.h
method_impl.h