DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > Class Template Reference
DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > Class Template Reference
Signals | Proxy
Subclass of the numbered sigc::signal templates.
#include <signal_proxy.h>
Public Types
typedef DBusCxxPointer
< signal_proxy > pointer
Public Types inherited from DBus::signal_proxy_base
typedef DBusCxxPointer
< signal_proxy_base > pointer
Public Types inherited from DBus::signal_base
typedef DBusCxxPointer
< signal_base > pointer
Public Member Functions
signal_proxy (const std::string &interface, const std::string &name)
signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy (const std::string &interface, const std::string &name, const signal_proxy &src)
signal_proxy (const std::string &path, const std::string &interface, const std::string &name, const signal_proxy &src)
virtual signal_base::pointer clone ()
Public Member Functions inherited from DBus::signal_proxy_base
signal_proxy_base (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_base (const std::string &interface, const std::string &name)
signal_proxy_base (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_base (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_proxy_base (const signal_proxy_base &other)
virtual ~signal_proxy_base ()
virtual HandlerResult handle_signal (SignalMessage::const_pointer)
sigc::signal< HandlerResult,
SignalMessage::const_pointer >
::accumulated
< MessageHandlerAccumulator > signal_dbus_incoming ()
const std::string & match_rule ()
bool matches (Message::const_pointer msg)
Public Member Functions inherited from DBus::signal_base
virtual ~signal_base ()
DBusCxxPointer< Connection > connection ()
void set_connection (DBusCxxPointer< Connection > connection)
const std::string & sender () const
void set_sender (const std::string &s)
const std::string & interface () const
void set_interface (const std::string &i)
const std::string & name () const
void set_name (const std::string &n)
const Path & path () const
void set_path (const std::string &s)
const std::string & destination () const
void set_destination (const std::string &s)
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Static Public Member Functions
static pointer create (const std::string &interface, const std::string &name)
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
static pointer create (const std::string &interface, const std::string &name, const signal_proxy &src)
static pointer create (const std::string &path, const std::string &interface, const std::string &name, const signal_proxy &src)
Protected Member Functions
virtual HandlerResult on_dbus_incoming (SignalMessage::const_pointer msg)
Protected Member Functions inherited from DBus::signal_base
signal_base (const std::string &path, const std::string &interface, const std::string &name)
signal_base (const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_base (const signal_base &other)
bool handle_dbus_outgoing (Message::const_pointer)
Additional Inherited Members
Protected Attributes inherited from DBus::signal_proxy_base
std::string m_match_rule
sigc::signal< HandlerResult,
SignalMessage::const_pointer >
::accumulated
< MessageHandlerAccumulator > m_signal_dbus_incoming
Protected Attributes inherited from DBus::signal_base
DBusCxxWeakPointer< Connection > m_connection
std::string m_sender
Path m_path
std::string m_interface
std::string m_name
std::string m_destination
std::string m_match_rule
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4, class T_arg5, class T_arg6>
class DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >
Subclass of the numbered sigc::signal templates.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > typedef DBusCxxPointer<signal_proxy> DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::pointer
Constructor & Destructor Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal_proxy (const std::string & interface, const std::string & name) inline
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal_proxy (const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) inline
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::signal_proxy (const std::string & path, const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) inline
References DBus::signal_proxy_base::m_signal_dbus_incoming, and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::on_dbus_incoming().
Member Function Documentation
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual signal_base::pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::clone () inline virtual
Implements DBus::signal_proxy_base.
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & interface, const std::string & name) inline static
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & path, const std::string & interface, const std::string & name) inline static
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) inline static
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > static pointer DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::create (const std::string & path, const std::string & interface, const std::string & name, const signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil > & src) inline static
References DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::signal_proxy().
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > virtual HandlerResult DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::on_dbus_incoming (SignalMessage::const_pointer msg) inline protected virtual
References DBus::HANDLED, and DBus::NOT_HANDLED.
The documentation for this class was generated from the following file:
signal_proxy.h