dbus-cxx: DBus::MatchRule Class Reference
DBus::MatchRule Class Reference
Immutable class that represents a match rule for DBus.
#include <matchrule.h>
Public Member Functions
std::string match_rule () const
std::string path () const
std::string dbus_interface () const
std::string member () const
Protected Member Functions
MatchRule (std::string type, const std::shared_ptr< MatchRuleData >)
Private Member Functions
DBUS_CXX_PROPAGATE_CONST (std::shared_ptr< MatchRuleData >) m_priv
Friends
class MatchRuleBuilder
Detailed Description
Immutable class that represents a match rule for DBus.
Constructor & Destructor Documentation
MatchRule()
MatchRule::MatchRule (std::string type, const std::shared_ptr< MatchRuleData > data) protected
References DBus::type().
Member Function Documentation
DBUS_CXX_PROPAGATE_CONST()
DBus::MatchRule::DBUS_CXX_PROPAGATE_CONST (std::shared_ptr< MatchRuleData >) private
dbus_interface()
std::string MatchRule::dbus_interface () const
match_rule()
std::string MatchRule::match_rule () const
Referenced by DBus::SignalProxyBase::SignalProxyBase(), and DBus::SignalProxyBase::update_match_rule().
member()
std::string MatchRule::member () const
path()
std::string MatchRule::path () const
Friends And Related Function Documentation
MatchRuleBuilder
friend class MatchRuleBuilder friend
The documentation for this class was generated from the following files:
matchrule.h
matchrule.cpp