dbus-cxx: DBus::Variant Class Reference
DBus::Variant Class Reference
A Variant is a type-safe union for DBus operations.
#include <variant.h>
Public Member Functions
Variant ()
Variant (uint8_t byte)
Variant (bool b)
Variant (int16_t i)
Variant (uint16_t i)
Variant (int32_t i)
Variant (uint32_t i)
Variant (int64_t i)
Variant (uint64_t i)
Variant (double i)
Variant (const char *cstr)
Variant (std::string str)
Variant (Signature sig)
Variant (Path path)
template<typename T >
Variant (const std::vector< T > &vec)
template<typename Key , typename Value >
Variant (const std::map< Key, Value > &map)
template<typename ... T>
Variant (const std::tuple< T... > &tup)
Variant (const Variant &other)
Variant (Variant &&other)
~Variant ()
Signature signature () const
DataType type () const
const std::vector< uint8_t > * marshaled () const
int data_alignment () const
bool operator== (const Variant &other) const
Variant & operator= (const Variant &other)
template<typename T >
std::vector< T > to_vector ()
template<typename Key , typename Value >
std::map< Key, Value > to_map ()
template<typename ... T>
std::tuple< T... > to_tuple ()
bool to_bool () const
uint8_t to_uint8 () const
uint16_t to_uint16 () const
int16_t to_int16 () const
uint32_t to_uint32 () const
int32_t to_int32 () const
uint64_t to_uint64 () const
int64_t to_int64 () const
double to_double () const
std::string to_string () const
DBus::Path to_path () const
DBus::Signature to_signature () const
operator bool ()
operator uint8_t ()
operator uint16_t ()
operator int16_t ()
operator uint32_t ()
operator int32_t ()
operator uint64_t ()
operator int64_t ()
operator double ()
operator std::string ()
operator DBus::Path ()
operator DBus::Signature ()
template<typename T >
operator std::vector< T > ()
template<typename Key , typename Data >
operator std::map< Key, Data > ()
template<typename... T>
operator std::tuple< T... > ()
Static Public Member Functions
static Variant createFromMessage (MessageIterator iter)
Obsolete, do not call.
static Variant createFromDemarshal (Signature sig, std::shared_ptr< Demarshaling > demarshal, const std::vector< int > &filedescriptors, uint32_t depth)
Private Member Functions
void recurseArray (SignatureIterator iter, std::shared_ptr< Demarshaling > demarshal, Marshaling *marshal, const std::vector< int > &filedescriptors, uint32_t depth)
void recurseDictEntry (SignatureIterator iter, std::shared_ptr< Demarshaling > demarshal, Marshaling *marshal, uint32_t ending_offset, const std::vector< int > &filedescriptors, uint32_t depth)
void recurseStruct (SignatureIterator sigit, std::shared_ptr< Demarshaling > demarshal, Marshaling *marshal, const std::vector< int > &filedescriptors, uint32_t depth)
void remarshal (DataType dt, SignatureIterator sigit, std::shared_ptr< Demarshaling > demarshal, Marshaling *marshal, const std::vector< int > &filedescriptors, uint32_t depth)
void recurseArray (MessageIterator iter, Marshaling *marshal)
Obsolete, do not call.
void recurseDictEntry (MessageIterator iter, Marshaling *marshal)
Obsolete, do not call.
void recurseStruct (MessageIterator iter, Marshaling *marshal)
Obsolete, do not call.
Private Attributes
DataType m_currentType
Signature m_signature
std::vector< uint8_t > m_marshaled
int m_dataAlignment
Friends
class priv::VariantAppendIterator
class priv::VariantIterator
std::ostream & operator<< (std::ostream &os, const Variant &var)
Detailed Description
A Variant is a type-safe union for DBus operations.
Variants are immutable - once you create them, you cannot change them.
To get the value out of the variant, use one of the to_XXX methods. If the type you requested is not possible to get out, an ErrorBadVariantCast will be thrown.
Constructor & Destructor Documentation
Variant() [1/19]
Variant::Variant ()
References DBus::INVALID.
Variant() [2/19]
Variant::Variant (uint8_t byte)
References DBus::BYTE, DBus::default_endianess(), m_marshaled, and DBus::Marshaling::marshal().
Variant() [3/19]
Variant::Variant (bool b)
References DBus::BOOLEAN, DBus::default_endianess(), m_marshaled, and DBus::Marshaling::marshal().
Variant() [4/19]
Variant::Variant (int16_t i)
References DBus::default_endianess(), DBus::INT16, m_marshaled, and DBus::Marshaling::marshal().
Variant() [5/19]
Variant::Variant (uint16_t i)
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::UINT16.
Variant() [6/19]
Variant::Variant (int32_t i)
References DBus::default_endianess(), DBus::INT32, m_marshaled, and DBus::Marshaling::marshal().
Variant() [7/19]
Variant::Variant (uint32_t i)
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::UINT32.
Variant() [8/19]
Variant::Variant (int64_t i)
References DBus::default_endianess(), DBus::INT64, m_marshaled, and DBus::Marshaling::marshal().
Variant() [9/19]
Variant::Variant (uint64_t i)
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::UINT64.
Variant() [10/19]
Variant::Variant (double i)
References DBus::default_endianess(), DBus::DOUBLE, m_marshaled, and DBus::Marshaling::marshal().
Variant() [11/19]
Variant::Variant (const char * cstr)
Variant() [12/19]
Variant::Variant (std::string str)
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::STRING.
Variant() [13/19]
Variant::Variant (DBus::Signature sig) explicit
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::SIGNATURE.
Variant() [14/19]
Variant::Variant (DBus::Path path) explicit
References DBus::default_endianess(), m_marshaled, DBus::Marshaling::marshal(), and DBus::OBJECT_PATH.
Variant() [15/19]
template<typename T > DBus::Variant::Variant (const std::vector< T > & vec) inline
References DBus::ARRAY.
Variant() [16/19]
template<typename Key , typename Value > DBus::Variant::Variant (const std::map< Key, Value > & map) inline
References DBus::ARRAY.
Variant() [17/19]
template<typename ... T> DBus::Variant::Variant (const std::tuple< T... > & tup) inline
References DBus::STRUCT.
Variant() [18/19]
Variant::Variant (const Variant & other)
Variant() [19/19]
Variant::Variant (Variant && other)
References DBus::INVALID.
~Variant()
Variant::~Variant ()
Member Function Documentation
createFromDemarshal()
Variant Variant::createFromDemarshal (Signature sig, std::shared_ptr< Demarshaling > demarshal, const std::vector< int > & filedescriptors, uint32_t depth) static
References DBus::TypeInfo::alignment(), DBus::ARRAY, DBus::Signature::begin(), DBus::BOOLEAN, DBus::BYTE, DBus::default_endianess(), DBus::DOUBLE, DBus::INT16, DBus::INT32, DBus::INT64, DBus::INVALID, LOGGER_NAME, m_currentType, m_dataAlignment, m_marshaled, m_signature, DBus::Marshaling::marshal(), DBus::Validator::maximum_message_depth(), DBus::OBJECT_PATH, DBus::SignatureIterator::recurse(), recurseArray(), recurseStruct(), DBus::SIGNATURE, SIMPLELOGGER_TRACE, DBus::STRING, DBus::STRUCT, DBus::SignatureIterator::type(), DBus::UINT16, DBus::UINT32, and DBus::UINT64.
Referenced by DBus::MessageIterator::get_variant(), DBus::priv::VariantIterator::get_variant(), and remarshal().
createFromMessage()
DBus::Variant Variant::createFromMessage (MessageIterator iter) static
Obsolete, do not call.
data_alignment()
int Variant::data_alignment () const
References m_dataAlignment.
Referenced by DBus::Marshaling::marshal(), DBus::MessageAppendIterator::operator<<(), and DBus::priv::VariantAppendIterator::operator<<().
marshaled()
const std::vector< uint8_t > * Variant::marshaled () const
References m_marshaled.
Referenced by DBus::Marshaling::marshal(), DBus::MessageAppendIterator::operator<<(), DBus::priv::VariantAppendIterator::operator<<(), and remarshal().
operator bool()
Variant::operator bool ()
operator DBus::Path()
Variant::operator DBus::Path ()
operator DBus::Signature()
Variant::operator DBus::Signature ()
operator double()
Variant::operator double ()
operator int16_t()
Variant::operator int16_t ()
operator int32_t()
Variant::operator int32_t ()
operator int64_t()
Variant::operator int64_t ()
operator std::map< Key, Data >()
template<typename Key , typename Data > DBus::Variant::operator std::map< Key, Data > () inline
operator std::string()
Variant::operator std::string ()
operator std::tuple< T... >()
template<typename... T> DBus::Variant::operator std::tuple< T... > () inline
References to_tuple().
operator std::vector< T >()
template<typename T > DBus::Variant::operator std::vector< T > () inline
operator uint16_t()
Variant::operator uint16_t ()
operator uint32_t()
Variant::operator uint32_t ()
operator uint64_t()
Variant::operator uint64_t ()
operator uint8_t()
Variant::operator uint8_t ()
operator=()
Variant & Variant::operator= (const Variant & other)
References m_currentType, m_dataAlignment, m_marshaled, and m_signature.
operator==()
bool Variant::operator== (const Variant & other) const
References m_marshaled, and type().
recurseArray() [1/2]
void Variant::recurseArray (MessageIterator iter, Marshaling * marshal) private
Obsolete, do not call.
recurseArray() [2/2]
void Variant::recurseArray (SignatureIterator iter, std::shared_ptr< Demarshaling > demarshal, Marshaling * marshal, const std::vector< int > & filedescriptors, uint32_t depth) private
References DBus::Marshaling::align(), DBus::TypeInfo::alignment(), DBus::default_endianess(), DBus::DICT_ENTRY, LOGGER_NAME, DBus::Marshaling::marshal(), DBus::Validator::maximum_message_depth(), DBus::SignatureIterator::recurse(), recurseDictEntry(), remarshal(), SIMPLELOGGER_TRACE, and DBus::SignatureIterator::type().
Referenced by createFromDemarshal(), and remarshal().
recurseDictEntry() [1/2]
void Variant::recurseDictEntry (MessageIterator iter, Marshaling * marshal) private
Obsolete, do not call.
recurseDictEntry() [2/2]
void Variant::recurseDictEntry (SignatureIterator iter, std::shared_ptr< Demarshaling > demarshal, Marshaling * marshal, uint32_t ending_offset, const std::vector< int > & filedescriptors, uint32_t depth) private
References DBus::Marshaling::align(), LOGGER_NAME, DBus::Validator::maximum_message_depth(), remarshal(), SIMPLELOGGER_TRACE, and DBus::SignatureIterator::type().
Referenced by recurseArray().
recurseStruct() [1/2]
void Variant::recurseStruct (MessageIterator iter, Marshaling * marshal) private
Obsolete, do not call.
recurseStruct() [2/2]
void Variant::recurseStruct (SignatureIterator sigit, std::shared_ptr< Demarshaling > demarshal, Marshaling * marshal, const std::vector< int > & filedescriptors, uint32_t depth) private
References DBus::Marshaling::align(), DBus::SignatureIterator::is_valid(), DBus::Validator::maximum_message_depth(), remarshal(), and DBus::SignatureIterator::type().
Referenced by createFromDemarshal(), and remarshal().
remarshal()
void Variant::remarshal (DataType dt, SignatureIterator sigit, std::shared_ptr< Demarshaling > demarshal, Marshaling * marshal, const std::vector< int > & filedescriptors, uint32_t depth) private
References DBus::Marshaling::align(), DBus::TypeInfo::alignment(), DBus::ARRAY, DBus::Signature::begin(), DBus::BOOLEAN, DBus::BYTE, createFromDemarshal(), DBus::DICT_ENTRY, DBus::DOUBLE, DBus::Signature::end(), DBus::INT16, DBus::INT32, DBus::INT64, DBus::Marshaling::marshal(), marshaled(), DBus::OBJECT_PATH, DBus::SignatureIterator::recurse(), recurseArray(), recurseStruct(), DBus::SIGNATURE, DBus::STRING, DBus::STRUCT, type(), DBus::UINT16, DBus::UINT32, DBus::UINT64, and DBus::VARIANT.
Referenced by recurseArray(), recurseDictEntry(), and recurseStruct().
signature()
DBus::Signature Variant::signature () const
References m_signature.
Referenced by DBus::Marshaling::marshal(), DBus::MessageAppendIterator::operator<<(), and DBus::priv::VariantIterator::VariantIterator().
to_bool()
bool Variant::to_bool () const
References DBus::BOOLEAN, DBus::priv::VariantIterator::get_bool(), and m_currentType.
to_double()
double Variant::to_double () const
References DBus::DOUBLE, DBus::priv::VariantIterator::get_double(), and m_currentType.
to_int16()
int16_t Variant::to_int16 () const
References DBus::priv::VariantIterator::get_int16(), DBus::INT16, and m_currentType.
to_int32()
int32_t Variant::to_int32 () const
References DBus::priv::VariantIterator::get_int32(), DBus::INT32, and m_currentType.
to_int64()
int64_t Variant::to_int64 () const
References DBus::priv::VariantIterator::get_int64(), DBus::INT64, and m_currentType.
to_map()
template<typename Key , typename Value > std::map<Key, Value> DBus::Variant::to_map () inline
References DBus::ARRAY, and m_currentType.
to_path()
DBus::Path Variant::to_path () const
References DBus::priv::VariantIterator::get_string(), m_currentType, and DBus::OBJECT_PATH.
Referenced by DBus::CallMessage::path(), and DBus::SignalMessage::path().
to_signature()
DBus::Signature Variant::to_signature () const
References DBus::priv::VariantIterator::get_signature(), m_currentType, and DBus::SIGNATURE.
Referenced by DBus::Message::append_signature(), and DBus::Message::signature().
to_string()
std::string Variant::to_string () const
References DBus::priv::VariantIterator::get_string(), m_currentType, and DBus::STRING.
Referenced by DBus::CallMessage::interface_name(), DBus::SignalMessage::interface_name(), DBus::SignalMessage::member(), and DBus::ErrorMessage::name().
to_tuple()
template<typename ... T> std::tuple<T...> DBus::Variant::to_tuple () inline
References m_currentType, and DBus::STRUCT.
Referenced by operator std::tuple< T... >().
to_uint16()
uint16_t Variant::to_uint16 () const
References DBus::priv::VariantIterator::get_uint16(), m_currentType, and DBus::UINT16.
to_uint32()
uint32_t Variant::to_uint32 () const
References DBus::priv::VariantIterator::get_uint32(), m_currentType, and DBus::UINT32.
Referenced by DBus::Message::create_from_data(), DBus::ErrorMessage::reply_serial(), DBus::ReturnMessage::reply_serial(), and DBus::Message::serialize_to_vector().
to_uint64()
uint64_t Variant::to_uint64 () const
References DBus::priv::VariantIterator::get_uint64(), m_currentType, and DBus::UINT64.
to_uint8()
uint8_t Variant::to_uint8 () const
References DBus::BYTE, DBus::priv::VariantIterator::get_uint8(), and m_currentType.
to_vector()
template<typename T > std::vector<T> DBus::Variant::to_vector () inline
References DBus::ARRAY, and m_currentType.
type()
DBus::DataType Variant::type () const
References m_currentType.
Referenced by DBus::Message::append_signature(), DBus::CallMessage::interface_name(), DBus::SignalMessage::interface_name(), DBus::SignalMessage::member(), DBus::ErrorMessage::name(), DBus::MessageAppendIterator::operator<<(), DBus::priv::VariantAppendIterator::operator<<(), operator==(), DBus::CallMessage::path(), DBus::SignalMessage::path(), remarshal(), DBus::ErrorMessage::reply_serial(), DBus::ReturnMessage::reply_serial(), DBus::Message::serialize_to_vector(), and DBus::Message::signature().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Variant & var) friend
priv::VariantAppendIterator
friend class priv::VariantAppendIterator friend
priv::VariantIterator
friend class priv::VariantIterator friend
Member Data Documentation
m_currentType
DataType DBus::Variant::m_currentType private
Referenced by createFromDemarshal(), DBus::priv::VariantAppendIterator::operator<<(), operator=(), to_bool(), to_double(), to_int16(), to_int32(), to_int64(), to_map(), to_path(), to_signature(), to_string(), to_tuple(), to_uint16(), to_uint32(), to_uint64(), to_uint8(), to_vector(), and type().
m_dataAlignment
int DBus::Variant::m_dataAlignment private
Referenced by createFromDemarshal(), data_alignment(), and operator=().
m_marshaled
std::vector<uint8_t> DBus::Variant::m_marshaled private
Referenced by createFromDemarshal(), marshaled(), operator=(), operator==(), Variant(), DBus::priv::VariantAppendIterator::VariantAppendIterator(), and DBus::priv::VariantIterator::VariantIterator().
m_signature
Signature DBus::Variant::m_signature private
Referenced by createFromDemarshal(), DBus::priv::VariantAppendIterator::operator<<(), operator=(), and signature().
The documentation for this class was generated from the following files:
variant.h
variant.cpp