dbus-cxx: DBus::Qt::QtThreadDispatcher Class Reference
DBus::Qt::QtThreadDispatcher Class Reference
#include <qtthreaddispatcher.h>
Signals
void notifyMainThread ()
Public Member Functions
~QtThreadDispatcher ()
void add_message (std::shared_ptr< Object > object, std::shared_ptr< const CallMessage > message)
void add_signal_proxy (std::shared_ptr< SignalProxyBase > handler)
bool remove_signal_proxy (std::shared_ptr< SignalProxyBase > handler)
void add_signal (std::shared_ptr< const SignalMessage > message)
Public Member Functions inherited from DBus::ThreadDispatcher
virtual ~ThreadDispatcher ()
virtual void add_message (std::shared_ptr< Object > object, std::shared_ptr< const CallMessage > message)=0
When a new message comes in that needs to be processed, this method is called with the object that the method needs to go to, and the message to send to this object.
virtual void add_signal_proxy (std::shared_ptr< SignalProxyBase > handler)=0
Add a signal proxy that must emit its signals from the thread represented by this ThreadDispatcher.
virtual bool remove_signal_proxy (std::shared_ptr< SignalProxyBase > handler)=0
Remove a signal proxy.
virtual void add_signal (std::shared_ptr< const SignalMessage > message)=0
When a new signal message comes in that needs to be processed, this method is called with the SignalMessage that must be emitted from this thread.
Static Public Member Functions
static std::shared_ptr< QtThreadDispatcher > create ()
Private Slots
void sendMessages ()
Private Member Functions
QtThreadDispatcher ()
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Constructor & Destructor Documentation
QtThreadDispatcher()
QtThreadDispatcher::QtThreadDispatcher () private
References notifyMainThread(), and sendMessages().
Referenced by create().
~QtThreadDispatcher()
QtThreadDispatcher::~QtThreadDispatcher ()
Member Function Documentation
add_message()
void QtThreadDispatcher::add_message (std::shared_ptr< Object > object, std::shared_ptr< const CallMessage > message) virtual
Implements DBus::ThreadDispatcher.
References notifyMainThread().
add_signal()
void QtThreadDispatcher::add_signal (std::shared_ptr< const SignalMessage > message) virtual
Implements DBus::ThreadDispatcher.
References notifyMainThread().
add_signal_proxy()
void QtThreadDispatcher::add_signal_proxy (std::shared_ptr< SignalProxyBase > handler) virtual
Implements DBus::ThreadDispatcher.
create()
std::shared_ptr< QtThreadDispatcher > QtThreadDispatcher::create () static
References QtThreadDispatcher().
Referenced by main().
DBUS_CXX_PROPAGATE_CONST()
DBus::Qt::QtThreadDispatcher::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
notifyMainThread
void DBus::Qt::QtThreadDispatcher::notifyMainThread () signal
Referenced by add_message(), add_signal(), and QtThreadDispatcher().
remove_signal_proxy()
bool QtThreadDispatcher::remove_signal_proxy (std::shared_ptr< SignalProxyBase > handler) virtual
Implements DBus::ThreadDispatcher.
sendMessages
void QtThreadDispatcher::sendMessages () private slot
Referenced by QtThreadDispatcher().
The documentation for this class was generated from the following files:
qtthreaddispatcher.h
qtthreaddispatcher.cpp