dbus-cxx: DBus::IntrospectableInterfaceProxy Class Reference
DBus::IntrospectableInterfaceProxy Class Reference
#include <introspectableinterfaceproxy.h>
Public Member Functions
std::string Introspect ()
Public Member Functions inherited from DBus::InterfaceProxy
virtual ~InterfaceProxy ()
ObjectProxy * object () const
Path path () const
std::weak_ptr< Connection > connection () const
const std::string & name () const
const Methods & methods () const
std::shared_ptr< MethodProxyBase > method (const std::string &name) const
Returns the first method with the given name.
template<class T_type >
std::shared_ptr< MethodProxy< T_type > > create_method (const std::string &name)
bool add_method (std::shared_ptr< MethodProxyBase > method)
Adds the named method.
void remove_method (const std::string &name)
Removes the method with the given name.
void remove_method (std::shared_ptr< MethodProxyBase > method)
Removed the specific method.
bool has_method (const std::string &name) const
True if the interface has a method with the given name.
bool has_method (std::shared_ptr< MethodProxyBase > method) const
True if the interface has the specified method.
const std::map< std::string, std::shared_ptr< PropertyProxyBase > > & properties () const
Get the (local) cache of all properties.
std::shared_ptr< PropertyProxyBase > property (const std::string &name) const
bool has_property (const std::string &name) const
True if the interface has a property with the given name.
bool has_property (std::shared_ptr< PropertyProxyBase > property) const
True if the interface has the specified property.
void remove_property (const std::string &name)
Removes the property with the given name.
void remove_property (std::shared_ptr< PropertyProxyBase > method)
Removed the specific property.
template<class T_type >
std::shared_ptr< PropertyProxy< T_type > > create_property (const std::string &name, PropertyUpdateType update=PropertyUpdateType::Updates)
Create a property with the given type, and the given name.
bool add_property (std::shared_ptr< PropertyProxyBase > property)
Adds the given property.
void cache_properties ()
Ask the remote object for the status of all of its properties.
std::shared_ptr< CallMessage > create_call_message (const std::string &method_name) const
std::shared_ptr< const ReturnMessage > call (std::shared_ptr< const CallMessage >, int timeout_milliseconds=-1) const
template<class T_arg >
std::shared_ptr< SignalProxy< T_arg > > create_signal (const std::string &sig_name)
const Signals & signals () const
std::shared_ptr< SignalProxyBase > signal (const std::string &signame)
bool add_signal (std::shared_ptr< SignalProxyBase > sig)
bool remove_signal (const std::string &signame)
bool remove_signal (std::shared_ptr< SignalProxyBase > sig)
bool has_signal (const std::string &signame) const
bool has_signal (std::shared_ptr< SignalProxyBase > sig) const
Static Public Member Functions
static std::shared_ptr< IntrospectableInterfaceProxy > create ()
Static Public Member Functions inherited from DBus::InterfaceProxy
static std::shared_ptr< InterfaceProxy > create (const std::string &name=std::string())
Private Member Functions
IntrospectableInterfaceProxy ()
Private Attributes
std::shared_ptr< MethodProxy< std::string()> > m_introspect_method
Additional Inherited Members
Public Types inherited from DBus::InterfaceProxy
typedef std::multimap< std::string, std::shared_ptr< MethodProxyBase > > Methods
typedef std::set< std::shared_ptr< SignalProxyBase > > Signals
Protected Member Functions inherited from DBus::InterfaceProxy
InterfaceProxy (const std::string &name)
Constructor & Destructor Documentation
IntrospectableInterfaceProxy()
IntrospectableInterfaceProxy::IntrospectableInterfaceProxy () private
References m_introspect_method.
Referenced by create().
Member Function Documentation
create()
std::shared_ptr< IntrospectableInterfaceProxy > IntrospectableInterfaceProxy::create () static
References IntrospectableInterfaceProxy().
Introspect()
std::string IntrospectableInterfaceProxy::Introspect ()
References m_introspect_method.
Member Data Documentation
m_introspect_method
std::shared_ptr<MethodProxy<std::string()> > DBus::IntrospectableInterfaceProxy::m_introspect_method private
Referenced by Introspect(), and IntrospectableInterfaceProxy().
The documentation for this class was generated from the following files:
introspectableinterfaceproxy.h
introspectableinterfaceproxy.cpp