dbus-cxx: DBus::priv::VariantAppendIterator Class Reference
DBus::priv::VariantAppendIterator Class Reference
Used to append a single, complete value to a Variant.
#include <variantappenditerator.h>
Public Member Functions
VariantAppendIterator (Variant *variant)
~VariantAppendIterator ()
VariantAppendIterator & operator<< (const bool &v)
VariantAppendIterator & operator<< (const uint8_t &v)
VariantAppendIterator & operator<< (const int16_t &v)
VariantAppendIterator & operator<< (const uint16_t &v)
VariantAppendIterator & operator<< (const int32_t &v)
VariantAppendIterator & operator<< (const uint32_t &v)
VariantAppendIterator & operator<< (const int64_t &v)
VariantAppendIterator & operator<< (const uint64_t &v)
VariantAppendIterator & operator<< (const double &v)
VariantAppendIterator & operator<< (const char *v)
VariantAppendIterator & operator<< (const std::string &v)
VariantAppendIterator & operator<< (const Signature &v)
VariantAppendIterator & operator<< (const Path &v)
VariantAppendIterator & operator<< (const Variant &v)
template<typename T >
VariantAppendIterator & operator<< (const std::vector< T > &v)
template<typename Key , typename Data >
VariantAppendIterator & operator<< (const std::map< Key, Data > &dictionary)
template<typename... T>
VariantAppendIterator & operator<< (const std::tuple< T... > &tup)
Private Member Functions
VariantAppendIterator (Variant *variant, ContainerType t)
bool open_container (ContainerType t, const std::string &contained_signature)
bool close_container ()
VariantAppendIterator * sub_iterator ()
Private Attributes
std::shared_ptr< priv_data > m_priv
Detailed Description
Used to append a single, complete value to a Variant.
This is essentially a variant-specific version of MessageAppendIterator
Constructor & Destructor Documentation
VariantAppendIterator() [1/2]
VariantAppendIterator::VariantAppendIterator (Variant * variant, ContainerType t) private
References DBus::default_endianess(), and m_priv.
Referenced by open_container().
VariantAppendIterator() [2/2]
VariantAppendIterator::VariantAppendIterator (Variant * variant)
References DBus::default_endianess(), DBus::Variant::m_marshaled, and m_priv.
~VariantAppendIterator()
VariantAppendIterator::~VariantAppendIterator ()
References m_priv.
Member Function Documentation
close_container()
bool VariantAppendIterator::close_container () private
References DBus::ARRAY, DBus::DICT_ENTRY, m_priv, DBus::Validator::maximum_array_size(), DBus::None, DBus::STRUCT, and DBus::VARIANT.
Referenced by open_container(), and operator<<().
open_container()
bool VariantAppendIterator::open_container (ContainerType t, const std::string & contained_signature) private
References DBus::TypeInfo::alignment(), DBus::ARRAY, DBus::Signature::begin(), close_container(), m_priv, DBus::signature(), DBus::SignatureIterator::type(), and VariantAppendIterator().
Referenced by operator<<().
operator<<() [1/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const bool & v)
References m_priv.
operator<<() [2/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const char * v)
References m_priv.
operator<<() [3/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const double & v)
References m_priv.
operator<<() [4/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const int16_t & v)
References m_priv.
operator<<() [5/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const int32_t & v)
References m_priv.
operator<<() [6/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const int64_t & v)
References m_priv.
operator<<() [7/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const Path & v)
References m_priv.
operator<<() [8/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const Signature & v)
References m_priv.
operator<<() [9/17]
template<typename Key , typename Data > VariantAppendIterator & DBus::priv::VariantAppendIterator::operator<< (const std::map< Key, Data > & dictionary) inline
References DBus::ARRAY, close_container(), DBus::DICT_ENTRY, open_container(), DBus::signature_dict_data(), and sub_iterator().
operator<<() [10/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const std::string & v)
References m_priv.
operator<<() [11/17]
template<typename... T> VariantAppendIterator & DBus::priv::VariantAppendIterator::operator<< (const std::tuple< T... > & tup) inline
References close_container(), open_container(), DBus::signature(), DBus::STRUCT, and sub_iterator().
operator<<() [12/17]
template<typename T > VariantAppendIterator & DBus::priv::VariantAppendIterator::operator<< (const std::vector< T > & v) inline
References DBus::ARRAY, close_container(), open_container(), DBus::signature(), and sub_iterator().
operator<<() [13/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const uint16_t & v)
References m_priv.
operator<<() [14/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const uint32_t & v)
References m_priv.
operator<<() [15/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const uint64_t & v)
References m_priv.
operator<<() [16/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const uint8_t & v)
References m_priv.
operator<<() [17/17]
VariantAppendIterator & VariantAppendIterator::operator<< (const Variant & v)
References DBus::ARRAY, DBus::Signature::begin(), close_container(), DBus::Variant::data_alignment(), DBus::DICT_ENTRY, DBus::Signature::end(), DBus::Variant::m_currentType, m_priv, DBus::Variant::m_signature, DBus::Variant::marshaled(), DBus::SignatureIterator::recurse(), and DBus::Variant::type().
sub_iterator()
VariantAppendIterator * VariantAppendIterator::sub_iterator () private
References m_priv.
Referenced by operator<<().
Member Data Documentation
m_priv
std::shared_ptr<priv_data> DBus::priv::VariantAppendIterator::m_priv private
Referenced by close_container(), open_container(), operator<<(), sub_iterator(), VariantAppendIterator(), and ~VariantAppendIterator().
The documentation for this class was generated from the following files:
variantappenditerator.h
variantappenditerator.cpp