DBus::signal_proxy_simple Class Reference
DBus::signal_proxy_simple Class Reference
#include <signal_proxy_base.h>
Public Types
typedef DBusCxxPointer< signal_proxy_base > pointer
Public Types inherited from DBus::signal_proxy_base
typedef DBusCxxPointer< signal_proxy_base > pointer
Public Types inherited from DBus::signal_base
typedef DBusCxxPointer< signal_base > pointer
Public Member Functions
signal_proxy_simple (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_simple (const std::string &interface, const std::string &name)
signal_proxy_simple (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_simple (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_proxy_simple (const signal_proxy_simple &other)
virtual ~signal_proxy_simple ()
virtual signal_base::pointer clone ()
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Public Member Functions inherited from DBus::signal_proxy_base
signal_proxy_base (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_base (const std::string &interface, const std::string &name)
signal_proxy_base (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_base (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_proxy_base (const signal_proxy_base &other)
virtual ~signal_proxy_base ()
virtual HandlerResult handle_signal (SignalMessage::const_pointer)
sigc::signal< HandlerResult, SignalMessage::const_pointer >::accumulated< MessageHandlerAccumulator > signal_dbus_incoming ()
const std::string & match_rule ()
bool matches (Message::const_pointer msg)
Public Member Functions inherited from DBus::signal_base
virtual ~signal_base ()
DBusCxxPointer< Connection > connection ()
void set_connection (DBusCxxPointer< Connection > connection)
const std::string & sender () const
void set_sender (const std::string &s)
const std::string & interface () const
void set_interface (const std::string &i)
const std::string & name () const
void set_name (const std::string &n)
const Path & path () const
void set_path (const std::string &s)
const std::string & destination () const
void set_destination (const std::string &s)
virtual std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Static Public Member Functions
static pointer create (const std::string &path, const std::string &interface, const std::string &name)
static pointer create (const std::string &interface, const std::string &name)
static pointer create (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
static pointer create (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
static pointer create (const signal_proxy_simple &other)
Additional Inherited Members
Protected Member Functions inherited from DBus::signal_base
signal_base (const std::string &path, const std::string &interface, const std::string &name)
signal_base (const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &path, const std::string &interface, const std::string &name)
signal_base (DBusCxxPointer< Connection > connection, const std::string &interface, const std::string &name)
signal_base (const signal_base &other)
bool handle_dbus_outgoing (Message::const_pointer)
Protected Attributes inherited from DBus::signal_proxy_base
std::string m_match_rule
sigc::signal< HandlerResult, SignalMessage::const_pointer >::accumulated< MessageHandlerAccumulator > m_signal_dbus_incoming
Protected Attributes inherited from DBus::signal_base
DBusCxxWeakPointer< Connection > m_connection
std::string m_sender
Path m_path
std::string m_interface
std::string m_name
std::string m_destination
std::string m_match_rule
Member Typedef Documentation
pointer
typedef DBusCxxPointer<signal_proxy_base> DBus::signal_proxy_simple::pointer
Constructor & Destructor Documentation
signal_proxy_simple() [1/5]
DBus::signal_proxy_simple::signal_proxy_simple (const std::string & path, const std::string & interface, const std::string & name)
Referenced by clone(), and create().
signal_proxy_simple() [2/5]
DBus::signal_proxy_simple::signal_proxy_simple (const std::string & interface, const std::string & name)
signal_proxy_simple() [3/5]
DBus::signal_proxy_simple::signal_proxy_simple (DBusCxxPointer< Connection > connection, const std::string & path, const std::string & interface, const std::string & name)
signal_proxy_simple() [4/5]
DBus::signal_proxy_simple::signal_proxy_simple (DBusCxxPointer< Connection > connection, const std::string & interface, const std::string & name)
signal_proxy_simple() [5/5]
DBus::signal_proxy_simple::signal_proxy_simple (const signal_proxy_simple & other)
~signal_proxy_simple()
DBus::signal_proxy_simple::~signal_proxy_simple () virtual
Member Function Documentation
clone()
signal_base::pointer DBus::signal_proxy_simple::clone () virtual
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Implements DBus::signal_proxy_base.
References signal_proxy_simple().
create() [1/5]
signal_proxy_simple::pointer DBus::signal_proxy_simple::create (const std::string & path, const std::string & interface, const std::string & name) static
References signal_proxy_simple().
Referenced by DBus::Connection::create_signal_proxy().
create() [2/5]
signal_proxy_simple::pointer DBus::signal_proxy_simple::create (const std::string & interface, const std::string & name) static
References signal_proxy_simple().
create() [3/5]
signal_proxy_simple::pointer DBus::signal_proxy_simple::create (DBusCxxPointer< Connection > connection, const std::string & path, const std::string & interface, const std::string & name) static
References signal_proxy_simple().
create() [4/5]
signal_proxy_simple::pointer DBus::signal_proxy_simple::create (DBusCxxPointer< Connection > connection, const std::string & interface, const std::string & name) static
References signal_proxy_simple().
create() [5/5]
signal_proxy_simple::pointer DBus::signal_proxy_simple::create (const signal_proxy_simple & other) static
References signal_proxy_simple().
The documentation for this class was generated from the following files:
signal_proxy_base.h
signal_proxy_base.cpp