dbus-cxx: DBus::Message Class Reference
DBus::Message Class Reference abstract
DBus Messages
This class represents a basic DBus message and also serves as a base class for the specialized message types (call, return, signal, error).
#include <message.h>
Public Member Functions
virtual ~Message ()
bool operator== (const Message &other)
bool is_valid () const
void invalidate ()
operator bool () const
uint32_t serial () const
virtual MessageType type () const =0
void set_auto_start (bool auto_start)
bool auto_start ()
Returns true if the bus is allowed to start an owner for this message's destination if it is not running.
bool set_destination (const std::string &s)
Set the destination of this message.
std::string destination () const
std::string sender () const
Signature signature () const
template<typename T >
MessageIterator operator>> (T &value) const
template<typename T >
MessageAppendIterator operator<< (const T &value)
MessageIterator begin () const
MessageIterator end () const
MessageAppendIterator append ()
bool serialize_to_vector (std::vector< uint8_t > *vec, uint32_t serial) const
Serialize this message to the given vector.
Variant header_field (MessageHeaderFields field) const
Returns the given header field(if it exists), otherwise returns a default constructed variant.
uint8_t flags () const
The message flags, as the marshaled byte.
Variant set_header_field (MessageHeaderFields field, Variant value)
Set the given header field.
Endianess endianess () const
const std::vector< int > & filedescriptors () const
Static Public Member Functions
static std::shared_ptr< Message > create_from_data (uint8_t *data, uint32_t data_len, std::vector< int > fds=std::vector< int >())
Protected Member Functions
Message ()
void append_signature (std::string toappend)
void clear_sig_and_data ()
Clears the signature and the data, so you can re-append data.
void set_flags (uint8_t flags)
Private Member Functions
std::vector< uint8_t > * body ()
const std::vector< uint8_t > * body () const
void add_filedescriptor (int fd)
uint32_t filedescriptors_size () const
int filedescriptor_at_location (int location) const
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Friends
class MessageAppendIterator
class MessageIterator
std::ostream & operator<< (std::ostream &os, const DBus::Message *msg)
Detailed Description
This class represents a basic DBus message and also serves as a base class for the specialized message types (call, return, signal, error).
This class cannot be initialized on its own; create a new Message from one of the subclasses
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
Message()
DBus::Message::Message () protected
~Message()
DBus::Message::~Message () virtual
Member Function Documentation
add_filedescriptor()
void DBus::Message::add_filedescriptor (int fd) private
References set_header_field(), and DBus::Unix_FDs.
append()
MessageAppendIterator DBus::Message::append ()
References MessageAppendIterator.
Referenced by DBus::ErrorMessage::ErrorMessage(), and DBus::ErrorMessage::set_message().
append_signature()
void DBus::Message::append_signature (std::string toappend) protected
References DBus::INVALID, DBus::Signature, DBus::Signature::str(), DBus::Variant::to_signature(), and DBus::Variant::type().
auto_start()
bool DBus::Message::auto_start ()
Returns true if the bus is allowed to start an owner for this message's destination if it is not running.
Returns
References DBUSCXX_MESSAGE_NO_AUTO_START_FLAG.
Referenced by set_auto_start().
begin()
MessageIterator DBus::Message::begin () const
References MessageIterator.
Referenced by DBus::ErrorMessage::message(), and operator>>().
body() [1/2]
std::vector< uint8_t > * DBus::Message::body () private
Referenced by DBus::MessageAppendIterator::MessageAppendIterator().
body() [2/2]
const std::vector< uint8_t > * DBus::Message::body () const private
clear_sig_and_data()
void DBus::Message::clear_sig_and_data () protected
Clears the signature and the data, so you can re-append data.
References DBus::Signature.
Referenced by DBus::ErrorMessage::set_message().
create_from_data()
std::shared_ptr< Message > DBus::Message::create_from_data (uint8_t * data, uint32_t data_len, std::vector< int > fds = std::vector<int>()) static
References DBus::Demarshaling::align(), DBus::Big, DBus::CallMessage::create(), DBus::ErrorMessage::create(), DBus::ReturnMessage::create(), DBus::SignalMessage::create(), DBus::Demarshaling::current_offset(), DBus::Demarshaling::demarshal_uint32_t(), DBus::Demarshaling::demarshal_uint8_t(), DBus::Demarshaling::demarshal_variant(), flags(), DBus::int_to_header_field(), DBus::Invalid, DBus::Little, LOGGER_NAME, serial(), DBus::Demarshaling::set_endianess(), SIMPLELOGGER_DEBUG, SIMPLELOGGER_TRACE, SIMPLELOGGER_WARN, DBus::Variant::to_uint32(), and DBus::Unix_FDs.
Referenced by DBus::priv::SendmsgTransport::readMessage(), and DBus::priv::SimpleTransport::readMessage().
DBUS_CXX_PROPAGATE_CONST()
DBus::Message::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
destination()
std::string DBus::Message::destination () const
References DBus::Destination, header_field(), and DBus::STRING.
end()
MessageIterator DBus::Message::end () const
References MessageIterator.
endianess()
DBus::Endianess DBus::Message::endianess () const
filedescriptor_at_location()
int DBus::Message::filedescriptor_at_location (int location) const private
filedescriptors()
const std::vector< int > & DBus::Message::filedescriptors () const
filedescriptors_size()
uint32_t DBus::Message::filedescriptors_size () const private
flags()
uint8_t DBus::Message::flags () const
The message flags, as the marshaled byte.
Returns
Referenced by DBus::CallMessage::create_error_reply(), create_from_data(), DBus::CallMessage::create_reply(), DBus::CallMessage::expects_reply(), set_flags(), and DBus::CallMessage::set_no_reply().
header_field()
Variant DBus::Message::header_field (MessageHeaderFields field) const
Returns the given header field(if it exists), otherwise returns a default constructed variant.
Parameters
field The field number to get
Returns
The data, otherwise a default-constructed variant.
Referenced by destination(), DBus::CallMessage::interface_name(), DBus::SignalMessage::interface_name(), DBus::CallMessage::member(), DBus::SignalMessage::member(), DBus::ErrorMessage::message(), DBus::ErrorMessage::name(), operator==(), DBus::CallMessage::path(), DBus::SignalMessage::path(), DBus::ErrorMessage::reply_serial(), DBus::ReturnMessage::reply_serial(), sender(), serialize_to_vector(), set_header_field(), and signature().
invalidate()
void DBus::Message::invalidate ()
is_valid()
bool DBus::Message::is_valid () const
Referenced by DBus::CallMessage::create_error_reply(), and DBus::CallMessage::create_reply().
operator bool()
DBus::Message::operator bool () const
operator<<()
template<typename T > MessageAppendIterator DBus::Message::operator<< (const T & value) inline
operator==()
bool DBus::Message::operator== (const Message & other)
References DBus::Destination, DBus::Error_Name, header_field(), DBus::Interface, DBus::Member, DBus::Path, DBus::Reply_Serial, DBus::Sender, DBus::Signature, type(), and DBus::Unix_FDs.
operator>>()
template<typename T > MessageIterator DBus::Message::operator>> (T & value) const inline
References begin().
sender()
std::string DBus::Message::sender () const
References header_field(), DBus::Sender, and DBus::STRING.
Referenced by DBus::CallMessage::create_error_reply(), and DBus::CallMessage::create_reply().
serial()
uint32_t DBus::Message::serial () const
Referenced by DBus::CallMessage::create_error_reply(), create_from_data(), DBus::CallMessage::create_reply(), and serialize_to_vector().
serialize_to_vector()
bool DBus::Message::serialize_to_vector (std::vector< uint8_t > * vec, uint32_t serial) const
Serialize this message to the given vector.
The vector will be resized but not cleared. Can fail with an error under the following circumstances:
Invalid message type passed in
Method return or method call does not have serial set
Parameters
vec The location to serialize the message to.
serial The serial of the message.
Returns
True if the message was able to be serialized, false otherwise.
References DBus::Marshaling::align(), DBus::CALL, DBus::default_endianess(), DBus::ERROR, header_field(), DBus::header_field_to_int(), DBus::INVALID, DBus::Little, LOGGER_NAME, DBus::Marshaling::marshal(), DBus::Marshaling::marshal_at_offset(), DBus::Validator::message_is_small_enough(), DBus::Reply_Serial, DBus::RETURN, serial(), DBus::SIGNAL, SIMPLELOGGER_ERROR, DBus::Variant::to_uint32(), DBus::Variant::type(), type(), and DBus::UINT32.
set_auto_start()
void DBus::Message::set_auto_start (bool auto_start)
References auto_start(), and DBUSCXX_MESSAGE_NO_AUTO_START_FLAG.
set_destination()
bool DBus::Message::set_destination (const std::string & s)
Set the destination of this message.
Parameters
s
Returns
true if the destination was able to be set, false if the destination was unable to be validated
References DBus::Destination, and DBus::Validator::validate_bus_name().
Referenced by DBus::CallMessage::CallMessage().
set_flags()
void DBus::Message::set_flags (uint8_t flags) protected
References flags().
Referenced by DBus::CallMessage::set_no_reply().
set_header_field()
Variant DBus::Message::set_header_field (MessageHeaderFields field, Variant value)
Set the given header field.
Returns the previously set value, if it exists.
Parameters
field The field to set
value The value to set the header field to
Returns
The old value, if it exists.
References header_field().
Referenced by add_filedescriptor(), DBus::ErrorMessage::ErrorMessage(), DBus::CallMessage::set_interface(), DBus::SignalMessage::set_interface(), DBus::CallMessage::set_member(), DBus::SignalMessage::set_member(), DBus::ErrorMessage::set_name(), DBus::CallMessage::set_path(), DBus::SignalMessage::set_path(), DBus::ErrorMessage::set_reply_serial(), and DBus::ReturnMessage::set_reply_serial().
signature()
Signature DBus::Message::signature () const
References header_field(), DBus::SIGNATURE, DBus::Signature, DBus::Variant::to_signature(), and DBus::Variant::type().
Referenced by DBus::ErrorMessage::message().
type()
virtual MessageType DBus::Message::type () const pure virtual
Implemented in DBus::SignalMessage, DBus::ReturnMessage, DBus::ErrorMessage, and DBus::CallMessage.
Referenced by operator==(), and serialize_to_vector().
Friends And Related Function Documentation
MessageAppendIterator
friend class MessageAppendIterator friend
Referenced by append().
MessageIterator
friend class MessageIterator friend
Referenced by begin(), and end().
operator<<
std::ostream& operator<< (std::ostream & os, const DBus::Message * msg) friend
The documentation for this class was generated from the following files:
message.h
message.cpp