DBus::PendingCall Class Reference
DBus::PendingCall Class Reference
DBus Messages
Monitors an asynchronous call, emitting a signal when a response is received.
#include <pendingcall.h>
Inherits trackable.
Public Types
typedef DBusCxxPointer< PendingCall > pointer
Public Member Functions
virtual ~PendingCall ()
PendingCall & operator= (const PendingCall &other)
void cancel ()
bool completed ()
Message::pointer steal_reply ()
void block ()
sigc::signal< void > signal_notify ()
DBusPendingCall * cobj ()
Static Public Member Functions
static pointer create (DBusPendingCall *cobj=NULL)
static pointer create (const PendingCall &)
Protected Member Functions
PendingCall (DBusPendingCall *cobj=NULL)
PendingCall (const PendingCall &)
Static Private Member Functions
static void notify_callback (DBusPendingCall *pending, void *data)
Private Attributes
DBusPendingCall * m_cobj
sigc::signal< void > m_signal_notify
Detailed Description
Monitors an asynchronous call, emitting a signal when a response is received.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
typedef DBusCxxPointer<PendingCall> DBus::PendingCall::pointer
Constructor & Destructor Documentation
PendingCall() [1/2]
DBus::PendingCall::PendingCall (DBusPendingCall * cobj = NULL) protected
References m_cobj, and notify_callback().
Referenced by create().
PendingCall() [2/2]
DBus::PendingCall::PendingCall (const PendingCall & c) protected
References m_cobj.
~PendingCall()
DBus::PendingCall::~PendingCall () virtual
References m_cobj.
Member Function Documentation
block()
void DBus::PendingCall::block ()
References m_cobj.
cancel()
void DBus::PendingCall::cancel ()
References m_cobj.
cobj()
DBusPendingCall* DBus::PendingCall::cobj ()
completed()
bool DBus::PendingCall::completed ()
References m_cobj.
create() [1/2]
PendingCall::pointer DBus::PendingCall::create (DBusPendingCall * cobj = NULL) static
References PendingCall().
Referenced by DBus::Connection::send_with_reply_async().
create() [2/2]
PendingCall::pointer DBus::PendingCall::create (const PendingCall & other) static
References PendingCall().
notify_callback()
void DBus::PendingCall::notify_callback (DBusPendingCall * pending, void * data) static private
References m_signal_notify.
Referenced by PendingCall().
operator=()
PendingCall & DBus::PendingCall::operator= (const PendingCall & other)
References m_cobj.
signal_notify()
sigc::signal< void > DBus::PendingCall::signal_notify ()
References m_signal_notify.
steal_reply()
Message::pointer DBus::PendingCall::steal_reply ()
References DBus::Message::create(), and m_cobj.
Member Data Documentation
m_cobj
DBusPendingCall* DBus::PendingCall::m_cobj private
Referenced by block(), cancel(), completed(), operator=(), PendingCall(), steal_reply(), and ~PendingCall().
m_signal_notify
sigc::signal<void> DBus::PendingCall::m_signal_notify private
Referenced by notify_callback(), and signal_notify().
The documentation for this class was generated from the following files:
pendingcall.h
pendingcall.cpp