dbus-cxx: DBus::DBusDaemonProxy Class Reference
DBus::DBusDaemonProxy Class Reference
#include <DBusDaemonProxy.h>
Public Member Functions
std::string Hello ()
uint32_t RequestName (std::string arg0, uint32_t arg1)
uint32_t ReleaseName (std::string arg0)
uint32_t StartServiceByName (std::string arg0, uint32_t arg1)
void UpdateActivationEnvironment (std::map< std::string, std::string > arg0)
bool NameHasOwner (std::string arg0)
std::vector< std::string > ListNames ()
std::vector< std::string > ListActivatableNames ()
void AddMatch (std::string arg0)
void RemoveMatch (std::string arg0)
std::string GetNameOwner (std::string arg0)
std::vector< std::string > ListQueuedOwners (std::string arg0)
uint32_t GetConnectionUnixUser (std::string arg0)
uint32_t GetConnectionUnixProcessID (std::string arg0)
std::vector< uint8_t > GetAdtAuditSessionData (std::string arg0)
std::vector< uint8_t > GetConnectionSELinuxSecurityContext (std::string arg0)
void ReloadConfig ()
std::string GetId ()
std::map< std::string, DBus::Variant > GetConnectionCredentials (std::string arg0)
std::shared_ptr< DBus::SignalProxy< void(std::string, std::string, std::string)> > signal_NameOwnerChanged ()
std::shared_ptr< DBus::SignalProxy< void(std::string)> > signal_NameLost ()
std::shared_ptr< DBus::SignalProxy< void(std::string)> > signal_NameAcquired ()
DBus::Variant Get (std::string arg0, std::string arg1)
std::map< std::string, DBus::Variant > GetAll (std::string arg0)
void Set (std::string arg0, std::string arg1, DBus::Variant arg2)
std::shared_ptr< DBus::SignalProxy< void(std::string, std::map< std::string, DBus::Variant >, std::vector< std::string >)> > signal_PropertiesChanged ()
std::string Introspect ()
void BecomeMonitor (std::vector< std::string > arg0, uint32_t arg1)
std::map< std::string, DBus::Variant > GetStats ()
std::map< std::string, DBus::Variant > GetConnectionStats (std::string arg0)
std::map< std::string, std::vector< std::string > > GetAllMatchRules ()
std::string GetMachineId ()
void Ping ()
Public Member Functions inherited from DBus::ObjectProxy
virtual ~ObjectProxy ()
std::weak_ptr< Connection > connection () const
void set_connection (std::shared_ptr< Connection > conn)
const std::string & destination () const
void set_destination (const std::string &destination)
const Path & path () const
void set_path (const std::string &path)
const Interfaces & interfaces () const
std::shared_ptr< InterfaceProxy > interface_by_name (const std::string &name) const
Returns the first interface with the given name.
bool add_interface (std::shared_ptr< InterfaceProxy > interface_ptr)
Adds the interface to this object.
std::shared_ptr< InterfaceProxy > create_interface (const std::string &name)
Creates and adds the named interface to this object.
void remove_interface (const std::string &name)
Removes the first interface with the given name.
void remove_interface (std::shared_ptr< InterfaceProxy > interface_ptr)
Removes the given interface.
bool has_interface (const std::string &name) const
bool has_interface (std::shared_ptr< InterfaceProxy > interface_ptr) const
bool add_method (const std::string &interface_name, std::shared_ptr< MethodProxyBase > method)
Adds the method to the named interface.
std::shared_ptr< CallMessage > create_call_message (const std::string &interface_name, const std::string &method_name) const
std::shared_ptr< CallMessage > create_call_message (const std::string &method_name) const
std::shared_ptr< const ReturnMessage > call (std::shared_ptr< const CallMessage >, int timeout_milliseconds=-1) const
Forwards this CallMessage to the Connection that this ObjectProxy is on, and returns a message with the response.
template<class T_type >
std::shared_ptr< MethodProxy< T_type > > create_method (const std::string &interface_name, const std::string &method_name)
Creates a proxy method with a signature based on the template parameters and adds it to the named interface.
template<class T_type >
std::shared_ptr< SignalProxy< T_type > > create_signal (const std::string &interface_name, const std::string &sig_name)
Creates a signal proxy with a signature based on the template parameters and adds it to the named interface.
template<class T_type >
std::shared_ptr< PropertyProxy< T_type > > create_property (const std::string &interface_name, const std::string &property_name, PropertyAccess access_type=PropertyAccess::ReadWrite, PropertyUpdateType update=PropertyUpdateType::Updates)
sigc::signal< void(std::shared_ptr< InterfaceProxy >)> signal_interface_added ()
Return a signal that you may connect to when an interface is added.
sigc::signal< void(std::shared_ptr< InterfaceProxy >)> signal_interface_removed ()
Return a signal that you may connect to when an interface is removed.
std::shared_ptr< PeerInterfaceProxy > getPeerInterface ()
std::shared_ptr< IntrospectableInterfaceProxy > getIntrospectableInterface ()
std::shared_ptr< PropertiesInterfaceProxy > getPropertiesInterface ()
Static Public Member Functions
static std::shared_ptr< DBusDaemonProxy > create (std::shared_ptr< DBus::Connection > conn, std::string dest="org.freedesktop.DBus", std::string path="/org/freedesktop/DBus", DBus::ThreadForCalling signalCallingThread=DBus::ThreadForCalling::DispatcherThread)
Static Public Member Functions inherited from DBus::ObjectProxy
static std::shared_ptr< ObjectProxy > create (const std::string &path)
Creates an ObjectProxy with a specific path.
static std::shared_ptr< ObjectProxy > create (const std::string &destination, const std::string &path)
Creates an ObjectProxy with a specific path.
static std::shared_ptr< ObjectProxy > create (std::shared_ptr< Connection > conn, const std::string &path)
static std::shared_ptr< ObjectProxy > create (std::shared_ptr< Connection > conn, const std::string &destination, const std::string &path)
Protected Member Functions
DBusDaemonProxy (std::shared_ptr< DBus::Connection > conn, std::string dest="org.freedesktop.DBus", std::string path="/org/freedesktop/DBus", DBus::ThreadForCalling signalCallingThread=DBus::ThreadForCalling::DispatcherThread)
Protected Member Functions inherited from DBus::ObjectProxy
ObjectProxy (std::shared_ptr< Connection > conn, const std::string &destination, const std::string &path)
This class has a protected constructor.
Protected Attributes
std::shared_ptr< DBus::MethodProxy< std::string()> > m_method_Hello
std::shared_ptr< DBus::MethodProxy< uint32_t(std::string, uint32_t)> > m_method_RequestName
std::shared_ptr< DBus::MethodProxy< uint32_t(std::string)> > m_method_ReleaseName
std::shared_ptr< DBus::MethodProxy< uint32_t(std::string, uint32_t)> > m_method_StartServiceByName
std::shared_ptr< DBus::MethodProxy< void(std::map< std::string, std::string >)> > m_method_UpdateActivationEnvironment
std::shared_ptr< DBus::MethodProxy< bool(std::string)> > m_method_NameHasOwner
std::shared_ptr< DBus::MethodProxy< std::vector< std::string >)> > m_method_ListNames
std::shared_ptr< DBus::MethodProxy< std::vector< std::string >)> > m_method_ListActivatableNames
std::shared_ptr< DBus::MethodProxy< void(std::string)> > m_method_AddMatch
std::shared_ptr< DBus::MethodProxy< void(std::string)> > m_method_RemoveMatch
std::shared_ptr< DBus::MethodProxy< std::string(std::string)> > m_method_GetNameOwner
std::shared_ptr< DBus::MethodProxy< std::vector< std::string > std::string)> > m_method_ListQueuedOwners
std::shared_ptr< DBus::MethodProxy< uint32_t(std::string)> > m_method_GetConnectionUnixUser
std::shared_ptr< DBus::MethodProxy< uint32_t(std::string)> > m_method_GetConnectionUnixProcessID
std::shared_ptr< DBus::MethodProxy< std::vector< uint8_t > std::string)> > m_method_GetAdtAuditSessionData
std::shared_ptr< DBus::MethodProxy< std::vector< uint8_t > std::string)> > m_method_GetConnectionSELinuxSecurityContext
std::shared_ptr< DBus::MethodProxy< void()> > m_method_ReloadConfig
std::shared_ptr< DBus::MethodProxy< std::string()> > m_method_GetId
std::shared_ptr< DBus::MethodProxy< std::map< std::string, DBus::Variant > std::string)> > m_method_GetConnectionCredentials
std::shared_ptr< DBus::SignalProxy< void(std::string, std::string, std::string)> > m_signalproxy_NameOwnerChanged
std::shared_ptr< DBus::SignalProxy< void(std::string)> > m_signalproxy_NameLost
std::shared_ptr< DBus::SignalProxy< void(std::string)> > m_signalproxy_NameAcquired
std::shared_ptr< DBus::MethodProxy< DBus::Variant(std::string, std::string)> > m_method_Get
std::shared_ptr< DBus::MethodProxy< std::map< std::string, DBus::Variant > std::string)> > m_method_GetAll
std::shared_ptr< DBus::MethodProxy< void(std::string, std::string, DBus::Variant)> > m_method_Set
std::shared_ptr< DBus::SignalProxy< void(std::string, std::map< std::string, DBus::Variant >, std::vector< std::string >)> > m_signalproxy_PropertiesChanged
std::shared_ptr< DBus::MethodProxy< std::string()> > m_method_Introspect
std::shared_ptr< DBus::MethodProxy< void(std::vector< std::string >, uint32_t)> > m_method_BecomeMonitor
std::shared_ptr< DBus::MethodProxy< std::map< std::string, DBus::Variant >)> > m_method_GetStats
std::shared_ptr< DBus::MethodProxy< std::map< std::string, DBus::Variant > std::string)> > m_method_GetConnectionStats
std::shared_ptr< DBus::MethodProxy< std::map< std::string, std::vector< std::string > >)> > m_method_GetAllMatchRules
std::shared_ptr< DBus::MethodProxy< std::string()> > m_method_GetMachineId
std::shared_ptr< DBus::MethodProxy< void()> > m_method_Ping
Additional Inherited Members
Public Types inherited from DBus::ObjectProxy
typedef std::map< std::string, std::shared_ptr< InterfaceProxy > > Interfaces
Constructor & Destructor Documentation
DBusDaemonProxy()
DBusDaemonProxy::DBusDaemonProxy (std::shared_ptr< DBus::Connection > conn, std::string dest = "org.freedesktop.DBus", std::string path = "/org/freedesktop/DBus", DBus::ThreadForCalling signalCallingThread = DBus::ThreadForCalling::DispatcherThread) protected
References m_method_AddMatch, m_method_BecomeMonitor, m_method_Get, m_method_GetAdtAuditSessionData, m_method_GetAll, m_method_GetAllMatchRules, m_method_GetConnectionCredentials, m_method_GetConnectionSELinuxSecurityContext, m_method_GetConnectionStats, m_method_GetConnectionUnixProcessID, m_method_GetConnectionUnixUser, m_method_GetId, m_method_GetMachineId, m_method_GetNameOwner, m_method_GetStats, m_method_Hello, m_method_Introspect, m_method_ListActivatableNames, m_method_ListNames, m_method_ListQueuedOwners, m_method_NameHasOwner, m_method_Ping, m_method_ReleaseName, m_method_ReloadConfig, m_method_RemoveMatch, m_method_RequestName, m_method_Set, m_method_StartServiceByName, m_method_UpdateActivationEnvironment, m_signalproxy_NameAcquired, m_signalproxy_NameLost, m_signalproxy_NameOwnerChanged, and m_signalproxy_PropertiesChanged.
Referenced by create().
Member Function Documentation
AddMatch()
void DBusDaemonProxy::AddMatch (std::string arg0)
BecomeMonitor()
void DBusDaemonProxy::BecomeMonitor (std::vector< std::string > arg0, uint32_t arg1)
create()
std::shared_ptr< DBusDaemonProxy > DBusDaemonProxy::create (std::shared_ptr< DBus::Connection > conn, std::string dest = "org.freedesktop.DBus", std::string path = "/org/freedesktop/DBus", DBus::ThreadForCalling signalCallingThread = DBus::ThreadForCalling::DispatcherThread) static
References DBusDaemonProxy().
Referenced by DBus::Connection::bus_register().
Get()
DBus::Variant DBusDaemonProxy::Get (std::string arg0, std::string arg1)
References m_method_Get.
GetAdtAuditSessionData()
std::vector< uint8_t > DBusDaemonProxy::GetAdtAuditSessionData (std::string arg0)
References m_method_GetAdtAuditSessionData.
GetAll()
std::map< std::string, DBus::Variant > DBusDaemonProxy::GetAll (std::string arg0)
References m_method_GetAll.
GetAllMatchRules()
std::map< std::string, std::vector< std::string > > DBusDaemonProxy::GetAllMatchRules ()
References m_method_GetAllMatchRules.
GetConnectionCredentials()
std::map< std::string, DBus::Variant > DBusDaemonProxy::GetConnectionCredentials (std::string arg0)
References m_method_GetConnectionCredentials.
GetConnectionSELinuxSecurityContext()
std::vector< uint8_t > DBusDaemonProxy::GetConnectionSELinuxSecurityContext (std::string arg0)
References m_method_GetConnectionSELinuxSecurityContext.
GetConnectionStats()
std::map< std::string, DBus::Variant > DBusDaemonProxy::GetConnectionStats (std::string arg0)
References m_method_GetConnectionStats.
GetConnectionUnixProcessID()
uint32_t DBusDaemonProxy::GetConnectionUnixProcessID (std::string arg0)
References m_method_GetConnectionUnixProcessID.
GetConnectionUnixUser()
uint32_t DBusDaemonProxy::GetConnectionUnixUser (std::string arg0)
References m_method_GetConnectionUnixUser.
GetId()
std::string DBusDaemonProxy::GetId ()
References m_method_GetId.
GetMachineId()
std::string DBusDaemonProxy::GetMachineId ()
References m_method_GetMachineId.
GetNameOwner()
std::string DBusDaemonProxy::GetNameOwner (std::string arg0)
References m_method_GetNameOwner.
GetStats()
std::map< std::string, DBus::Variant > DBusDaemonProxy::GetStats ()
References m_method_GetStats.
Hello()
std::string DBusDaemonProxy::Hello ()
References m_method_Hello.
Introspect()
std::string DBusDaemonProxy::Introspect ()
References m_method_Introspect.
ListActivatableNames()
std::vector< std::string > DBusDaemonProxy::ListActivatableNames ()
References m_method_ListActivatableNames.
ListNames()
std::vector< std::string > DBusDaemonProxy::ListNames ()
References m_method_ListNames.
ListQueuedOwners()
std::vector< std::string > DBusDaemonProxy::ListQueuedOwners (std::string arg0)
References m_method_ListQueuedOwners.
NameHasOwner()
bool DBusDaemonProxy::NameHasOwner (std::string arg0)
References m_method_NameHasOwner.
Ping()
void DBusDaemonProxy::Ping ()
ReleaseName()
uint32_t DBusDaemonProxy::ReleaseName (std::string arg0)
References m_method_ReleaseName.
ReloadConfig()
void DBusDaemonProxy::ReloadConfig ()
RemoveMatch()
void DBusDaemonProxy::RemoveMatch (std::string arg0)
RequestName()
uint32_t DBusDaemonProxy::RequestName (std::string arg0, uint32_t arg1)
References m_method_RequestName.
Set()
void DBusDaemonProxy::Set (std::string arg0, std::string arg1, DBus::Variant arg2)
signal_NameAcquired()
std::shared_ptr< DBus::SignalProxy< void(std::string)> > DBusDaemonProxy::signal_NameAcquired ()
References m_signalproxy_NameAcquired.
signal_NameLost()
std::shared_ptr< DBus::SignalProxy< void(std::string)> > DBusDaemonProxy::signal_NameLost ()
References m_signalproxy_NameLost.
signal_NameOwnerChanged()
std::shared_ptr< DBus::SignalProxy< void(std::string, std::string, std::string)> > DBusDaemonProxy::signal_NameOwnerChanged ()
References m_signalproxy_NameOwnerChanged.
signal_PropertiesChanged()
std::shared_ptr< DBus::SignalProxy< void(std::string, std::map< std::string, DBus::Variant >, std::vector< std::string >)> > DBusDaemonProxy::signal_PropertiesChanged ()
References m_signalproxy_PropertiesChanged.
StartServiceByName()
uint32_t DBusDaemonProxy::StartServiceByName (std::string arg0, uint32_t arg1)
References m_method_StartServiceByName.
UpdateActivationEnvironment()
void DBusDaemonProxy::UpdateActivationEnvironment (std::map< std::string, std::string > arg0)
Member Data Documentation
m_method_AddMatch
std::shared_ptr<DBus::MethodProxy<void(std::string)> > DBus::DBusDaemonProxy::m_method_AddMatch protected
Referenced by DBusDaemonProxy().
m_method_BecomeMonitor
std::shared_ptr<DBus::MethodProxy<void(std::vector<std::string>, uint32_t)> > DBus::DBusDaemonProxy::m_method_BecomeMonitor protected
Referenced by DBusDaemonProxy().
m_method_Get
std::shared_ptr<DBus::MethodProxy<DBus::Variant(std::string, std::string)> > DBus::DBusDaemonProxy::m_method_Get protected
Referenced by DBusDaemonProxy(), and Get().
m_method_GetAdtAuditSessionData
std::shared_ptr<DBus::MethodProxy<std::vector<uint8_t> std::string)> > DBus::DBusDaemonProxy::m_method_GetAdtAuditSessionData protected
Referenced by DBusDaemonProxy(), and GetAdtAuditSessionData().
m_method_GetAll
std::shared_ptr<DBus::MethodProxy<std::map<std::string, DBus::Variant> std::string)> > DBus::DBusDaemonProxy::m_method_GetAll protected
Referenced by DBusDaemonProxy(), and GetAll().
m_method_GetAllMatchRules
std::shared_ptr<DBus::MethodProxy<std::map<std::string, std::vector<std::string> >)> > DBus::DBusDaemonProxy::m_method_GetAllMatchRules protected
Referenced by DBusDaemonProxy(), and GetAllMatchRules().
m_method_GetConnectionCredentials
std::shared_ptr<DBus::MethodProxy<std::map<std::string, DBus::Variant> std::string)> > DBus::DBusDaemonProxy::m_method_GetConnectionCredentials protected
Referenced by DBusDaemonProxy(), and GetConnectionCredentials().
m_method_GetConnectionSELinuxSecurityContext
std::shared_ptr<DBus::MethodProxy<std::vector<uint8_t> std::string)> > DBus::DBusDaemonProxy::m_method_GetConnectionSELinuxSecurityContext protected
Referenced by DBusDaemonProxy(), and GetConnectionSELinuxSecurityContext().
m_method_GetConnectionStats
std::shared_ptr<DBus::MethodProxy<std::map<std::string, DBus::Variant> std::string)> > DBus::DBusDaemonProxy::m_method_GetConnectionStats protected
Referenced by DBusDaemonProxy(), and GetConnectionStats().
m_method_GetConnectionUnixProcessID
std::shared_ptr<DBus::MethodProxy<uint32_t(std::string)> > DBus::DBusDaemonProxy::m_method_GetConnectionUnixProcessID protected
Referenced by DBusDaemonProxy(), and GetConnectionUnixProcessID().
m_method_GetConnectionUnixUser
std::shared_ptr<DBus::MethodProxy<uint32_t(std::string)> > DBus::DBusDaemonProxy::m_method_GetConnectionUnixUser protected
Referenced by DBusDaemonProxy(), and GetConnectionUnixUser().
m_method_GetId
std::shared_ptr<DBus::MethodProxy<std::string()> > DBus::DBusDaemonProxy::m_method_GetId protected
Referenced by DBusDaemonProxy(), and GetId().
m_method_GetMachineId
std::shared_ptr<DBus::MethodProxy<std::string()> > DBus::DBusDaemonProxy::m_method_GetMachineId protected
Referenced by DBusDaemonProxy(), and GetMachineId().
m_method_GetNameOwner
std::shared_ptr<DBus::MethodProxy<std::string(std::string)> > DBus::DBusDaemonProxy::m_method_GetNameOwner protected
Referenced by DBusDaemonProxy(), and GetNameOwner().
m_method_GetStats
std::shared_ptr<DBus::MethodProxy<std::map<std::string, DBus::Variant>)> > DBus::DBusDaemonProxy::m_method_GetStats protected
Referenced by DBusDaemonProxy(), and GetStats().
m_method_Hello
std::shared_ptr<DBus::MethodProxy<std::string()> > DBus::DBusDaemonProxy::m_method_Hello protected
Referenced by DBusDaemonProxy(), and Hello().
m_method_Introspect
std::shared_ptr<DBus::MethodProxy<std::string()> > DBus::DBusDaemonProxy::m_method_Introspect protected
Referenced by DBusDaemonProxy(), and Introspect().
m_method_ListActivatableNames
std::shared_ptr<DBus::MethodProxy<std::vector<std::string>)> > DBus::DBusDaemonProxy::m_method_ListActivatableNames protected
Referenced by DBusDaemonProxy(), and ListActivatableNames().
m_method_ListNames
std::shared_ptr<DBus::MethodProxy<std::vector<std::string>)> > DBus::DBusDaemonProxy::m_method_ListNames protected
Referenced by DBusDaemonProxy(), and ListNames().
m_method_ListQueuedOwners
std::shared_ptr<DBus::MethodProxy<std::vector<std::string> std::string)> > DBus::DBusDaemonProxy::m_method_ListQueuedOwners protected
Referenced by DBusDaemonProxy(), and ListQueuedOwners().
m_method_NameHasOwner
std::shared_ptr<DBus::MethodProxy<bool(std::string)> > DBus::DBusDaemonProxy::m_method_NameHasOwner protected
Referenced by DBusDaemonProxy(), and NameHasOwner().
m_method_Ping
std::shared_ptr<DBus::MethodProxy<void()> > DBus::DBusDaemonProxy::m_method_Ping protected
Referenced by DBusDaemonProxy().
m_method_ReleaseName
std::shared_ptr<DBus::MethodProxy<uint32_t(std::string)> > DBus::DBusDaemonProxy::m_method_ReleaseName protected
Referenced by DBusDaemonProxy(), and ReleaseName().
m_method_ReloadConfig
std::shared_ptr<DBus::MethodProxy<void()> > DBus::DBusDaemonProxy::m_method_ReloadConfig protected
Referenced by DBusDaemonProxy().
m_method_RemoveMatch
std::shared_ptr<DBus::MethodProxy<void(std::string)> > DBus::DBusDaemonProxy::m_method_RemoveMatch protected
Referenced by DBusDaemonProxy().
m_method_RequestName
std::shared_ptr<DBus::MethodProxy<uint32_t(std::string, uint32_t)> > DBus::DBusDaemonProxy::m_method_RequestName protected
Referenced by DBusDaemonProxy(), and RequestName().
m_method_Set
std::shared_ptr<DBus::MethodProxy<void(std::string, std::string, DBus::Variant)> > DBus::DBusDaemonProxy::m_method_Set protected
Referenced by DBusDaemonProxy().
m_method_StartServiceByName
std::shared_ptr<DBus::MethodProxy<uint32_t(std::string, uint32_t)> > DBus::DBusDaemonProxy::m_method_StartServiceByName protected
Referenced by DBusDaemonProxy(), and StartServiceByName().
m_method_UpdateActivationEnvironment
std::shared_ptr<DBus::MethodProxy<void(std::map<std::string, std::string>)> > DBus::DBusDaemonProxy::m_method_UpdateActivationEnvironment protected
Referenced by DBusDaemonProxy().
m_signalproxy_NameAcquired
std::shared_ptr<DBus::SignalProxy<void(std::string)> > DBus::DBusDaemonProxy::m_signalproxy_NameAcquired protected
Referenced by DBusDaemonProxy(), and signal_NameAcquired().
m_signalproxy_NameLost
std::shared_ptr<DBus::SignalProxy<void(std::string)> > DBus::DBusDaemonProxy::m_signalproxy_NameLost protected
Referenced by DBusDaemonProxy(), and signal_NameLost().
m_signalproxy_NameOwnerChanged
std::shared_ptr<DBus::SignalProxy<void(std::string, std::string, std::string)> > DBus::DBusDaemonProxy::m_signalproxy_NameOwnerChanged protected
Referenced by DBusDaemonProxy(), and signal_NameOwnerChanged().
m_signalproxy_PropertiesChanged
std::shared_ptr<DBus::SignalProxy<void(std::string, std::map<std::string, DBus::Variant>, std::vector<std::string>)> > DBus::DBusDaemonProxy::m_signalproxy_PropertiesChanged protected
Referenced by DBusDaemonProxy(), and signal_PropertiesChanged().
The documentation for this class was generated from the following files:
DBusDaemonProxy.h
DBusDaemonProxy.cpp