dbus-cxx: DBus::SignalBase Class Reference
DBus::SignalBase Class Reference
Signals | Local Objects
Base class of all signals(proxy and adapter).
#include <signalbase.h>
Public Member Functions
virtual ~SignalBase ()
std::shared_ptr< Connection > connection ()
void set_connection (std::weak_ptr< Connection > connection)
const std::string & sender () const
void set_sender (const std::string &s)
const std::string & interface_name () const
void set_interface (const std::string &i)
const std::string & name () const
void set_name (const std::string &n)
const Path & path () const
void set_path (const std::string &s)
const std::string & destination () const
void set_destination (const std::string &s)
virtual std::string introspect (int space_depth=0) const
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
virtual std::string arg_name (size_t i)
virtual void set_arg_name (size_t i, const std::string &name)
Protected Member Functions
SignalBase (const std::string &path, const std::string &interface_name, const std::string &name)
SignalBase (const std::string &interface_name, const std::string &name)
SignalBase (std::weak_ptr< Connection > connection, const std::string &path, const std::string &interface_name, const std::string &name)
SignalBase (std::weak_ptr< Connection > connection, const std::string &interface_name, const std::string &name)
bool handle_dbus_outgoing (std::shared_ptr< const Message >)
Private Member Functions
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Detailed Description
Base class of all signals(proxy and adapter).
This is required to interact with signals in a generic manner, as the actual signal implementation class is templated.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
SignalBase() [1/4]
DBus::SignalBase::SignalBase (const std::string & path, const std::string & interface_name, const std::string & name) protected
References interface_name(), name(), and path().
SignalBase() [2/4]
DBus::SignalBase::SignalBase (const std::string & interface_name, const std::string & name) protected
References interface_name(), and name().
SignalBase() [3/4]
DBus::SignalBase::SignalBase (std::weak_ptr< Connection > connection, const std::string & path, const std::string & interface_name, const std::string & name) protected
References connection(), interface_name(), name(), and path().
SignalBase() [4/4]
DBus::SignalBase::SignalBase (std::weak_ptr< Connection > connection, const std::string & interface_name, const std::string & name) protected
References connection(), interface_name(), and name().
~SignalBase()
DBus::SignalBase::~SignalBase () virtual
Member Function Documentation
arg_name()
virtual std::string DBus::SignalBase::arg_name (size_t i) inline virtual
Reimplemented in DBus::Signal< void(T_type...)>.
connection()
std::shared_ptr< Connection > DBus::SignalBase::connection ()
Referenced by SignalBase().
DBUS_CXX_PROPAGATE_CONST()
DBus::SignalBase::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
destination()
const std::string & DBus::SignalBase::destination () const
Referenced by DBus::SignalProxyBase::matches().
handle_dbus_outgoing()
bool DBus::SignalBase::handle_dbus_outgoing (std::shared_ptr< const Message > msg) protected
interface_name()
const std::string & DBus::SignalBase::interface_name () const
Referenced by DBus::SignalProxyBase::matches(), SignalBase(), and DBus::SignalProxyBase::update_match_rule().
introspect()
virtual std::string DBus::SignalBase::introspect (int space_depth = 0) const inline virtual
This method is needed to be able to create a duplicate of a child capable of parsing their specific template type message.
Returns a DBus XML description of this interface
Reimplemented in DBus::Signal< void(T_type...)>.
name()
const std::string & DBus::SignalBase::name () const
Referenced by DBus::SignalProxyBase::matches(), SignalBase(), and DBus::SignalProxyBase::update_match_rule().
path()
const Path & DBus::SignalBase::path () const
Referenced by DBus::SignalProxyBase::matches(), SignalBase(), and DBus::SignalProxyBase::update_match_rule().
sender()
const std::string & DBus::SignalBase::sender () const
Referenced by DBus::SignalProxyBase::matches().
set_arg_name()
virtual void DBus::SignalBase::set_arg_name (size_t i, const std::string & name) inline virtual
Reimplemented in DBus::Signal< void(T_type...)>.
set_connection()
void DBus::SignalBase::set_connection (std::weak_ptr< Connection > connection)
set_destination()
void DBus::SignalBase::set_destination (const std::string & s)
set_interface()
void DBus::SignalBase::set_interface (const std::string & i)
set_name()
void DBus::SignalBase::set_name (const std::string & n)
set_path()
void DBus::SignalBase::set_path (const std::string & s)
set_sender()
void DBus::SignalBase::set_sender (const std::string & s)
The documentation for this class was generated from the following files:
signalbase.h
signalbase.cpp