dbus-cxx: DBus::TypeInfo Class Reference
DBus::TypeInfo Class Reference
Contains useful data about the type in order for code generation to happen in an easy manner.
#include <types.h>
Public Member Functions
TypeInfo (DataType d)
The type to get info for.
bool isTemplated () const
Returns true if this type is templated.
std::vector< std::string > includeFilesForType () const
Returns the needed includes in order to use this type.
std::string cppType () const
Returns the C++ type of this DataType.
bool is_basic () const
True if the element type is a basic type.
bool is_fixed () const
True if the element type is a fixed type.
bool is_container () const
True if the element type is a container.
int32_t alignment () const
Return the alignment of the type.
char to_dbus_char () const
Turn this type into a DBus char.
Private Attributes
DataType m_type
Detailed Description
Contains useful data about the type in order for code generation to happen in an easy manner.
Constructor & Destructor Documentation
TypeInfo()
DBus::TypeInfo::TypeInfo (DataType d)
The type to get info for.
Member Function Documentation
alignment()
int32_t DBus::TypeInfo::alignment () const
Return the alignment of the type.
Returns
References DBus::ARRAY, DBus::BOOLEAN, DBus::BYTE, DBus::DICT_ENTRY, DBus::DOUBLE, DBus::INT16, DBus::INT32, DBus::INT64, m_type, DBus::OBJECT_PATH, DBus::SIGNATURE, DBus::STRING, DBus::STRUCT, DBus::UINT16, DBus::UINT32, DBus::UINT64, DBus::UNIX_FD, and DBus::VARIANT.
Referenced by DBus::Variant::createFromDemarshal(), DBus::MessageAppendIterator::open_container(), DBus::priv::VariantAppendIterator::open_container(), DBus::Variant::recurseArray(), and DBus::Variant::remarshal().
cppType()
std::string DBus::TypeInfo::cppType () const
Returns the C++ type of this DataType.
References DBus::ARRAY, DBus::BOOLEAN, DBus::BYTE, DBus::DICT_ENTRY, DBus::DOUBLE, DBus::INT16, DBus::INT32, DBus::INT64, DBus::INVALID, m_type, DBus::OBJECT_PATH, DBus::SIGNATURE, DBus::STRING, DBus::STRUCT, DBus::UINT16, DBus::UINT32, DBus::UINT64, DBus::UNIX_FD, and DBus::VARIANT.
includeFilesForType()
std::vector< std::string > DBus::TypeInfo::includeFilesForType () const
Returns the needed includes in order to use this type.
References DBus::ARRAY, DBus::BYTE, DBus::DICT_ENTRY, DBus::INT16, DBus::INT32, DBus::INT64, m_type, DBus::STRING, DBus::STRUCT, DBus::UINT16, DBus::UINT32, DBus::UINT64, and DBus::VARIANT.
is_basic()
bool DBus::TypeInfo::is_basic () const
True if the element type is a basic type.
References DBus::BYTE, DBus::INT16, DBus::INT32, DBus::INT64, m_type, DBus::OBJECT_PATH, DBus::SIGNATURE, DBus::STRING, DBus::UINT16, DBus::UINT32, DBus::UINT64, and DBus::UNIX_FD.
Referenced by DBus::Signature::create_signature_tree(), and DBus::SignatureIterator::is_basic().
is_container()
bool DBus::TypeInfo::is_container () const
True if the element type is a container.
References DBus::ARRAY, DBus::DICT_ENTRY, m_type, DBus::STRUCT, and DBus::VARIANT.
Referenced by DBus::Signature::create_signature_tree(), DBus::MessageIterator::is_container(), DBus::SignatureIterator::is_container(), and DBus::priv::VariantIterator::is_container().
is_fixed()
bool DBus::TypeInfo::is_fixed () const
True if the element type is a fixed type.
References DBus::BYTE, DBus::INT16, DBus::INT32, DBus::INT64, m_type, DBus::UINT16, DBus::UINT32, and DBus::UINT64.
Referenced by DBus::MessageIterator::is_fixed(), DBus::SignatureIterator::is_fixed(), and DBus::priv::VariantIterator::is_fixed().
isTemplated()
bool DBus::TypeInfo::isTemplated () const
Returns true if this type is templated.
References DBus::ARRAY, DBus::DICT_ENTRY, m_type, and DBus::STRUCT.
to_dbus_char()
char DBus::TypeInfo::to_dbus_char () const
Turn this type into a DBus char.
Returns
References DBus::ARRAY, DBus::BOOLEAN, DBus::BYTE, DBus::DOUBLE, DBus::INT16, DBus::INT32, DBus::INT64, DBus::INVALID, m_type, DBus::OBJECT_PATH, DBus::SIGNATURE, DBus::STRING, DBus::UINT16, DBus::UINT32, DBus::UINT64, DBus::UNIX_FD, and DBus::VARIANT.
Referenced by DBus::SignatureIterator::iterate_over_subsig(), and DBus::SignatureIterator::signature().
Member Data Documentation
m_type
DataType DBus::TypeInfo::m_type private
Referenced by alignment(), cppType(), includeFilesForType(), is_basic(), is_container(), is_fixed(), isTemplated(), and to_dbus_char().
The documentation for this class was generated from the following files:
types.h
types.cpp