DBus::MethodProxyBase Class Reference
DBus::MethodProxyBase Class Reference
Objects | Proxy
#include <methodproxybase.h>
Public Types
typedef DBusCxxPointer< MethodProxyBase > pointer
Public Member Functions
~MethodProxyBase ()
InterfaceProxy * interface () const
const std::string & name () const
void set_name (const std::string &name)
CallMessage::pointer create_call_message () const
ReturnMessage::const_pointer call (CallMessage::const_pointer, int timeout_milliseconds=-1) const
PendingCall::pointer call_async (CallMessage::const_pointer, int timeout_milliseconds=-1) const
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Static Public Member Functions
static pointer create (const std::string &name)
Protected Member Functions
MethodProxyBase (const std::string &name)
MethodProxyBase (const MethodProxyBase &other)
Protected Attributes
InterfaceProxy * m_interface
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
Friends
class InterfaceProxy
Detailed Description
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
typedef DBusCxxPointer<MethodProxyBase> DBus::MethodProxyBase::pointer
Constructor & Destructor Documentation
MethodProxyBase() [1/2]
DBus::MethodProxyBase::MethodProxyBase (const std::string & name) protected
References m_name_mutex.
Referenced by create().
MethodProxyBase() [2/2]
DBus::MethodProxyBase::MethodProxyBase (const MethodProxyBase & other) protected
References m_name_mutex.
~MethodProxyBase()
DBus::MethodProxyBase::~MethodProxyBase ()
References m_name_mutex.
Member Function Documentation
call()
ReturnMessage::const_pointer DBus::MethodProxyBase::call (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_interface.
Referenced by DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), and DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()().
call_async()
PendingCall::pointer DBus::MethodProxyBase::call_async (CallMessage::const_pointer call_message, int timeout_milliseconds = -1) const
References m_interface.
create()
MethodProxyBase::pointer DBus::MethodProxyBase::create (const std::string & name) static
References MethodProxyBase().
create_call_message()
CallMessage::pointer DBus::MethodProxyBase::create_call_message () const
References m_interface, and m_name.
Referenced by DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), and DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()().
interface()
InterfaceProxy * DBus::MethodProxyBase::interface () const
References m_interface.
name()
const std::string & DBus::MethodProxyBase::name () const
References m_name.
Referenced by set_name().
set_name()
void DBus::MethodProxyBase::set_name (const std::string & name)
References m_name, m_name_mutex, m_signal_name_changed, and name().
signal_name_changed()
sigc::signal< void, const std::string &, const std::string &> DBus::MethodProxyBase::signal_name_changed ()
References m_signal_name_changed.
Friends And Related Function Documentation
InterfaceProxy
friend class InterfaceProxy friend
Member Data Documentation
m_interface
InterfaceProxy* DBus::MethodProxyBase::m_interface protected
Referenced by call(), call_async(), create_call_message(), and interface().
m_name
std::string DBus::MethodProxyBase::m_name protected
Referenced by create_call_message(), name(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::operator()(), DBus::MethodProxy< T_return, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), DBus::MethodProxy< void, nil, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, nil, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, nil, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil >::operator()(), DBus::MethodProxy< void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil >::operator()(), and set_name().
m_name_mutex
pthread_mutex_t DBus::MethodProxyBase::m_name_mutex protected
Ensures that the name doesn't change while the name changed signal is emitting.
Referenced by MethodProxyBase(), set_name(), and ~MethodProxyBase().
m_signal_name_changed
sigc::signal<void,const std::string&, const std::string&> DBus::MethodProxyBase::m_signal_name_changed protected
Referenced by set_name(), and signal_name_changed().
The documentation for this class was generated from the following files:
methodproxybase.h
methodproxybase.cpp