DBus::Connection Class Reference
DBus::Connection Class Reference
Connection point to the DBus.
#include <connection.h>
Public Types
typedef DBusCxxPointer< Connection > pointer
typedef DBusCxxWeakPointer< Connection > weak_pointer
typedef sigc::signal1< bool, Watch::pointer, InterruptablePredicateAccumulatorDefaultFalse > AddWatchSignal
typedef sigc::signal1< bool, Timeout::pointer, InterruptablePredicateAccumulatorDefaultFalse > AddTimeoutSignal
typedef std::deque< Watch::pointer > Watches
typedef std::list< signal_proxy_base::pointer > ProxySignals
typedef std::map< std::string, ProxySignals > NameToProxySignalMap
typedef std::map< std::string, NameToProxySignalMap > InterfaceToNameProxySignalMap
Public Member Functions
virtual ~Connection ()
operator bool () const
True if this is a valid connection; false otherwise.
bool is_valid () const
True if this is a valid connection; false otherwise.
bool is_private () const
True if this is a valid connection and is private; false otherwise.
bool bus_register ()
Registers this connection with the bus.
bool is_registered () const
True if this connection is already registered.
const char * unique_name () const
Gets the unique name of the connection as assigned by the message bus.
unsigned long unix_user (const std::string &name) const
The unix user id associated with the name connection or -1 if an error occurred.
const char * bus_id () const
The bus' globally unique ID, as described in the D-Bus specification.
int request_name (const std::string &name, unsigned int flags=0)
int release_name (const std::string &name)
bool name_has_owner (const std::string &name) const
StartReply start_service (const std::string &name, uint32_t flags) const
bool add_match (const std::string &rule)
void add_match_nonblocking (const std::string &rule)
bool remove_match (const std::string &rule)
void remove_match_nonblocking (const std::string &rule)
bool is_connected () const
bool is_authenticated () const
bool is_anonymous () const
const char * server_id () const
uint32_t send (const Message::const_pointer)
Connection & operator<< (Message::const_pointer msg)
Sends the message on the connection.
PendingCall::pointer send_with_reply_async (Message::const_pointer message, int timeout_milliseconds=-1) const
ReturnMessage::const_pointer send_with_reply_blocking (Message::const_pointer msg, int timeout_milliseconds=-1) const
void flush ()
bool read_write_dispatch (int timeout_milliseconds=-1)
bool read_write (int timeout_milliseconds=-1)
Message::pointer borrow_message ()
void return_message (Message::pointer message)
void steal_borrowed_message (Message::pointer message)
Message::pointer pop_message ()
DispatchStatus dispatch_status () const
DispatchStatus dispatch ()
int unix_fd () const
int socket () const
unsigned long unix_user () const
unsigned long unix_process_id () const
void set_allow_anonymous (bool allow=true)
void set_route_peer_messages (bool route=true)
void set_max_message_size (long size)
long max_message_size ()
void set_max_received_size (long size)
long max_received_size ()
long outgoing_size ()
bool has_messages_to_send ()
AddWatchSignal & signal_add_watch ()
Cannot call watch.handle() in a slot connected to this signal.
sigc::signal< bool, Watch::pointer > & signal_remove_watch ()
sigc::signal< void, Watch::pointer > & signal_watch_toggled ()
AddTimeoutSignal & signal_add_timeout ()
Cannot call timeout.handle() in a slot connected to this signal.
sigc::signal< bool, Timeout::pointer > & signal_remove_timeout ()
sigc::signal< bool, Timeout::pointer > & signal_timeout_toggled ()
sigc::signal< void > & signal_wakeup_main ()
sigc::signal< void, DispatchStatus > & signal_dispatch_status_changed ()
Cannot call dispatch() in a slot connected to this signal.
FilterSignal & signal_filter ()
Signal emitted during dispatch.
const Watches & unhandled_watches () const
void remove_unhandled_watch (const Watch::pointer w)
Object::pointer create_object (const std::string &path, PrimaryFallback pf=PRIMARY)
bool register_object (Object::pointer object)
ObjectPathHandler::pointer create_object (const std::string &path, sigc::slot< HandlerResult, Connection::pointer, Message::const_pointer > &slot, PrimaryFallback pf=PRIMARY)
ObjectPathHandler::pointer create_object (const std::string &path, HandlerResult(*MessageFunction)(Connection::pointer, Message::const_pointer), PrimaryFallback pf=PRIMARY)
ObjectProxy::pointer create_object_proxy (const std::string &path)
ObjectProxy::pointer create_object_proxy (const std::string &destination, const std::string &path)
bool unregister_object (const std::string &path)
signal_proxy_simple::pointer create_signal_proxy (const std::string &interface, const std::string &name)
Adds a signal with the given interface and name.
signal_proxy_simple::pointer create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
Adds a signal with the given path, interface and name.
template<class T_return >
DBusCxxPointer< signal_proxy< T_return > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 >
DBusCxxPointer< signal_proxy< T_return, T_arg1 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal_proxy (const std::string &interface, const std::string &name)
template<class T_return >
DBusCxxPointer< signal_proxy< T_return > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 >
DBusCxxPointer< signal_proxy< T_return, T_arg1 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal_proxy (const std::string &path, const std::string &interface, const std::string &name)
signal_proxy_base::pointer add_signal_proxy (signal_proxy_base::pointer signal)
Adds the given signal proxy to the connection.
bool remove_signal_proxy (signal_proxy_base::pointer proxy)
const InterfaceToNameProxySignalMap & get_signal_proxies ()
Gets all the signal handlers.
NameToProxySignalMap get_signal_proxies (const std::string &interface)
Gets the signal handlers for a specific interface.
ProxySignals get_signal_proxies (const std::string &interface, const std::string &member)
Gets the signal handlers for a specific interface and member.
template<class T_return >
DBusCxxPointer< signal< T_return > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 >
DBusCxxPointer< signal< T_return, T_arg1 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal (const std::string &interface, const std::string &name)
template<class T_return >
DBusCxxPointer< signal< T_return > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 >
DBusCxxPointer< signal< T_return, T_arg1 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal (const std::string &path, const std::string &interface, const std::string &name)
pointer self ()
Returns a smart pointer to itself.
DBusConnection * cobj ()
std::string introspect (const std::string &destination, const std::string &path)
Static Public Member Functions
static pointer create (DBusConnection *cobj=NULL, bool is_private=false)
static pointer create (BusType type, bool is_private=false)
Connects to a bus daemon and registers the client with it.
static pointer create (const Connection &other)
static pointer self (DBusConnection *c)
Given a dbus connection, if it was established through a call to Connection::create() this method will return a copy of the smart pointer returned by the create method.
static void set_global_change_sigpipe (bool will_modify_sigpipe=true)
Protected Types
typedef std::map< DBusTimeout *, Timeout::pointer > Timeouts
Protected Member Functions
Connection (DBusConnection *cobj=NULL, bool is_private=false)
Connection (BusType type, bool is_private=false)
Connects to a bus daemon and registers the client with it.
Connection (const Connection &other)
void initialize (bool is_private)
Static Protected Member Functions
static dbus_bool_t on_add_watch_callback (DBusWatch *cwatch, void *data)
static void on_remove_watch_callback (DBusWatch *cwatch, void *data)
static void on_watch_toggled_callback (DBusWatch *cwatch, void *data)
static dbus_bool_t on_add_timeout_callback (DBusTimeout *ctimeout, void *data)
static void on_remove_timeout_callback (DBusTimeout *ctimeout, void *data)
static void on_timeout_toggled_callback (DBusTimeout *ctimeout, void *data)
static void on_wakeup_main_callback (void *data)
static void on_dispatch_status_callback (DBusConnection *connection, DBusDispatchStatus new_status, void *data)
static DBusHandlerResult on_filter_callback (DBusConnection *connection, DBusMessage *message, void *data)
Protected Attributes
DBusConnection * m_cobj
bool m_private_flag
AddWatchSignal m_add_watch_signal
sigc::signal< bool, Watch::pointer > m_remove_watch_signal
sigc::signal< void, Watch::pointer > m_watch_toggled_signal
AddTimeoutSignal m_add_timeout_signal
sigc::signal< bool, Timeout::pointer > m_remove_timeout_signal
sigc::signal< bool, Timeout::pointer > m_timeout_toggled_signal
sigc::signal< void > m_wakeup_main_signal
sigc::signal< void, DispatchStatus > m_dispatch_status_signal
FilterSignal m_filter_signal
Watches m_unhandled_watches
Timeouts m_timeouts
std::map< std::string, ObjectPathHandler::pointer > m_created_objects
InterfaceToNameProxySignalMap m_proxy_signal_interface_map
Static Protected Attributes
static dbus_int32_t m_weak_pointer_slot = -1
Friends
void init (bool)
Initializes the dbus-cxx library.
Detailed Description
Connection point to the DBus.
Todo:
TODO need to deal with signal proxies that change name and/or interface
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
AddTimeoutSignal
typedef sigc::signal1<bool,Timeout::pointer,InterruptablePredicateAccumulatorDefaultFalse> DBus::Connection::AddTimeoutSignal
AddWatchSignal
typedef sigc::signal1<bool,Watch::pointer,InterruptablePredicateAccumulatorDefaultFalse> DBus::Connection::AddWatchSignal
InterfaceToNameProxySignalMap
typedef std::map<std::string,NameToProxySignalMap> DBus::Connection::InterfaceToNameProxySignalMap
NameToProxySignalMap
typedef std::map<std::string,ProxySignals> DBus::Connection::NameToProxySignalMap
pointer
typedef DBusCxxPointer<Connection> DBus::Connection::pointer
ProxySignals
typedef std::list<signal_proxy_base::pointer> DBus::Connection::ProxySignals
Timeouts
typedef std::map<DBusTimeout*,Timeout::pointer> DBus::Connection::Timeouts protected
Watches
typedef std::deque<Watch::pointer> DBus::Connection::Watches
weak_pointer
typedef DBusCxxWeakPointer<Connection> DBus::Connection::weak_pointer
Constructor & Destructor Documentation
Connection() [1/3]
DBus::Connection::Connection (DBusConnection * cobj = NULL, bool is_private = false) protected
References initialize(), and m_cobj.
Referenced by create().
Connection() [2/3]
DBus::Connection::Connection (BusType type, bool is_private = false) protected
Connects to a bus daemon and registers the client with it.
Parameters
is_private if true a private connection will be created. Otherwise a shared connection is created.
References DBus::BUS_NONE, DBus::Error::create(), initialize(), and m_cobj.
Connection() [3/3]
DBus::Connection::Connection (const Connection & other) protected
References m_cobj.
~Connection()
DBus::Connection::~Connection () virtual
References is_private(), is_valid(), and m_cobj.
Member Function Documentation
add_match()
bool DBus::Connection::add_match (const std::string & rule)
References DBus::Error::create(), is_valid(), and m_cobj.
Referenced by add_signal_proxy().
add_match_nonblocking()
void DBus::Connection::add_match_nonblocking (const std::string & rule)
References is_valid(), and m_cobj.
add_signal_proxy()
signal_proxy_base::pointer DBus::Connection::add_signal_proxy (signal_proxy_base::pointer signal)
Adds the given signal proxy to the connection.
References add_match(), m_proxy_signal_interface_map, and DBus::signal_base::name().
Referenced by create_signal_proxy().
borrow_message()
Message::pointer DBus::Connection::borrow_message ()
References DBus::Message::create(), is_valid(), and m_cobj.
bus_id()
const char * DBus::Connection::bus_id () const
The bus' globally unique ID, as described in the D-Bus specification.
References DBus::Error::create(), is_valid(), and m_cobj.
bus_register()
bool DBus::Connection::bus_register ()
Registers this connection with the bus.
References DBus::Error::create(), is_valid(), and m_cobj.
cobj()
DBusConnection * DBus::Connection::cobj ()
References m_cobj.
Referenced by create_signal(), and self().
create() [1/3]
Connection::pointer DBus::Connection::create (DBusConnection * cobj = NULL, bool is_private = false) static
Examples:
callee_raw.cpp, caller_raw.cpp, signal_emitter.cpp, signal_emitter_2.cpp, signal_emitter_raw.cpp, and signal_receiver_raw.cpp.
References DBus::conn_wp_deleter(), Connection(), and m_weak_pointer_slot.
Referenced by DBus::Dispatcher::create_connection().
create() [2/3]
Connection::pointer DBus::Connection::create (BusType type, bool is_private = false) static
Connects to a bus daemon and registers the client with it.
Parameters
is_private if true a private connection will be created. Otherwise a shared connection is created.
References DBus::conn_wp_deleter(), Connection(), and m_weak_pointer_slot.
create() [3/3]
Connection::pointer DBus::Connection::create (const Connection & other) static
References DBus::conn_wp_deleter(), Connection(), and m_weak_pointer_slot.
create_object() [1/3]
Object::pointer DBus::Connection::create_object (const std::string & path, PrimaryFallback pf = PRIMARY)
References DBus::Object::create(), and m_created_objects.
create_object() [2/3]
ObjectPathHandler::pointer DBus::Connection::create_object (const std::string & path, sigc::slot< HandlerResult, Connection::pointer, Message::const_pointer > & slot, PrimaryFallback pf = PRIMARY)
References m_created_objects.
create_object() [3/3]
ObjectPathHandler::pointer DBus::Connection::create_object (const std::string & path, HandlerResult(*)(Connection::pointer, Message::const_pointer) MessageFunction, PrimaryFallback pf = PRIMARY)
References m_created_objects.
create_object_proxy() [1/2]
ObjectProxy::pointer DBus::Connection::create_object_proxy (const std::string & path)
References DBus::ObjectProxy::create().
create_object_proxy() [2/2]
ObjectProxy::pointer DBus::Connection::create_object_proxy (const std::string & destination, const std::string & path)
References DBus::ObjectProxy::create().
create_signal() [1/16]
template<class T_return > DBusCxxPointer<signal<T_return> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [2/16]
template<class T_return , class T_arg1 > DBusCxxPointer<signal<T_return, T_arg1> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [3/16]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [4/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [5/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [6/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [7/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [8/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::Connection::create_signal (const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [9/16]
template<class T_return > DBusCxxPointer<signal<T_return> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [10/16]
template<class T_return , class T_arg1 > DBusCxxPointer<signal<T_return, T_arg1> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [11/16]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [12/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [13/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [14/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [15/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal() [16/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::Connection::create_signal (const std::string & path, const std::string & interface, const std::string & name) inline
References cobj(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), introspect(), and set_global_change_sigpipe().
create_signal_proxy() [1/18]
signal_proxy_simple::pointer DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name)
Adds a signal with the given interface and name.
Returns
Smart pointer to the newly added signal or a null smart pointer if it couldn't be added
References add_signal_proxy(), and DBus::signal_proxy_simple::create().
create_signal_proxy() [2/18]
signal_proxy_simple::pointer DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name)
Adds a signal with the given path, interface and name.
Returns
Smart pointer to the newly added signal or a null smart pointer if it couldn't be added
References add_signal_proxy(), and DBus::signal_proxy_simple::create().
create_signal_proxy() [3/18]
template<class T_return > DBusCxxPointer<signal_proxy<T_return> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [4/18]
template<class T_return , class T_arg1 > DBusCxxPointer<signal_proxy<T_return, T_arg1> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [5/18]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [6/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [7/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [8/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [9/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [10/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::Connection::create_signal_proxy (const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [11/18]
template<class T_return > DBusCxxPointer<signal_proxy<T_return> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [12/18]
template<class T_return , class T_arg1 > DBusCxxPointer<signal_proxy<T_return, T_arg1> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [13/18]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [14/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [15/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [16/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [17/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), and DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create().
create_signal_proxy() [18/18]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer<signal_proxy<T_return, T_arg1,T_arg2,T_arg3,T_arg4,T_arg5,T_arg6,T_arg7> > DBus::Connection::create_signal_proxy (const std::string & path, const std::string & interface, const std::string & name) inline
References add_signal_proxy(), DBus::signal_proxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and remove_signal_proxy().
dispatch()
DispatchStatus DBus::Connection::dispatch ()
References DBus::DISPATCH_COMPLETE, is_valid(), and m_cobj.
dispatch_status()
DispatchStatus DBus::Connection::dispatch_status () const
References DBus::DISPATCH_COMPLETE, is_valid(), and m_cobj.
flush()
void DBus::Connection::flush ()
References is_valid(), and m_cobj.
Referenced by introspect().
get_signal_proxies() [1/3]
const Connection::InterfaceToNameProxySignalMap & DBus::Connection::get_signal_proxies ()
Gets all the signal handlers.
References m_proxy_signal_interface_map.
get_signal_proxies() [2/3]
Connection::NameToProxySignalMap DBus::Connection::get_signal_proxies (const std::string & interface)
Gets the signal handlers for a specific interface.
References m_proxy_signal_interface_map.
get_signal_proxies() [3/3]
Connection::ProxySignals DBus::Connection::get_signal_proxies (const std::string & interface, const std::string & member)
Gets the signal handlers for a specific interface and member.
References m_proxy_signal_interface_map.
has_messages_to_send()
bool DBus::Connection::has_messages_to_send ()
References is_valid(), and m_cobj.
initialize()
void DBus::Connection::initialize (bool is_private) protected
References is_private(), m_cobj, m_private_flag, on_add_timeout_callback(), on_add_watch_callback(), on_dispatch_status_callback(), on_filter_callback(), on_remove_timeout_callback(), on_remove_watch_callback(), on_timeout_toggled_callback(), on_wakeup_main_callback(), and on_watch_toggled_callback().
Referenced by Connection().
introspect()
std::string DBus::Connection::introspect (const std::string & destination, const std::string & path)
References DBus::CallMessage::create(), flush(), and send_with_reply_async().
Referenced by create_signal().
is_anonymous()
bool DBus::Connection::is_anonymous () const
References is_valid(), and m_cobj.
is_authenticated()
bool DBus::Connection::is_authenticated () const
References is_valid(), and m_cobj.
is_connected()
bool DBus::Connection::is_connected () const
References is_valid(), and m_cobj.
is_private()
bool DBus::Connection::is_private () const
True if this is a valid connection and is private; false otherwise.
References m_private_flag.
Referenced by initialize(), and ~Connection().
is_registered()
bool DBus::Connection::is_registered () const
True if this connection is already registered.
References unique_name().
is_valid()
bool DBus::Connection::is_valid () const
True if this is a valid connection; false otherwise.
References m_cobj.
Referenced by add_match(), add_match_nonblocking(), borrow_message(), bus_id(), bus_register(), dispatch(), dispatch_status(), flush(), has_messages_to_send(), is_anonymous(), is_authenticated(), is_connected(), max_message_size(), max_received_size(), name_has_owner(), outgoing_size(), pop_message(), read_write(), read_write_dispatch(), release_name(), remove_match(), remove_match_nonblocking(), request_name(), return_message(), self(), send(), send_with_reply_async(), send_with_reply_blocking(), server_id(), set_allow_anonymous(), set_max_message_size(), set_max_received_size(), set_route_peer_messages(), socket(), start_service(), steal_borrowed_message(), unique_name(), unix_fd(), unix_process_id(), unix_user(), and ~Connection().
max_message_size()
long DBus::Connection::max_message_size ()
References is_valid(), and m_cobj.
max_received_size()
long DBus::Connection::max_received_size ()
References is_valid(), and m_cobj.
name_has_owner()
bool DBus::Connection::name_has_owner (const std::string & name) const
References DBus::Error::create(), is_valid(), and m_cobj.
on_add_timeout_callback()
dbus_bool_t DBus::Connection::on_add_timeout_callback (DBusTimeout * ctimeout, void * data) static protected
References DBus::Timeout::create(), m_timeouts, and signal_add_timeout().
Referenced by initialize().
on_add_watch_callback()
dbus_bool_t DBus::Connection::on_add_watch_callback (DBusWatch * cwatch, void * data) static protected
References DBus::Watch::create(), m_unhandled_watches, and signal_add_watch().
Referenced by initialize().
on_dispatch_status_callback()
void DBus::Connection::on_dispatch_status_callback (DBusConnection * connection, DBusDispatchStatus new_status, void * data) static protected
References signal_dispatch_status_changed().
Referenced by initialize().
on_filter_callback()
DBusHandlerResult DBus::Connection::on_filter_callback (DBusConnection * connection, DBusMessage * message, void * data) static protected
References DBus::SignalMessage::create(), DBus::Message::create(), DBus::DONT_FILTER, DBus::FILTER, DBus::FILTER_NEEDS_MEMORY, DBus::HANDLED, DBus::HANDLER_NEEDS_MEMORY, DBus::NOT_HANDLED, and DBus::SIGNAL_MESSAGE.
Referenced by initialize().
on_remove_timeout_callback()
void DBus::Connection::on_remove_timeout_callback (DBusTimeout * ctimeout, void * data) static protected
References DBus::Timeout::create(), m_timeouts, and signal_remove_timeout().
Referenced by initialize().
on_remove_watch_callback()
void DBus::Connection::on_remove_watch_callback (DBusWatch * cwatch, void * data) static protected
References DBus::Watch::create(), and signal_remove_watch().
Referenced by initialize().
on_timeout_toggled_callback()
void DBus::Connection::on_timeout_toggled_callback (DBusTimeout * ctimeout, void * data) static protected
References DBus::Timeout::create(), m_timeouts, and signal_timeout_toggled().
Referenced by initialize().
on_wakeup_main_callback()
void DBus::Connection::on_wakeup_main_callback (void * data) static protected
References signal_wakeup_main().
Referenced by initialize().
on_watch_toggled_callback()
void DBus::Connection::on_watch_toggled_callback (DBusWatch * cwatch, void * data) static protected
References DBus::Watch::create(), and signal_watch_toggled().
Referenced by initialize().
operator bool()
DBus::Connection::operator bool () const
True if this is a valid connection; false otherwise.
References m_cobj.
operator<<()
Connection & DBus::Connection::operator<< (Message::const_pointer msg)
Sends the message on the connection.
References send().
outgoing_size()
long DBus::Connection::outgoing_size ()
References is_valid(), and m_cobj.
pop_message()
Message::pointer DBus::Connection::pop_message ()
References DBus::Message::create(), is_valid(), and m_cobj.
read_write()
bool DBus::Connection::read_write (int timeout_milliseconds = -1)
References is_valid(), and m_cobj.
read_write_dispatch()
bool DBus::Connection::read_write_dispatch (int timeout_milliseconds = -1)
References is_valid(), and m_cobj.
register_object()
bool DBus::Connection::register_object (Object::pointer object)
release_name()
int DBus::Connection::release_name (const std::string & name)
References DBus::Error::create(), is_valid(), and m_cobj.
remove_match()
bool DBus::Connection::remove_match (const std::string & rule)
References DBus::Error::create(), is_valid(), and m_cobj.
Referenced by remove_signal_proxy().
remove_match_nonblocking()
void DBus::Connection::remove_match_nonblocking (const std::string & rule)
References is_valid(), and m_cobj.
remove_signal_proxy()
bool DBus::Connection::remove_signal_proxy (signal_proxy_base::pointer proxy)
References m_proxy_signal_interface_map, DBus::signal_base::name(), and remove_match().
Referenced by create_signal_proxy().
remove_unhandled_watch()
void DBus::Connection::remove_unhandled_watch (const Watch::pointer w)
References m_unhandled_watches.
request_name()
int DBus::Connection::request_name (const std::string & name, unsigned int flags = 0)
References DBus::Error::create(), is_valid(), and m_cobj.
return_message()
void DBus::Connection::return_message (Message::pointer message)
References is_valid(), and m_cobj.
self() [1/2]
Connection::pointer DBus::Connection::self ()
Returns a smart pointer to itself.
References cobj(), is_valid(), and m_weak_pointer_slot.
Referenced by DBus::MessageHandler::message_handler_callback().
self() [2/2]
Connection::pointer DBus::Connection::self (DBusConnection * c) static
Given a dbus connection, if it was established through a call to Connection::create() this method will return a copy of the smart pointer returned by the create method.
This is accomplished safely because the create() methods store a weak pointer in a dbus data slot associated with the DBusConnection C object, and this method creates the smart pointer from the weak pointer if the weak pointer is still valid.
If the DBusConnection was created outside a Connection::create() method or the underlying object has already been deleted this method will return an empty pointer.
References m_weak_pointer_slot.
send()
uint32_t DBus::Connection::send (const Message::const_pointer msg)
References is_valid(), and m_cobj.
Referenced by operator<<().
send_with_reply_async()
PendingCall::pointer DBus::Connection::send_with_reply_async (Message::const_pointer message, int timeout_milliseconds = -1) const
References DBus::PendingCall::create(), is_valid(), and m_cobj.
Referenced by introspect().
send_with_reply_blocking()
ReturnMessage::const_pointer DBus::Connection::send_with_reply_blocking (Message::const_pointer msg, int timeout_milliseconds = -1) const
References DBus::ReturnMessage::create(), DBus::Error::create(), is_valid(), and m_cobj.
server_id()
const char * DBus::Connection::server_id () const
References is_valid(), and m_cobj.
set_allow_anonymous()
void DBus::Connection::set_allow_anonymous (bool allow = true)
References is_valid(), and m_cobj.
set_global_change_sigpipe()
void DBus::Connection::set_global_change_sigpipe (bool will_modify_sigpipe = true) static
Referenced by create_signal().
set_max_message_size()
void DBus::Connection::set_max_message_size (long size)
References is_valid(), and m_cobj.
set_max_received_size()
void DBus::Connection::set_max_received_size (long size)
References is_valid(), and m_cobj.
set_route_peer_messages()
void DBus::Connection::set_route_peer_messages (bool route = true)
References is_valid(), and m_cobj.
signal_add_timeout()
Connection::AddTimeoutSignal & DBus::Connection::signal_add_timeout ()
Cannot call timeout.handle() in a slot connected to this signal.
References m_add_timeout_signal.
Referenced by on_add_timeout_callback().
signal_add_watch()
Connection::AddWatchSignal & DBus::Connection::signal_add_watch ()
Cannot call watch.handle() in a slot connected to this signal.
References m_add_watch_signal.
Referenced by on_add_watch_callback().
signal_dispatch_status_changed()
sigc::signal< void, DispatchStatus > & DBus::Connection::signal_dispatch_status_changed ()
Cannot call dispatch() in a slot connected to this signal.
References m_dispatch_status_signal.
Referenced by on_dispatch_status_callback().
signal_filter()
FilterSignal & DBus::Connection::signal_filter ()
Signal emitted during dispatch.
A slot returning true will cause the message to be filtered.
References m_filter_signal.
signal_remove_timeout()
sigc::signal< bool, Timeout::pointer > & DBus::Connection::signal_remove_timeout ()
References m_remove_timeout_signal.
Referenced by on_remove_timeout_callback().
signal_remove_watch()
sigc::signal< bool, Watch::pointer > & DBus::Connection::signal_remove_watch ()
References m_remove_watch_signal.
Referenced by on_remove_watch_callback().
signal_timeout_toggled()
sigc::signal< bool, Timeout::pointer > & DBus::Connection::signal_timeout_toggled ()
References m_timeout_toggled_signal.
Referenced by on_timeout_toggled_callback().
signal_wakeup_main()
sigc::signal< void > & DBus::Connection::signal_wakeup_main ()
References m_wakeup_main_signal.
Referenced by on_wakeup_main_callback().
signal_watch_toggled()
sigc::signal< void, Watch::pointer > & DBus::Connection::signal_watch_toggled ()
References m_watch_toggled_signal.
Referenced by on_watch_toggled_callback().
socket()
int DBus::Connection::socket () const
References is_valid(), and m_cobj.
start_service()
StartReply DBus::Connection::start_service (const std::string & name, uint32_t flags) const
References DBus::Error::create(), is_valid(), m_cobj, DBus::START_REPLY_ALREADY_RUNNING, DBus::START_REPLY_FAILED, and DBus::START_REPLY_SUCCESS.
steal_borrowed_message()
void DBus::Connection::steal_borrowed_message (Message::pointer message)
References is_valid(), and m_cobj.
unhandled_watches()
const Connection::Watches & DBus::Connection::unhandled_watches () const
References m_unhandled_watches.
unique_name()
const char * DBus::Connection::unique_name () const
Gets the unique name of the connection as assigned by the message bus.
References is_valid(), and m_cobj.
Referenced by is_registered().
unix_fd()
int DBus::Connection::unix_fd () const
References is_valid(), and m_cobj.
unix_process_id()
unsigned long DBus::Connection::unix_process_id () const
References is_valid(), and m_cobj.
unix_user() [1/2]
unsigned long DBus::Connection::unix_user (const std::string & name) const
The unix user id associated with the name connection or -1 if an error occurred.
References DBus::Error::create(), is_valid(), and m_cobj.
unix_user() [2/2]
unsigned long DBus::Connection::unix_user () const
References is_valid(), and m_cobj.
unregister_object()
bool DBus::Connection::unregister_object (const std::string & path)
Friends And Related Function Documentation
init
void init (bool) friend
Initializes the dbus-cxx library.
Parameters
threadsafe If true the library's threadsafe structures, along with the underlying dbus library will be initialized to support threadsafe operations. This makes the library threadsafe at the cost of efficiency.
Member Data Documentation
m_add_timeout_signal
AddTimeoutSignal DBus::Connection::m_add_timeout_signal protected
Referenced by signal_add_timeout().
m_add_watch_signal
AddWatchSignal DBus::Connection::m_add_watch_signal protected
Referenced by signal_add_watch().
m_cobj
DBusConnection* DBus::Connection::m_cobj protected
Referenced by add_match(), add_match_nonblocking(), borrow_message(), bus_id(), bus_register(), cobj(), Connection(), dispatch(), dispatch_status(), flush(), has_messages_to_send(), initialize(), is_anonymous(), is_authenticated(), is_connected(), is_valid(), max_message_size(), max_received_size(), name_has_owner(), operator bool(), outgoing_size(), pop_message(), read_write(), read_write_dispatch(), release_name(), remove_match(), remove_match_nonblocking(), request_name(), return_message(), send(), send_with_reply_async(), send_with_reply_blocking(), server_id(), set_allow_anonymous(), set_max_message_size(), set_max_received_size(), set_route_peer_messages(), socket(), start_service(), steal_borrowed_message(), unique_name(), unix_fd(), unix_process_id(), unix_user(), and ~Connection().
m_created_objects
std::map<std::string,ObjectPathHandler::pointer> DBus::Connection::m_created_objects protected
Referenced by create_object().
m_dispatch_status_signal
sigc::signal<void,DispatchStatus> DBus::Connection::m_dispatch_status_signal protected
Referenced by signal_dispatch_status_changed().
m_filter_signal
FilterSignal DBus::Connection::m_filter_signal protected
Referenced by signal_filter().
m_private_flag
bool DBus::Connection::m_private_flag protected
Referenced by initialize(), and is_private().
m_proxy_signal_interface_map
InterfaceToNameProxySignalMap DBus::Connection::m_proxy_signal_interface_map protected
Referenced by add_signal_proxy(), get_signal_proxies(), and remove_signal_proxy().
m_remove_timeout_signal
sigc::signal<bool,Timeout::pointer> DBus::Connection::m_remove_timeout_signal protected
Referenced by signal_remove_timeout().
m_remove_watch_signal
sigc::signal<bool,Watch::pointer> DBus::Connection::m_remove_watch_signal protected
Referenced by signal_remove_watch().
m_timeout_toggled_signal
sigc::signal<bool,Timeout::pointer> DBus::Connection::m_timeout_toggled_signal protected
Referenced by signal_timeout_toggled().
m_timeouts
Timeouts DBus::Connection::m_timeouts protected
Referenced by on_add_timeout_callback(), on_remove_timeout_callback(), and on_timeout_toggled_callback().
m_unhandled_watches
Watches DBus::Connection::m_unhandled_watches protected
Referenced by on_add_watch_callback(), remove_unhandled_watch(), and unhandled_watches().
m_wakeup_main_signal
sigc::signal<void> DBus::Connection::m_wakeup_main_signal protected
Referenced by signal_wakeup_main().
m_watch_toggled_signal
sigc::signal<void,Watch::pointer> DBus::Connection::m_watch_toggled_signal protected
Referenced by signal_watch_toggled().
m_weak_pointer_slot
dbus_int32_t DBus::Connection::m_weak_pointer_slot = -1 static protected
Referenced by create(), DBus::init(), and self().
The documentation for this class was generated from the following files:
connection.h
connection.cpp