DBus::Interface Class Reference
DBus::Interface Class Reference
Objects | Local Objects
#include <interface.h>
Public Types
typedef DBusCxxPointer< Interface > pointer
Typedef to smart pointers to Interface.
typedef DBusCxxWeakPointer< Interface > weak_pointer
Typedef to weak smart pointers to Interface.
typedef std::multimap< std::string, MethodBase::pointer > Methods
Typedef to the storage structure for methods.
typedef std::set< signal_base::pointer > Signals
Typedef to the storage structure for signals.
Public Member Functions
virtual ~Interface ()
Object * object () const
Returns the object associated with this interface.
Path path () const
Returns the path of the object associated with this interface or a null string if no object is associated.
DBusCxxPointer< Connection > connection () const
Returns the connection associated with this interface's object or a null pointer if no object is associated.
HandlerResult handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
Handles the specified call message on the specified connection.
const std::string & name () const
Get the name of this interface.
void set_name (const std::string &new_name)
Sets the name of this interface.
const Methods & methods () const
Returns the methods associated with this interface.
MethodBase::pointer method (const std::string &name) const
Returns the first method with the given name.
template<class T_return >
DBusCxxPointer< Method< T_return > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 0 parameters.
template<class T_return , class T_arg1 >
DBusCxxPointer< Method< T_return, T_arg1 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 1 parameters.
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 2 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 3 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 4 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 5 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 6 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_method (const std::string &name)
Creates a method with a return value (possibly void) and 7 parameters.
template<class T_return >
DBusCxxPointer< Method< T_return > > create_method (const std::string &name, sigc::slot0< T_return > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 >
DBusCxxPointer< Method< T_return, T_arg1 > > create_method (const std::string &name, sigc::slot1< T_return, T_arg1 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2 > > create_method (const std::string &name, sigc::slot2< T_return, T_arg1, T_arg2 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3 > > create_method (const std::string &name, sigc::slot3< T_return, T_arg1, T_arg2, T_arg3 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_method (const std::string &name, sigc::slot4< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_method (const std::string &name, sigc::slot5< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_method (const std::string &name, sigc::slot6< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > slot)
Creates a method with a signature equivalent to the provided.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_method (const std::string &name, sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot)
Creates a method with a signature equivalent to the provided.
bool add_method (MethodBase::pointer method)
Adds the named method.
void remove_method (const std::string &name)
Removes the first method with the given name.
bool has_method (const std::string &name) const
True if the interface has a method with the given name.
bool add_signal (signal_base::pointer signal)
Adds the given signal.
bool remove_signal (signal_base::pointer signal)
Removes the given signal.
bool remove_signal (const std::string &name)
Removes all signals with the given name.
bool has_signal (signal_base::pointer signal) const
True if the given signal is part of this interface.
bool has_signal (const std::string &name) const
True if this interface has at least one signal with the given name.
template<class T_return >
DBusCxxPointer< signal< T_return > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 0 parameters.
template<class T_return , class T_arg1 >
DBusCxxPointer< signal< T_return, T_arg1 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 1 parameters.
template<class T_return , class T_arg1 , class T_arg2 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 2 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 3 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 4 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 5 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 6 parameters.
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 >
DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and 7 parameters.
const Signals & signals ()
Returns the signals associated with this interface.
signal_base::pointer signal (const std::string &signal_name)
Returns the first signal found with a matching name.
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Signal emitted when the name is changed.
sigc::signal< void, MethodBase::pointer > signal_method_added ()
Signal emitted when a method of the given name is added.
sigc::signal< void, MethodBase::pointer > signal_method_removed ()
Signal emitted when a method of the given name is removed.
std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
Static Public Member Functions
static pointer create (const std::string &name=std::string())
Creates a named Interface.
Protected Types
typedef std::map< MethodBase::pointer, sigc::connection > MethodSignalNameConnections
Protected Member Functions
Interface (const std::string &name)
This class has a protected constructor.
void set_object (Object *object)
void on_method_name_changed (const std::string &oldname, const std::string &newname, MethodBase::pointer method)
Callback point that updates the method name map when a method changes its name.
void set_connection (DBusCxxPointer< Connection > conn)
void set_path (const std::string &new_path)
Protected Attributes
std::string m_name
Methods m_methods
Signals m_signals
pthread_rwlock_t m_methods_rwlock
pthread_rwlock_t m_signals_rwlock
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
sigc::signal< void, MethodBase::pointer > m_signal_method_added
sigc::signal< void, MethodBase::pointer > m_signal_method_removed
MethodSignalNameConnections m_method_signal_name_connections
Private Attributes
Object * m_object
Friends
class Object
Detailed Description
Todo:
Do something about the signals when the interface name is changed
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
Methods
typedef std::multimap<std::string, MethodBase::pointer> DBus::Interface::Methods
Typedef to the storage structure for methods.
Data Structure - multimap is used since multiple methods can have the same name. This is what allows for overloading. Key - method name Value -smart pointer to a method.
Can access type as Interface::Methods
MethodSignalNameConnections
typedef std::map<MethodBase::pointer,sigc::connection> DBus::Interface::MethodSignalNameConnections protected
pointer
typedef DBusCxxPointer<Interface> DBus::Interface::pointer
Typedef to smart pointers to Interface.
Can access type as Interface::pointer
Signals
typedef std::set<signal_base::pointer> DBus::Interface::Signals
Typedef to the storage structure for signals.
Data Structure - sets is used since signal names are not needed for the interface, but must be unique.
Can access type as Interface::Signals
weak_pointer
typedef DBusCxxWeakPointer<Interface> DBus::Interface::weak_pointer
Typedef to weak smart pointers to Interface.
Can access type as Interface::weak_pointer
Constructor & Destructor Documentation
Interface()
DBus::Interface::Interface (const std::string & name) protected
This class has a protected constructor.
Use the create() methods to obtain a smart pointer to a new instance.
References m_methods_rwlock, m_name_mutex, and m_signals_rwlock.
Referenced by create().
~Interface()
DBus::Interface::~Interface () virtual
References m_methods_rwlock, m_name_mutex, and m_signals_rwlock.
Member Function Documentation
add_method()
bool DBus::Interface::add_method (MethodBase::pointer method)
Adds the named method.
References m_method_signal_name_connections, m_methods, m_methods_rwlock, m_signal_method_added, method(), and on_method_name_changed().
Referenced by create_method().
add_signal()
bool DBus::Interface::add_signal (signal_base::pointer signal)
Adds the given signal.
Returns
true if the signal was successfully added, false otherwise
References connection(), m_name, m_signals, m_signals_rwlock, name(), and path().
Referenced by create_signal().
connection()
Connection::pointer DBus::Interface::connection () const
Returns the connection associated with this interface's object or a null pointer if no object is associated.
References m_object.
Referenced by add_signal().
create()
Interface::pointer DBus::Interface::create (const std::string & name = std::string()) static
Creates a named Interface.
Parameters
name The name of this interface
References Interface().
Referenced by DBus::Object::create_interface().
create_method() [1/16]
template<class T_return > DBusCxxPointer< Method< T_return > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 0 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [2/16]
template<class T_return , class T_arg1 > DBusCxxPointer< Method< T_return, T_arg1 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 1 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [3/16]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 2 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [4/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 3 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [5/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 4 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [6/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 5 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [7/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 6 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [8/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > DBus::Interface::create_method (const std::string & name)
Creates a method with a return value (possibly void) and 7 parameters.
Returns
A smart pointer to the newly created method
Parameters
name The name that will be associated with this method
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [9/16]
template<class T_return > DBusCxxPointer< Method< T_return > > DBus::Interface::create_method (const std::string & name, sigc::slot0< T_return > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [10/16]
template<class T_return , class T_arg1 > DBusCxxPointer< Method< T_return, T_arg1 > > DBus::Interface::create_method (const std::string & name, sigc::slot1< T_return, T_arg1 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [11/16]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2 > > DBus::Interface::create_method (const std::string & name, sigc::slot2< T_return, T_arg1, T_arg2 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [12/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3 > > DBus::Interface::create_method (const std::string & name, sigc::slot3< T_return, T_arg1, T_arg2, T_arg3 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [13/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > DBus::Interface::create_method (const std::string & name, sigc::slot4< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [14/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > DBus::Interface::create_method (const std::string & name, sigc::slot5< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [15/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > DBus::Interface::create_method (const std::string & name, sigc::slot6< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_method() [16/16]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer< Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > DBus::Interface::create_method (const std::string & name, sigc::slot7< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > slot)
Creates a method with a signature equivalent to the provided.
Parameters
slot parameter's signature
Returns
A smart pointer to the newly created method
Parameters
slot This slot will be called with the given signature when the method is invoked
Template parameters of the sigc::slot will determine the signature of the method created.
References add_method(), DBus::Method< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and method().
create_signal() [1/8]
template<class T_return > DBusCxxPointer< signal< T_return > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 0 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [2/8]
template<class T_return , class T_arg1 > DBusCxxPointer< signal< T_return, T_arg1 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 1 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [3/8]
template<class T_return , class T_arg1 , class T_arg2 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 2 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [4/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 3 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [5/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 4 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [6/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 5 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [7/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 6 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
create_signal() [8/8]
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 , class T_arg5 , class T_arg6 , class T_arg7 > DBusCxxPointer< signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 > > DBus::Interface::create_signal (const std::string & name)
Creates a signal with a return value (possibly void) and 7 parameters.
Returns
A smart pointer to the newly created signal
Parameters
name The name that will be associated with this signal
References add_signal(), DBus::signal< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::create(), and m_name.
handle_call_message()
HandlerResult DBus::Interface::handle_call_message (DBusCxxPointer< Connection > connection, CallMessage::const_pointer message)
Handles the specified call message on the specified connection.
Looks for methods matching the name specified in the message, then calls handle_call_message() for each matching message.
Once a method returns HANDLED no further methods will be tried.
Returns
HANDLED if one method in this interface handled the message, NOT_HANDLED otherwise
Parameters
conn The Connection to send the reply message on
msg The CallMessage to handle
References DBus::HANDLED, m_methods, m_name, method(), and DBus::NOT_HANDLED.
has_method()
bool DBus::Interface::has_method (const std::string & name) const
True if the interface has a method with the given name.
References m_methods, and m_methods_rwlock.
has_signal() [1/2]
bool DBus::Interface::has_signal (signal_base::pointer signal) const
True if the given signal is part of this interface.
References m_signals, and m_signals_rwlock.
has_signal() [2/2]
bool DBus::Interface::has_signal (const std::string & name) const
True if this interface has at least one signal with the given name.
References m_signals, m_signals_rwlock, and name().
introspect()
std::string DBus::Interface::introspect (int space_depth = 0) const
Returns a DBus XML description of this interface.
References m_methods, m_signals, and name().
method()
MethodBase::pointer DBus::Interface::method (const std::string & name) const
Returns the first method with the given name.
References m_methods, and m_methods_rwlock.
Referenced by add_method(), create_method(), handle_call_message(), on_method_name_changed(), and remove_method().
methods()
const Interface::Methods & DBus::Interface::methods () const
Returns the methods associated with this interface.
References m_methods.
name()
const std::string & DBus::Interface::name () const
Get the name of this interface.
References m_name.
Referenced by add_signal(), has_signal(), introspect(), remove_signal(), and set_connection().
object()
Object * DBus::Interface::object () const
Returns the object associated with this interface.
Note that there is no set_object() method as an interface must be added to an object through the object's add_interface() method.
References m_object.
Referenced by set_object().
on_method_name_changed()
void DBus::Interface::on_method_name_changed (const std::string & oldname, const std::string & newname, MethodBase::pointer method) protected
Callback point that updates the method name map when a method changes its name.
References m_method_signal_name_connections, m_methods, m_methods_rwlock, and method().
Referenced by add_method().
path()
Path DBus::Interface::path () const
Returns the path of the object associated with this interface or a null string if no object is associated.
References m_object.
Referenced by add_signal().
remove_method()
void DBus::Interface::remove_method (const std::string & name)
Removes the first method with the given name.
References m_method_signal_name_connections, m_methods, m_methods_rwlock, m_signal_method_removed, and method().
remove_signal() [1/2]
bool DBus::Interface::remove_signal (signal_base::pointer signal)
Removes the given signal.
Returns
true if the signal was successfully removed, false otherwise
One reason a signal couldn't be removed is if it wasn't a part of the interface.
References m_signals, and m_signals_rwlock.
remove_signal() [2/2]
bool DBus::Interface::remove_signal (const std::string & name)
Removes all signals with the given name.
References m_signals, m_signals_rwlock, and name().
set_connection()
void DBus::Interface::set_connection (DBusCxxPointer< Connection > conn) protected
References m_signals, and name().
set_name()
void DBus::Interface::set_name (const std::string & new_name)
Sets the name of this interface.
References m_name, m_name_mutex, m_signal_name_changed, and m_signals.
set_object()
void DBus::Interface::set_object (Object * object) protected
References m_object, m_signals, and object().
set_path()
void DBus::Interface::set_path (const std::string & new_path) protected
References m_signals.
signal()
signal_base::pointer DBus::Interface::signal (const std::string & signal_name)
Returns the first signal found with a matching name.
If more than one signal has a given name there are no guarantees as to which signal will be returned.
References m_signals, and m_signals_rwlock.
signal_method_added()
sigc::signal< void, MethodBase::pointer > DBus::Interface::signal_method_added ()
Signal emitted when a method of the given name is added.
References m_signal_method_added.
signal_method_removed()
sigc::signal< void, MethodBase::pointer > DBus::Interface::signal_method_removed ()
Signal emitted when a method of the given name is removed.
References m_signal_method_removed.
signal_name_changed()
sigc::signal< void, const std::string &, const std::string &> DBus::Interface::signal_name_changed ()
Signal emitted when the name is changed.
References m_signal_name_changed.
signals()
const Interface::Signals & DBus::Interface::signals ()
Returns the signals associated with this interface.
References m_signals.
Friends And Related Function Documentation
Object
friend class Object friend
Member Data Documentation
m_method_signal_name_connections
MethodSignalNameConnections DBus::Interface::m_method_signal_name_connections protected
Referenced by add_method(), on_method_name_changed(), and remove_method().
m_methods
Methods DBus::Interface::m_methods protected
Referenced by add_method(), handle_call_message(), has_method(), introspect(), method(), methods(), on_method_name_changed(), and remove_method().
m_methods_rwlock
pthread_rwlock_t DBus::Interface::m_methods_rwlock mutable protected
Referenced by add_method(), has_method(), Interface(), method(), on_method_name_changed(), remove_method(), and ~Interface().
m_name
std::string DBus::Interface::m_name protected
Referenced by add_signal(), create_signal(), handle_call_message(), name(), and set_name().
m_name_mutex
pthread_mutex_t DBus::Interface::m_name_mutex protected
Ensures that the name doesn't change while the name changed signal is emitting.
Referenced by Interface(), set_name(), and ~Interface().
m_object
Object* DBus::Interface::m_object private
Referenced by connection(), object(), path(), and set_object().
m_signal_method_added
sigc::signal<void,MethodBase::pointer> DBus::Interface::m_signal_method_added protected
Referenced by add_method(), and signal_method_added().
m_signal_method_removed
sigc::signal<void,MethodBase::pointer> DBus::Interface::m_signal_method_removed protected
Referenced by remove_method(), and signal_method_removed().
m_signal_name_changed
sigc::signal<void,const std::string&,const std::string&> DBus::Interface::m_signal_name_changed protected
Referenced by set_name(), and signal_name_changed().
m_signals
Signals DBus::Interface::m_signals protected
Referenced by add_signal(), has_signal(), introspect(), remove_signal(), set_connection(), set_name(), set_object(), set_path(), signal(), and signals().
m_signals_rwlock
pthread_rwlock_t DBus::Interface::m_signals_rwlock mutable protected
Referenced by add_signal(), has_signal(), Interface(), remove_signal(), signal(), and ~Interface().
The documentation for this class was generated from the following files:
interface.h
interface.cpp