dbus-cxx: DBus::Path Class Reference
DBus::Path Class Reference
Represents a DBus Path.
#include <path.h>
Inherits std::string.
Public Member Functions
Path ()
Path (const std::string &s, size_type pos=0, size_type n=npos)
Path (const char *)
Path (const char *s, size_type n)
Path (size_type n, char c)
template<class InputIterator >
Path (InputIterator first, InputIterator last)
~Path ()
operator bool () const
bool is_valid () const
bool is_root () const
std::vector< std::string > decomposed () const
Decomposes the string into its component elements.
bool append_element (const std::string &element)
Adds the element string to the path ensuring delimeters are properly taken care of.
Static Public Member Functions
static Path relative_path (const Path &first, const Path &second)
Create a relative path between the two paths.
Detailed Description
Represents a DBus Path.
Paths have slashes in them(e.g. /com/example/MusicPlayer1)
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Constructor & Destructor Documentation
Path() [1/6]
DBus::Path::Path ()
Path() [2/6]
DBus::Path::Path (const std::string & s, size_type pos = 0, size_type n = npos)
Path() [3/6]
DBus::Path::Path (const char * s)
Path() [4/6]
DBus::Path::Path (const char * s, size_type n)
Path() [5/6]
DBus::Path::Path (size_type n, char c)
Path() [6/6]
template<class InputIterator > DBus::Path::Path (InputIterator first, InputIterator last) inline
~Path()
DBus::Path::~Path ()
Member Function Documentation
append_element()
bool DBus::Path::append_element (const std::string & element)
Adds the element string to the path ensuring delimeters are properly taken care of.
An element that contains invalid characters will not be added to the path.
Returns
True if the element was succesfully added, false otherwise.
References DBUSCXX_VALID_PATH_CHARACTERS, and DBus::npos.
Referenced by relative_path().
decomposed()
std::vector< std::string > DBus::Path::decomposed () const
Decomposes the string into its component elements.
If the path is invalid or non-existant an empty vector will be returned.
If the path is the root path a vector containing a single empty string will be returned. In this way a valid root path is differentiated from an invalid or empty path.
References decomposed(), and is_valid().
Referenced by decomposed(), DBus::Connection::process_call_message(), relative_path(), and DBus::Connection::unregister_object().
is_root()
bool DBus::Path::is_root () const
Referenced by DBus::Connection::process_call_message(), relative_path(), and DBus::Connection::unregister_object().
is_valid()
bool DBus::Path::is_valid () const
References DBUSCXX_VALID_PATH_CHARACTERS, and DBus::npos.
Referenced by decomposed().
operator bool()
DBus::Path::operator bool () const
relative_path()
Path DBus::Path::relative_path (const Path & first, const Path & second) static
Create a relative path between the two paths.
The second param must be below the first, e.g. if first is "/first" and second is "/second" this returns a null path.
Parameters
first
second
Returns
References append_element(), decomposed(), and is_root().
The documentation for this class was generated from the following files:
path.h
path.cpp