dbus-cxx: DBus::Uv::UvDispatcher Class Reference
DBus::Uv::UvDispatcher Class Reference
#include <uvdispatcher.h>
Public Member Functions
~UvDispatcher ()
std::shared_ptr< Connection > create_connection (BusType type)
std::shared_ptr< Connection > create_connection (std::string address)
bool add_connection (std::shared_ptr< Connection > connection)
Public Member Functions inherited from DBus::Dispatcher
virtual ~Dispatcher ()
Static Public Member Functions
static std::shared_ptr< UvDispatcher > create ()
Private Member Functions
UvDispatcher ()
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Constructor & Destructor Documentation
UvDispatcher()
UvDispatcher::UvDispatcher () private
Referenced by create().
~UvDispatcher()
UvDispatcher::~UvDispatcher ()
Member Function Documentation
add_connection()
bool UvDispatcher::add_connection (std::shared_ptr< Connection > connection) virtual
Implements DBus::Dispatcher.
References LOGGER_NAME, and SIMPLELOGGER_ERROR.
Referenced by create_connection().
create()
std::shared_ptr< UvDispatcher > UvDispatcher::create () static
References UvDispatcher().
Referenced by main().
create_connection() [1/2]
std::shared_ptr< DBus::Connection > UvDispatcher::create_connection (DBus::BusType type) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, DBus::Connection::create(), and DBus::type().
create_connection() [2/2]
std::shared_ptr< DBus::Connection > UvDispatcher::create_connection (std::string address) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, and DBus::Connection::create().
DBUS_CXX_PROPAGATE_CONST()
DBus::Uv::UvDispatcher::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
The documentation for this class was generated from the following files:
uvdispatcher.h
uvdispatcher.cpp