dbus-cxx: DBus::PropertyProxyBase Class Reference
DBus::PropertyProxyBase Class Reference
Base type of PropertyProxy to allow for storage in e.g.
#include <propertyproxy.h>
Public Member Functions
std::string name () const
Get the name of this propery.
Variant variant_value ()
Get the value of this property as a Variant.
PropertyUpdateType update_type () const
sigc::signal< void(Variant)> signal_generic_property_changed ()
This signal is emitted whenever the property changes.
void set_value (Variant value)
Set the value of this property.
InterfaceProxy * interface_name () const
Protected Member Functions
PropertyProxyBase (std::string name, PropertyUpdateType update)
~PropertyProxyBase ()
Private Member Functions
void set_interface (InterfaceProxy *proxy)
void updated_value (Variant value)
void invalidate ()
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Friends
class InterfaceProxy
Detailed Description
Base type of PropertyProxy to allow for storage in e.g.
a vector.
Constructor & Destructor Documentation
PropertyProxyBase()
PropertyProxyBase::PropertyProxyBase (std::string name, PropertyUpdateType update) protected
~PropertyProxyBase()
PropertyProxyBase::~PropertyProxyBase () protected
Member Function Documentation
DBUS_CXX_PROPAGATE_CONST()
DBus::PropertyProxyBase::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
interface_name()
DBus::InterfaceProxy * PropertyProxyBase::interface_name () const
invalidate()
void PropertyProxyBase::invalidate () private
name()
std::string PropertyProxyBase::name () const
Get the name of this propery.
Returns
Referenced by DBus::PropertyProxy< T_type >::create().
set_interface()
void PropertyProxyBase::set_interface (InterfaceProxy * proxy) private
set_value()
void PropertyProxyBase::set_value (DBus::Variant value)
Set the value of this property.
When used on a remote property(a proxy), this will attempt to set the value on the remote object. If the property is READONLY, this acts as a No-op.
When used on a local property(adapter), this will emit the PropertyChanged DBus signal in order to notify clients that the property has updated. Note that the exact value of the PropertyUpdateType will determine what is emitted(invalidated, new value, or invalidation)
Parameters
value The new value to set
References DBus::Const, and DBus::CallMessage::create().
Referenced by DBus::PropertyProxy< T_type >::set_value().
signal_generic_property_changed()
sigc::signal< void(DBus::Variant)> PropertyProxyBase::signal_generic_property_changed ()
This signal is emitted whenever the property changes.
Returns
Referenced by DBus::PropertyProxy< T_type >::PropertyProxy().
update_type()
DBus::PropertyUpdateType PropertyProxyBase::update_type () const
updated_value()
void PropertyProxyBase::updated_value (Variant value) private
Referenced by variant_value().
variant_value()
DBus::Variant PropertyProxyBase::variant_value ()
Get the value of this property as a Variant.
If the value is stale, this will go and query the latest value from the remote object.
Returns
References DBus::CallMessage::create(), DBUS_CXX_PROPERTIES_INTERFACE, and updated_value().
Referenced by DBus::PropertyProxy< T_type >::value().
Friends And Related Function Documentation
InterfaceProxy
friend class InterfaceProxy friend
The documentation for this class was generated from the following files:
propertyproxy.h
propertyproxy.cpp