dbus-cxx: DBus::Signature Class Reference
DBus::Signature Class Reference
Represents a DBus signature.
#include <signature.h>
Public Types
typedef SignatureIterator iterator
typedef const SignatureIterator const_iterator
typedef std::string::size_type size_type
Public Member Functions
Signature ()
Signature (const std::string &s, size_type pos=0, size_type n=npos)
Signature (const char *)
Signature (const char *s, size_type n)
Signature (size_type n, char c)
~Signature ()
operator const std::string & () const
const std::string & str () const
Signature & operator= (const std::string &s)
Signature & operator= (const char *s)
bool operator== (const std::string &s) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool is_valid () const
True if the signature is a valid DBus signature.
bool is_singleton () const
True if the signature is a valid DBus signature and contains exactly one complete type.
void print_tree (std::ostream *stream) const
Print the signature tree to the given ostream.
Static Public Attributes
static const size_type npos = std::string::npos
Private Member Functions
void initialize ()
std::shared_ptr< priv::SignatureNode > create_signature_tree (std::string::const_iterator *it, std::stack< ContainerType > *container_stack, bool *ok)
void print_node (std::ostream *stream, priv::SignatureNode *node, int spaces) const
Private Attributes
std::shared_ptr< priv_data > m_priv
Detailed Description
Represents a DBus signature.
DBus signatures indicate what type of data the message contains/the method parameters.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
const_iterator
typedef const SignatureIterator DBus::Signature::const_iterator
iterator
typedef SignatureIterator DBus::Signature::iterator
size_type
typedef std::string::size_type DBus::Signature::size_type
Constructor & Destructor Documentation
Signature() [1/5]
DBus::Signature::Signature ()
Signature() [2/5]
DBus::Signature::Signature (const std::string & s, size_type pos = 0, size_type n = npos)
References initialize(), and m_priv.
Signature() [3/5]
DBus::Signature::Signature (const char * s)
References initialize(), and m_priv.
Signature() [4/5]
DBus::Signature::Signature (const char * s, size_type n)
References initialize(), and m_priv.
Signature() [5/5]
DBus::Signature::Signature (size_type n, char c)
References initialize(), and m_priv.
~Signature()
DBus::Signature::~Signature ()
Member Function Documentation
begin() [1/2]
Signature::iterator DBus::Signature::begin ()
References m_priv.
Referenced by DBus::Demarshaling::demarshal_variant(), DBus::ErrorMessage::message(), DBus::MessageIterator::MessageIterator(), DBus::MessageAppendIterator::open_container(), DBus::priv::VariantAppendIterator::open_container(), DBus::MessageAppendIterator::operator<<(), and DBus::priv::VariantIterator::VariantIterator().
begin() [2/2]
Signature::const_iterator DBus::Signature::begin () const
References m_priv.
create_signature_tree()
std::shared_ptr< priv::SignatureNode > DBus::Signature::create_signature_tree (std::string::const_iterator * it, std::stack< ContainerType > * container_stack, bool * ok) private
References DBus::ARRAY, DBus::char_to_container_type(), DBus::char_to_dbus_type(), DBus::DICT_ENTRY, DBus::INVALID, DBus::TypeInfo::is_basic(), DBus::TypeInfo::is_container(), DBus::is_ending_container(), m_priv, DBus::STRUCT, and DBus::VARIANT.
Referenced by initialize().
end() [1/2]
Signature::iterator DBus::Signature::end ()
Referenced by DBus::MessageAppendIterator::operator<<().
end() [2/2]
Signature::const_iterator DBus::Signature::end () const
initialize()
void DBus::Signature::initialize () private
References create_signature_tree(), LOGGER_NAME, m_priv, SIMPLELOGGER_DEBUG, and SIMPLELOGGER_TRACE.
Referenced by Signature().
is_singleton()
bool DBus::Signature::is_singleton () const
True if the signature is a valid DBus signature and contains exactly one complete type.
References DBus::INVALID, and m_priv.
is_valid()
bool DBus::Signature::is_valid () const
True if the signature is a valid DBus signature.
References m_priv.
operator const std::string &()
DBus::Signature::operator const std::string & () const
operator=() [1/2]
Signature & DBus::Signature::operator= (const char * s)
References m_priv.
operator=() [2/2]
Signature & DBus::Signature::operator= (const std::string & s)
References m_priv.
operator==()
bool DBus::Signature::operator== (const std::string & s) const inline
References str().
print_node()
void DBus::Signature::print_node (std::ostream * stream, priv::SignatureNode * node, int spaces) const private
References DBus::priv::SignatureNode::m_dataType.
print_tree()
void DBus::Signature::print_tree (std::ostream * stream) const
Print the signature tree to the given ostream.
Parameters
stream
References m_priv.
str()
const std::string & DBus::Signature::str () const
References m_priv.
Referenced by DBus::Message::append_signature(), DBus::Marshaling::marshal(), DBus::MessageAppendIterator::operator<<(), DBus::operator<<(), and operator==().
Member Data Documentation
m_priv
std::shared_ptr<priv_data> DBus::Signature::m_priv private
Referenced by begin(), create_signature_tree(), initialize(), is_singleton(), is_valid(), operator=(), print_tree(), Signature(), and str().
npos
const size_type DBus::Signature::npos = std::string::npos static
The documentation for this class was generated from the following files:
signature.h
signature.cpp