dbus-cxx: DBus::Timeout Class Reference
DBus::Timeout Class Reference
Provides timeouts that can be armed/disarmed as necessary.
#include <timeout.h>
Public Types
typedef DBusCxxPointer< Timeout > pointer
typedef DBusCxxWeakPointer< Timeout > weak_pointer
Public Member Functions
~Timeout ()
bool is_valid () const
operator bool () const
int interval () const
bool is_enabled () const
bool handle ()
bool operator== (const Timeout &other) const
bool operator!= (const Timeout &other) const
void arm (bool should_arm=true)
bool is_armed ()
DBusTimeout * cobj ()
operator DBusTimeout * ()
Static Public Member Functions
static pointer create (DBusTimeout *cobj=NULL)
Protected Member Functions
Timeout (DBusTimeout *cobj=NULL)
Static Protected Member Functions
static void timer_callback_proxy (sigval_t sv)
Protected Attributes
DBusTimeout * m_cobj
timer_t m_timer_id
bool m_is_armed
std::mutex m_arming_mutex
Detailed Description
Provides timeouts that can be armed/disarmed as necessary.
Typically used by connections as requested by the underlying dbus library.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
typedef DBusCxxPointer<Timeout> DBus::Timeout::pointer
weak_pointer
typedef DBusCxxWeakPointer<Timeout> DBus::Timeout::weak_pointer
Constructor & Destructor Documentation
Timeout()
DBus::Timeout::Timeout (DBusTimeout * cobj = NULL) protected
References m_cobj.
Referenced by create().
~Timeout()
DBus::Timeout::~Timeout ()
References m_arming_mutex, m_is_armed, and m_timer_id.
Member Function Documentation
arm()
void DBus::Timeout::arm (bool should_arm = true)
References interval(), m_arming_mutex, m_is_armed, m_timer_id, and timer_callback_proxy().
cobj()
DBusTimeout * DBus::Timeout::cobj ()
References m_cobj.
create()
Timeout::pointer DBus::Timeout::create (DBusTimeout * cobj = NULL) static
References Timeout().
Referenced by DBus::Connection::on_add_timeout_callback(), DBus::Connection::on_remove_timeout_callback(), and DBus::Connection::on_timeout_toggled_callback().
handle()
bool DBus::Timeout::handle ()
References is_valid(), and m_cobj.
Referenced by timer_callback_proxy().
interval()
int DBus::Timeout::interval () const
References is_valid(), and m_cobj.
Referenced by arm().
is_armed()
bool DBus::Timeout::is_armed ()
References m_is_armed.
is_enabled()
bool DBus::Timeout::is_enabled () const
References is_valid(), and m_cobj.
is_valid()
bool DBus::Timeout::is_valid () const
References m_cobj.
Referenced by handle(), interval(), is_enabled(), operator bool(), and timer_callback_proxy().
operator bool()
DBus::Timeout::operator bool () const
References is_valid().
operator DBusTimeout *()
DBus::Timeout::operator DBusTimeout * ()
References m_cobj.
operator!=()
bool DBus::Timeout::operator!= (const Timeout & other) const
References m_cobj.
operator==()
bool DBus::Timeout::operator== (const Timeout & other) const
References m_cobj.
timer_callback_proxy()
void DBus::Timeout::timer_callback_proxy (sigval_t sv) static protected
References handle(), and is_valid().
Referenced by arm().
Member Data Documentation
m_arming_mutex
std::mutex DBus::Timeout::m_arming_mutex protected
Referenced by arm(), and ~Timeout().
m_cobj
DBusTimeout* DBus::Timeout::m_cobj protected
Referenced by cobj(), handle(), interval(), is_enabled(), is_valid(), operator DBusTimeout *(), operator!=(), operator==(), and Timeout().
m_is_armed
bool DBus::Timeout::m_is_armed protected
Referenced by arm(), is_armed(), and ~Timeout().
m_timer_id
timer_t DBus::Timeout::m_timer_id protected
Referenced by arm(), and ~Timeout().
The documentation for this class was generated from the following files:
timeout.h
timeout.cpp