dbus-cxx: DBus::PropertyProxy< T_type > Class Template Reference
DBus::PropertyProxy< T_type > Class Template Reference
Represents a remote DBus property.
#include <propertyproxy.h>
Public Member Functions
sigc::signal< void(T_type)> signal_property_changed ()
void set_value (T_type t)
T_type value ()
Public Member Functions inherited from DBus::PropertyProxyBase
std::string name () const
Get the name of this propery.
Variant variant_value ()
Get the value of this property as a Variant.
PropertyUpdateType update_type () const
sigc::signal< void(Variant)> signal_generic_property_changed ()
This signal is emitted whenever the property changes.
void set_value (Variant value)
Set the value of this property.
InterfaceProxy * interface_name () const
Static Public Member Functions
static std::shared_ptr< PropertyProxy< T_type > > create (std::string name, PropertyUpdateType update)
Private Member Functions
PropertyProxy (std::string name, PropertyUpdateType update)
void parentUpdated (Variant v)
Private Attributes
sigc::signal< void(T_type)> m_signal_changed
Additional Inherited Members
Protected Member Functions inherited from DBus::PropertyProxyBase
PropertyProxyBase (std::string name, PropertyUpdateType update)
~PropertyProxyBase ()
Detailed Description
template<typename T_type>
class DBus::PropertyProxy< T_type >
Represents a remote DBus property.
Properties can be Read, Write, or Readonly.
Constructor & Destructor Documentation
PropertyProxy()
template<typename T_type > DBus::PropertyProxy< T_type >::PropertyProxy (std::string name, PropertyUpdateType update) inline private
References DBus::PropertyProxy< T_type >::parentUpdated(), and DBus::PropertyProxyBase::signal_generic_property_changed().
Member Function Documentation
create()
template<typename T_type > static std::shared_ptr< PropertyProxy< T_type > > DBus::PropertyProxy< T_type >::create (std::string name, PropertyUpdateType update) inline static
References DBus::PropertyProxyBase::name().
Referenced by DBus::InterfaceProxy::create_property().
parentUpdated()
template<typename T_type > void DBus::PropertyProxy< T_type >::parentUpdated (Variant v) inline private
References DBus::PropertyProxy< T_type >::m_signal_changed.
Referenced by DBus::PropertyProxy< T_type >::PropertyProxy().
set_value()
template<typename T_type > void DBus::PropertyProxy< T_type >::set_value (T_type t) inline
References DBus::PropertyProxyBase::set_value().
signal_property_changed()
template<typename T_type > sigc::signal< void(T_type)> DBus::PropertyProxy< T_type >::signal_property_changed () inline
References DBus::PropertyProxy< T_type >::m_signal_changed.
value()
template<typename T_type > T_type DBus::PropertyProxy< T_type >::value () inline
References DBus::PropertyProxyBase::variant_value().
Member Data Documentation
m_signal_changed
template<typename T_type > sigc::signal<void(T_type)> DBus::PropertyProxy< T_type >::m_signal_changed private
Referenced by DBus::PropertyProxy< T_type >::parentUpdated(), and DBus::PropertyProxy< T_type >::signal_property_changed().
The documentation for this class was generated from the following file:
propertyproxy.h