DBus::Watch Class Reference
DBus::Watch Class Reference
Provides file descriptor watches.
#include <watch.h>
Public Types
typedef DBusCxxPointer< Watch > pointer
typedef DBusCxxWeakPointer< Watch > weak_pointer
Public Member Functions
~Watch ()
bool is_valid () const
operator bool () const
int unix_fd () const
int socket () const
unsigned int flags () const
bool is_readable () const
bool is_writable () const
bool is_enabled () const
bool handle (unsigned int flags)
bool handle_read (bool error=false, bool hangup=false)
bool handle_write (bool error=false, bool hangup=false)
bool handle_readwrite (bool error=false, bool hangup=false)
DBusWatch * cobj ()
const DBusWatch * cobj () const
operator DBusWatch * ()
Static Public Member Functions
static pointer create (DBusWatch *cobj=NULL)
Protected Member Functions
Watch (DBusWatch *cobj=NULL)
Protected Attributes
DBusWatch * m_cobj
Detailed Description
Provides file descriptor watches.
Typically used by connections as requested by the underlying dbus library.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
typedef DBusCxxPointer<Watch> DBus::Watch::pointer
weak_pointer
typedef DBusCxxWeakPointer<Watch> DBus::Watch::weak_pointer
Constructor & Destructor Documentation
Watch()
DBus::Watch::Watch (DBusWatch * cobj = NULL) protected
References m_cobj.
Referenced by create().
~Watch()
DBus::Watch::~Watch ()
Member Function Documentation
cobj() [1/2]
DBusWatch * DBus::Watch::cobj ()
References m_cobj.
Referenced by operator DBusWatch *().
cobj() [2/2]
const DBusWatch * DBus::Watch::cobj () const
References m_cobj.
create()
Watch::pointer DBus::Watch::create (DBusWatch * cobj = NULL) static
References Watch().
Referenced by DBus::Connection::on_add_watch_callback(), DBus::Connection::on_remove_watch_callback(), and DBus::Connection::on_watch_toggled_callback().
flags()
unsigned int DBus::Watch::flags () const
References is_valid(), m_cobj, and DBus::WATCH_ERROR.
Referenced by handle_read(), handle_readwrite(), handle_write(), is_readable(), and is_writable().
handle()
bool DBus::Watch::handle (unsigned int flags)
References is_valid(), and m_cobj.
Referenced by handle_read(), handle_readwrite(), and handle_write().
handle_read()
bool DBus::Watch::handle_read (bool error = false, bool hangup = false)
References flags(), handle(), DBus::WATCH_ERROR, DBus::WATCH_HANGUP, and DBus::WATCH_READABLE.
handle_readwrite()
bool DBus::Watch::handle_readwrite (bool error = false, bool hangup = false)
References flags(), handle(), DBus::WATCH_ERROR, DBus::WATCH_HANGUP, DBus::WATCH_READABLE, and DBus::WATCH_WRITABLE.
handle_write()
bool DBus::Watch::handle_write (bool error = false, bool hangup = false)
References flags(), handle(), DBus::WATCH_ERROR, DBus::WATCH_HANGUP, and DBus::WATCH_WRITABLE.
is_enabled()
bool DBus::Watch::is_enabled () const
References is_valid(), and m_cobj.
is_readable()
bool DBus::Watch::is_readable () const
References flags(), and DBus::WATCH_READABLE.
is_valid()
bool DBus::Watch::is_valid () const
References m_cobj.
Referenced by flags(), handle(), is_enabled(), operator bool(), socket(), and unix_fd().
is_writable()
bool DBus::Watch::is_writable () const
References flags(), and DBus::WATCH_WRITABLE.
operator bool()
DBus::Watch::operator bool () const
References is_valid().
operator DBusWatch *()
DBus::Watch::operator DBusWatch * ()
References cobj().
socket()
int DBus::Watch::socket () const
References is_valid(), and m_cobj.
unix_fd()
int DBus::Watch::unix_fd () const
References is_valid(), and m_cobj.
Member Data Documentation
m_cobj
DBusWatch* DBus::Watch::m_cobj protected
Referenced by cobj(), flags(), handle(), is_enabled(), is_valid(), socket(), unix_fd(), and Watch().
The documentation for this class was generated from the following files:
watch.h
watch.cpp