DBus::ReturnMessage Class Reference
DBus::ReturnMessage Class Reference
DBus Messages
Represents a DBus call return message.
#include <returnmessage.h>
Public Types
typedef DBusCxxPointer< ReturnMessage > pointer
typedef DBusCxxPointer< const ReturnMessage > const_pointer
typedef DBusCxxWeakPointer< ReturnMessage > weak_pointer
Public Types inherited from DBus::Message
typedef DBusCxxPointer< Message > pointer
typedef DBusCxxPointer< const Message > const_pointer
typedef DBusCxxWeakPointer< Message > weak_pointer
typedef MessageIterator iterator
typedef MessageAppendIterator append_iterator
Public Member Functions
const char * signature () const
bool has_signature (const std::string &signature) const
ReturnMessage & operator= (const Message &other)
bool set_reply_serial (uint32_t)
uint32_t reply_serial () const
Public Member Functions inherited from DBus::Message
DBusCxxPointer< ReturnMessage > create_reply () const
virtual ~Message ()
Message & operator= (const Message &m)
bool operator== (const Message &other)
bool is_valid () const
void invalidate ()
operator bool () const
uint32_t serial () const
int type () const
void set_auto_start (bool auto_start)
bool auto_start ()
bool set_destination (const std::string &s)
const char * destination () const
bool set_sender (const std::string &s)
const char * sender () const
bool is_call (const std::string &interface, const std::string &method) const
bool is_signal (const std::string &interface, const std::string &signal_name) const
bool is_error (const std::string &error_name) const
bool has_destination (const std::string &name) const
bool has_sender (const std::string &name) const
template<typename T >
iterator operator>> (T &value) const
template<typename T >
append_iterator operator<< (const T &value)
iterator begin () const
iterator end () const
append_iterator append ()
DBusMessage * cobj () const
Static Public Member Functions
static pointer create ()
static pointer create (DBusMessage *callee)
static pointer create (Message::pointer callee)
static pointer create (Message::const_pointer callee)
Static Public Member Functions inherited from DBus::Message
static pointer create (MessageType type)
static pointer create (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::pointer other, CreateMethod m=CREATE_ALIAS)
static pointer create (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Protected Member Functions
ReturnMessage ()
ReturnMessage (DBusMessage *callee)
ReturnMessage (Message::pointer callee)
ReturnMessage (Message::const_pointer callee)
Protected Member Functions inherited from DBus::Message
Message (MessageType type)
Message (DBusMessage *cobj=NULL, CreateMethod m=CREATE_ALIAS)
Message (Message::pointer other, CreateMethod m=CREATE_ALIAS)
Message (Message::const_pointer other, CreateMethod m=CREATE_ALIAS)
Additional Inherited Members
Protected Attributes inherited from DBus::Message
DBusMessage * m_cobj
bool m_valid
Detailed Description
Represents a DBus call return message.
This class inherits from Message and uses the dbus_message_* methods to create an interface for a return message that is a response to a call message.
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
const_pointer
typedef DBusCxxPointer<const ReturnMessage> DBus::ReturnMessage::const_pointer
pointer
typedef DBusCxxPointer<ReturnMessage> DBus::ReturnMessage::pointer
weak_pointer
typedef DBusCxxWeakPointer<ReturnMessage> DBus::ReturnMessage::weak_pointer
Constructor & Destructor Documentation
ReturnMessage() [1/4]
DBus::ReturnMessage::ReturnMessage () protected
Referenced by create().
ReturnMessage() [2/4]
DBus::ReturnMessage::ReturnMessage (DBusMessage * callee) protected
ReturnMessage() [3/4]
DBus::ReturnMessage::ReturnMessage (Message::pointer callee) protected
ReturnMessage() [4/4]
DBus::ReturnMessage::ReturnMessage (Message::const_pointer callee) protected
Member Function Documentation
create() [1/4]
ReturnMessage::pointer DBus::ReturnMessage::create () static
References ReturnMessage().
Referenced by DBus::Message::create_reply(), and DBus::Connection::send_with_reply_blocking().
create() [2/4]
ReturnMessage::pointer DBus::ReturnMessage::create (DBusMessage * callee) static
References ReturnMessage().
create() [3/4]
ReturnMessage::pointer DBus::ReturnMessage::create (Message::pointer callee) static
References ReturnMessage().
create() [4/4]
ReturnMessage::pointer DBus::ReturnMessage::create (Message::const_pointer callee) static
References ReturnMessage().
has_signature()
bool DBus::ReturnMessage::has_signature (const std::string & signature) const
References DBus::Message::m_cobj.
operator=()
ReturnMessage & DBus::ReturnMessage::operator= (const Message & other)
References DBus::Message::cobj(), and DBus::Message::m_cobj.
reply_serial()
uint32_t DBus::ReturnMessage::reply_serial () const
References DBus::Message::m_cobj.
set_reply_serial()
bool DBus::ReturnMessage::set_reply_serial (uint32_t s)
References DBus::Message::m_cobj.
signature()
const char * DBus::ReturnMessage::signature () const
References DBus::Message::m_cobj.
The documentation for this class was generated from the following files:
returnmessage.h
returnmessage.cpp