dbus-cxx: CalleeClass Class Reference
CalleeClass Class Reference
#include <calleeclass.h>
Public Member Functions
int add (int a, int b)
int add (int a, int b)
int add (int a, int b)
Public Member Functions inherited from DBus::Object
virtual ~Object ()
const Path & path () const
Returns the path this handler is associated with.
std::weak_ptr< Connection > connection () const
Returns the connection this handler is registered with.
bool unregister ()
Unregisters the handler.
sigc::signal< void(std::shared_ptr< Connection >) > & signal_registered ()
Emitted when this object is registered with a connection.
sigc::signal< void(std::shared_ptr< Connection >) > & signal_unregistered ()
Emitted when this object is unregistered from a connection.
void set_connection (std::shared_ptr< Connection > conn)
Sets the connection that this object is on.
const Interfaces & interfaces () const
Get all the interfaces associated with this Object instance.
std::shared_ptr< Interface > interface_by_name (const std::string &name) const
Returns the interface with the given name.
bool add_interface (std::shared_ptr< Interface > interface_by_name)
Adds the interface to this object.
std::shared_ptr< Interface > create_interface (const std::string &name)
Creates and adds the named interface to this object.
template<typename T_type >
std::shared_ptr< Method< T_type > > create_method (const std::string &method_name, sigc::slot< T_type > slot)
Creates a method with a signature based on the.
template<typename T_type >
std::shared_ptr< Method< T_type > > create_method (const std::string &interface_name, const std::string &method_name, sigc::slot< T_type > slot)
Creates a method with a signature based on the.
template<typename T_type >
std::shared_ptr< Property< T_type > > create_property (const std::string &interface_name, const std::string &property_name, PropertyAccess access_type=PropertyAccess::ReadWrite, PropertyUpdateType update_type=PropertyUpdateType::Updates)
void remove_interface (const std::string &name)
Removes the interface found with the given name.
bool has_interface (const std::string &name)
Test whether an Object has a named interface.
std::shared_ptr< Interface > default_interface () const
Get the default interface associated with this object.
bool set_default_interface (const std::string &new_default_name)
Set the default interface to a specific name.
bool set_default_interface (std::shared_ptr< Interface > interface_by_name)
Set the default interface for handling calls to no interface.
void remove_default_interface ()
Removes the currently set (if any) default interface.
template<class... T_type>
std::shared_ptr< Signal< T_type... > > create_signal (const std::string &name)
Creates a signal with a return value (possibly void) and a variable number of parameters and adds it to the default interface.
template<class... T_type>
std::shared_ptr< Signal< T_type... > > create_signal (const std::string &iface, const std::string &name)
Creates a signal with a return value (possibly void) and a variable number of parameters and adds it to the named interface.
const Children & children () const
Get the children associated with this object instance.
std::shared_ptr< Object > child (const std::string &name) const
Get a named child of this object.
bool add_child (const std::string &name, std::shared_ptr< Object > child, bool force=false)
Add an object as a child with a specified name This method will fail if the object already has a child with the specified name and force is not set.
bool remove_child (const std::string &name)
Remove the named child from this object.
bool has_child (const std::string &name) const
Test whether an object has a child with a specified name.
bool has_child (std::shared_ptr< Object > child) const
std::string introspect (int space_depth=0) const
Returns a DBus XML description of this interface.
sigc::signal< void(std::shared_ptr< Interface >) > signal_interface_added ()
Signal emitted when an interface is added to this object.
sigc::signal< void(std::shared_ptr< Interface >) > signal_interface_removed ()
Signal emitted when an interface is removed from this object.
sigc::signal< void(std::shared_ptr< Interface >, std::shared_ptr< Interface >)> signal_default_interface_changed ()
Signal emitted when the default interface of this object is changed.
HandlerResult handle_message (std::shared_ptr< const Message > msg)
Handles the specified message on the specified connection.
void set_handling_thread (std::thread::id thr)
std::thread::id handling_thread ()
bool is_lightweight () const
bool has_objectmanager () const
void set_has_objectmanager (bool objectmanager)
Static Public Member Functions
static std::shared_ptr< CalleeClass > create (std::string path)
static std::shared_ptr< CalleeClass > create (std::string path)
static std::shared_ptr< CalleeClass > create (std::string path)
Static Public Member Functions inherited from DBus::Object
static std::shared_ptr< Object > create (const std::string &path=std::string())
Create an Object that will be exported out onto the bus.
static std::shared_ptr< Object > create_lightweight (const std::string &path=std::string())
Private Member Functions
CalleeClass (std::string path)
CalleeClass (std::string path)
CalleeClass (std::string path)
Additional Inherited Members
Public Types inherited from DBus::Object
typedef std::map< std::string, std::shared_ptr< Interface > > Interfaces
Typedef to the storage structure for an Object instance's interfaces.
typedef std::map< std::string, std::shared_ptr< Object > > Children
Typedef to storage structure for an Object instance's children.
Protected Member Functions inherited from DBus::Object
Object (const std::string &path)
This class has a protected constructor.
Constructor & Destructor Documentation
CalleeClass() [1/3]
CalleeClass::CalleeClass (std::string path) private
References add().
Referenced by create().
CalleeClass() [2/3]
CalleeClass::CalleeClass (std::string path) private
CalleeClass() [3/3]
CalleeClass::CalleeClass (std::string path) private
Member Function Documentation
add() [1/3]
int CalleeClass::add (int a, int b)
Referenced by CalleeClass().
add() [2/3]
int CalleeClass::add (int a, int b)
add() [3/3]
int CalleeClass::add (int a, int b)
create() [1/3]
std::shared_ptr< CalleeClass > CalleeClass::create (std::string path) static
References CalleeClass(), and DBus::Object::path().
Referenced by main().
create() [2/3]
static std::shared_ptr< CalleeClass > CalleeClass::create (std::string path) static
create() [3/3]
static std::shared_ptr< CalleeClass > CalleeClass::create (std::string path) static
The documentation for this class was generated from the following files:
dbus-cxx-glib/unit-tests/calleeclass.h
dbus-cxx-qt/unit-tests/calleeclass.h
dbus-cxx-uv/unit-tests/calleeclass.h
dbus-cxx-glib/unit-tests/calleeclass.cpp
dbus-cxx-qt/unit-tests/calleeclass.cpp
dbus-cxx-uv/unit-tests/calleeclass.cpp