dbus-cxx: DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil > Class Template Reference
Objects | Proxy
#include <methodproxy.h>
Public Types
typedef DBusCxxPointer< MethodProxy > pointer
Public Types inherited from DBus::MethodProxyBase
typedef DBusCxxPointer< MethodProxyBase > pointer
Public Member Functions
MethodProxy (const std::string &name)
T_return operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4)
Public Member Functions inherited from DBus::MethodProxyBase
~MethodProxyBase ()
InterfaceProxy * interface () const
const std::string & name () const
void set_name (const std::string &name)
CallMessage::pointer create_call_message () const
ReturnMessage::const_pointer call (CallMessage::const_pointer, int timeout_milliseconds=-1) const
PendingCall::pointer call_async (CallMessage::const_pointer, int timeout_milliseconds=-1) const
sigc::signal< void, const std::string &, const std::string & > signal_name_changed ()
Static Public Member Functions
static pointer create (const std::string &name)
Static Public Member Functions inherited from DBus::MethodProxyBase
static pointer create (const std::string &name)
Additional Inherited Members
Protected Member Functions inherited from DBus::MethodProxyBase
MethodProxyBase (const std::string &name)
MethodProxyBase (const MethodProxyBase &other)
Protected Attributes inherited from DBus::MethodProxyBase
InterfaceProxy * m_interface
std::string m_name
pthread_mutex_t m_name_mutex
Ensures that the name doesn't change while the name changed signal is emitting.
sigc::signal< void, const std::string &, const std::string & > m_signal_name_changed
Detailed Description
template<class T_return, class T_arg1, class T_arg2, class T_arg3, class T_arg4>
class DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >
Author
Rick L Vinyard Jr rviny.nosp@m.ard@.nosp@m.cs.nm.nosp@m.su.e.nosp@m.du
Member Typedef Documentation
pointer
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > typedef DBusCxxPointer<MethodProxy> DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::pointer
Constructor & Destructor Documentation
MethodProxy()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::MethodProxy (const std::string & name) inline
Member Function Documentation
create()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > static pointer DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::create (const std::string & name) inline static
References DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7 >::MethodProxy().
operator()()
template<class T_return , class T_arg1 , class T_arg2 , class T_arg3 , class T_arg4 > T_return DBus::MethodProxy< T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil >::operator() (T_arg1 _val_1, T_arg2 _val_2, T_arg3 _val_3, T_arg4 _val_4) inline
References DBus::MethodProxyBase::call(), DBus::MethodProxyBase::create_call_message(), DBUSCXX_DEBUG_STDSTR, and DBus::MethodProxyBase::m_name.
The documentation for this class was generated from the following file:
methodproxy.h