dbus-cxx: DBus::Qt::QtDispatcher Class Reference
DBus::Qt::QtDispatcher Class Reference
#include <qtdispatcher.h>
Public Member Functions
~QtDispatcher ()
std::shared_ptr< Connection > create_connection (BusType type)
std::shared_ptr< Connection > create_connection (std::string address)
bool add_connection (std::shared_ptr< Connection > connection)
Public Member Functions inherited from DBus::Dispatcher
virtual ~Dispatcher ()
Static Public Member Functions
static std::shared_ptr< QtDispatcher > create ()
Private Slots
void activated (int socket)
Private Member Functions
QtDispatcher ()
DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) m_priv
Constructor & Destructor Documentation
QtDispatcher()
QtDispatcher::QtDispatcher () private
Referenced by create().
~QtDispatcher()
QtDispatcher::~QtDispatcher ()
Member Function Documentation
activated
void QtDispatcher::activated (int socket) private slot
References DBus::COMPLETE, and conn.
Referenced by add_connection().
add_connection()
bool QtDispatcher::add_connection (std::shared_ptr< Connection > connection) virtual
Implements DBus::Dispatcher.
References activated().
Referenced by create_connection().
create()
std::shared_ptr< QtDispatcher > QtDispatcher::create () static
References QtDispatcher().
Referenced by main().
create_connection() [1/2]
std::shared_ptr< DBus::Connection > QtDispatcher::create_connection (DBus::BusType type) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, DBus::Connection::create(), and DBus::type().
create_connection() [2/2]
std::shared_ptr< DBus::Connection > QtDispatcher::create_connection (std::string address) virtual
Implements DBus::Dispatcher.
References add_connection(), conn, and DBus::Connection::create().
DBUS_CXX_PROPAGATE_CONST()
DBus::Qt::QtDispatcher::DBUS_CXX_PROPAGATE_CONST (std::unique_ptr< priv_data >) private
The documentation for this class was generated from the following files:
qtdispatcher.h
qtdispatcher.cpp