dbus-cxx: sasl.cpp File Reference
sasl.cpp File Reference
#include "sasl.h"
#include "dbus-cxx-private.h"
#include <cstring>
#include <ostream>
#include <poll.h>
#include <regex>
#include <sstream>
#include <unistd.h>
Functions
static const std::regex OK_REGEX ("OK ([a-z0-9]*)")
static const std::regex DATA_REGEX ("DATA ([a-z0-9]*)")
static const std::regex ERROR_REGEX ("ERROR(.*)")
static const std::regex AGREE_UNIX_FD_REGEX ("AGREE_UNIX_FD")
static const std::regex REJECTED_REGEX ("REJECTED (.*)")
static int hexchar2int (char c)
Variables
static const char * LOGGER_NAME = "DBus.priv.SASL"
Function Documentation
AGREE_UNIX_FD_REGEX()
static const std::regex AGREE_UNIX_FD_REGEX ("AGREE_UNIX_FD") static
Referenced by DBus::priv::SASL::authenticate().
DATA_REGEX()
static const std::regex DATA_REGEX ("DATA ([a-z0-9]*)") static
ERROR_REGEX()
static const std::regex ERROR_REGEX ("ERROR(.*)") static
Referenced by DBus::priv::SASL::authenticate().
hexchar2int()
static int hexchar2int (char c) static
Referenced by DBus::priv::SASL::hex_to_vector().
OK_REGEX()
static const std::regex OK_REGEX ("OK ([a-z0-9]*)") static
Referenced by DBus::priv::SASL::authenticate().
REJECTED_REGEX()
static const std::regex REJECTED_REGEX ("REJECTED (.*)") static
Referenced by DBus::priv::SASL::authenticate().
Variable Documentation
LOGGER_NAME
const char* LOGGER_NAME = "DBus.priv.SASL" static
Referenced by DBus::priv::SASL::read_data(), and DBus::priv::SASL::write_data_with_newline().