dbus-cxx: test-glib-dispatcher.cpp File Reference
test-glib-dispatcher.cpp File Reference
#include <dbus-cxx-glib.h>
#include "calleeclass.h"
Functions
static int doexit (gpointer user_data)
int main (int argc, char **argv)
Function Documentation
doexit()
static int doexit (gpointer user_data) static
Referenced by main().
main()
int main (int argc, char ** argv)
References conn, DBus::GLib::GLibDispatcher::create(), CalleeClass::create(), DBus::CurrentThread, doexit(), DBus::log_std_err(), DBus::SESSION, DBus::set_log_level(), DBus::set_logging_function(), and SL_TRACE.