dbus-cxx: test-qt-dispatcher.cpp File Reference
test-qt-dispatcher.cpp File Reference
#include <QCoreApplication>
#include <QTimer>
#include <dbus-cxx-qt.h>
#include "calleeclass.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References conn, DBus::Qt::QtDispatcher::create(), DBus::Qt::QtThreadDispatcher::create(), DBus::StandaloneDispatcher::create(), CalleeClass::create(), DBus::CurrentThread, DBus::log_std_err(), DBus::SESSION, DBus::set_log_level(), DBus::set_logging_function(), and SL_TRACE.