dbus-cxx: validator.cpp File Reference
validator.cpp File Reference
#include "validator.h"
Functions
static bool is_allowable_character (char c)
Function Documentation
is_allowable_character()
static bool is_allowable_character (char c) static
Referenced by DBus::Validator::validate_bus_name(), DBus::Validator::validate_interface_name(), and DBus::Validator::validate_member_name().